### ISSUE TITLE
Do not allow constraint_cols to contain control column (Was: Partitioning on bigint field)

### ISSUE THREAD

**Issue by goldjee** [keithf4/pg_partman#100]
Is it possible to partition table based on bigint field? It appears that calling create_parent() using p_type='id' doesn't work with values not fitting into int.

**Comment by keithf4** [comment]
Yes that should work. Can you give me an example schema and/or some data and the full create_parent() command you used?

**Comment by goldjee** [comment]
Seems it's not working for me. First of all, I'm running Postgresql 9.5 with the latest version of pg_partman (downloaded it yesterday).

The example schema is
```
CREATE TABLE data."dataMatchSlotDetail"
(
  "matchID" bigint NOT NULL,
  "accID" integer NOT NULL,
  team smallint NOT NULL,
  slot smallint NOT NULL,
  item0 smallint,
  item1 smallint,
  item2 smallint,
  item3 smallint,
  item4 smallint,
  item5 smallint,
  kills smallint,
  deaths smallint,
  assists smallint,
  "leaverStatus" smallint,
  gold integer,
  "lastHits" integer,
  denies integer,
  "goldPerMin" numeric(9,4),
  "xpPerMin" numeric(9,4),
  "goldSpent" integer,
  "heroDamage" integer,
  "heroHealing" integer,
  level smallint,
  "abilityUpgrades" character varying(2044),
  "heroID" smallint,
  CONSTRAINT "dataMatchSlotDetail_pkey" PRIMARY KEY ("matchID", team, slot)
)
WITH (
  OIDS=FALSE,
  autovacuum_enabled=true,
  toast.autovacuum_enabled=true
);

CREATE INDEX "dataMatchSlotDetail_idx"
  ON data."dataMatchSlotDetail"
  USING btree
  ("matchID" DESC NULLS LAST, "accID", "heroID");
ALTER TABLE data."dataMatchSlotDetail" CLUSTER ON "dataMatchSlotDetail_idx";
```
It contains about 180 million rows. My `create_parent()` command is as follows:
```
select partman.create_parent(p_parent_table := 'data.dataMatchSlotDetail',
p_control := 'matchID',
p_type := 'id',
p_interval := '1000000',
p_constraint_cols := '{"matchID"}',
p_use_run_maintenance := true,
p_debug := true);
```
As my table already contains data and `create_parent()` doesn't move anything to partitions, after that I run
`select partman.partition_data_id('data.dataMatchSlotDetail');`
After some time i get message
![image](https://cloud.githubusercontent.com/assets/7242338/13901314/7621bdc2-ee30-11e5-9586-b7bc1098f18f.png)
Next, to update info about partitions and master table I run `analyze verbose` for each of them.
IDE tells me that my partitions (except the first one) don't contain any data:
![image](https://cloud.githubusercontent.com/assets/7242338/13901362/6c92f4e0-ee32-11e5-80f1-8887f6ec4be1.png)
Confirming that by determining matchID bounds and its count in parent table only.
```
select min("matchID"), max("matchID") from "data"."dataMatchSlotDetail";
select count("matchID") from only "data"."dataMatchSlotDetail";
```
![image](https://cloud.githubusercontent.com/assets/7242338/13901522/b57cae08-ee37-11e5-8a49-153a13387cea.png)
![image](https://cloud.githubusercontent.com/assets/7242338/13901525/d3c9c8be-ee37-11e5-80c3-1b9a76499a08.png)

So I try to `run_maintenance()` in debug mode just for my parent table (hoping it will do all the job):
`select partman.run_maintenance(p_parent_table := 'data.dataMatchSlotDetail', p_debug := true);`
The function interrupts with the following error message:

> NOTICE:  run_maint: parent_table: data.dataMatchSlotDetail, v_last_partition: dataMatchSlotDetail_p2202000000
> 
> [Err] ERROR:  value "2202000000" is out of range for type integer
> CONTEXT: PL/pgSQL function partman.apply_constraints(text,text,boolean,bigint,boolean) line 107 at assignment
> SQL statement "SELECT partman.apply_constraints(p_parent_table := v_row.parent_table, p_job_id := v_job_id, p_debug := p_debug)"
> PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 304 at PERFORM
> DETAIL: 
> HINT: 
> CONTEXT: SQL statement "SELECT partman.apply_constraints(p_parent_table := v_row.parent_table, p_job_id := v_job_id, p_debug := p_debug)"
> PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 304 at PERFORM
> DETAIL: 
> HINT: 
> 

Probably I'm doing something wrong. I would really appreciate if you point out the mistake.

**Comment by keithf4** [comment]
Are you sure you're running the latest version? There was a bigint syntax error that was fixed in the exact function you're getting the error for in v2.3.0

https://github.com/keithf4/pg_partman/pull/90

**Comment by goldjee** [comment]
```
git clone https://github.com/keithf4/pg_partman.git
cd pg_partman
make install
```
In postgres:
`[SQL]ALTER EXTENSION pg_partman UPDATE TO '2.3.1';`

> NOTICE:  version "2.3.1" of extension "pg_partman" is already installed
> 
> Time: 0.055s
> 
> Affected rows: 0
>

**Comment by keithf4** [comment]
Just realized after your last post that you're trying to set an additional constraint on the control column and that is not necessary (see my answer in https://github.com/keithf4/pg_partman/issues/101). I also answered why all your data didn't get moved. 
Can you try redoing this without setting `p_constraint_cols` in `create_parent()`? Wondering if it may be an edge case not being handled there.

**Comment by keithf4** [comment]
I created a new pgtap test that uses both a bigint value and row values greater than an integer could hold  (>3 billion) https://gist.github.com/keithf4/ceb4ac489ad3ed170baa
This is passing for me on 9.5
```
$ psql --version
psql (PostgreSQL) 9.5.0
$ pg_prove test/test-id.sql 
test/test-id.sql .. 14/? psql:test/test-id.sql:158: NOTICE:  Copied 10 row(s) to the parent. Removed 1 partitions.
psql:test/test-id.sql:162: NOTICE:  Copied 9 row(s) to the parent. Removed 5 partitions.
test/test-id.sql .. ok     
All tests successful.
Files=1, Tests=118,  2 wallclock secs ( 0.05 usr  0.01 sys +  0.01 cusr  0.01 csys =  0.08 CPU)
Result: PASS
```

**Comment by goldjee** [comment]
Thank you for your help. Works for me now.

**Comment by keithf4** [comment]
No need to close this yet. The fact that it seems to do that when you set a constraint like that is still a bit of a concern. I'll probably add a check to the config table to ensure that you cannot set the control column as a constraint column as well. Leaving this open so I don't forget.

**Comment by keithf4** [comment]
The restriction on setting the control column as an additional constraints column has been put in place for v2.3.3
