### ISSUE TITLE
Can't partition by timestamp

### ISSUE THREAD

**Issue by goldjee** [keithf4/pg_partman#101]
I'm trying to partition an existing large table by date. Here's the schema:
```
CREATE TABLE data."dataMatch"
(
  "matchID" bigint NOT NULL,
  "matchSeqNum" bigint NOT NULL,
  "timeStart" timestamp with time zone NOT NULL,
  ...
  CONSTRAINT "dataMatch_pkey" PRIMARY KEY ("matchID")
)
WITH (
  OIDS=FALSE,
  autovacuum_enabled=true
);
CREATE INDEX "dataMatch_idx"
  ON data."dataMatch"
  USING btree
  ("matchID" DESC, "matchSeqNum" DESC NULLS LAST, "timeStart" DESC NULLS LAST);
ALTER TABLE data."dataMatch" CLUSTER ON "dataMatch_idx";
```

There are 17 272 731 rows in this table as of now.

So, to start partitioning by dates, I call `create_parent `function as follows:
```
select partman.create_parent(p_parent_table := 'data.dataMatch',
p_control := 'timeStart',
p_type := 'time',
p_interval := 'daily',
p_start_partition := '2016-02-20',
p_constraint_cols := '{"timeStart"}',
p_use_run_maintenance := true,
p_debug := true);
```
Note that I'm planning to query the table mostly with conditions on "timeStart", so I need constraint exclusion for that field to optimize plans.

'2016-02-20' is the minimum date in my set, so I prefer to start with it.

Then, as usual, I run
`select partman.partition_data_time('data.dataMatch');`
Just like in the issue #100 I get that not all the data has been moved to partitions
![image](https://cloud.githubusercontent.com/assets/7242338/13903859/a44b7e1a-ee9c-11e5-81cc-3c16b0d79f2f.png)
and run
`select partman.run_maintenance(p_parent_table := 'data.dataMatch', p_debug := true);`
to do all the job for me. But it fails at applying constraints with message:
> NOTICE:  run_maint: parent_table: data.dataMatch, v_last_partition: dataMatch_p2016_03_24
> 
> NOTICE:  run_maint: v_current_partition_timestamp: 2016-02-20 00:00:00, v_max_time_parent: 2016-03-05 11:20:13
> 
> NOTICE:  run_maint before loop: current_partition_timestamp: 2016-03-05 00:00:00, v_premade_count: 19, v_sub_timestamp_min: <NULL>, v_sub_timestamp_max: <NULL>
> 
> NOTICE:  apply_constraint: v_parent_tablename: dataMatch , v_partition_suffix: 2016_02_18
> CONTEXT:  SQL statement "SELECT partman.apply_constraints(p_parent_table := v_row.parent_table, p_job_id := v_job_id, p_debug := p_debug)"
> PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 304 at PERFORM
> 
> NOTICE:  Target child table (dataMatch_p2016_02_18) does not exist. Skipping constraint creation.
> CONTEXT:  SQL statement "SELECT partman.apply_constraints(p_parent_table := v_row.parent_table, p_job_id := v_job_id, p_debug := p_debug)"
> PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 304 at PERFORM
> 
> Time: 69.059s
> 
> Affected rows: 1

Note that I've set constraint column "timeStart" which is NOT NULL.

**Comment by keithf4** [comment]
Please read the documentation on the `partition_data_time()` function. It only moves `p_batch_interval` for `p_batch_count` batches. Since you gave it no parameters, it only moved data for a single child table and stopped. As the docs say, if you want to partition a lot of data, it is recommended you use the included python function to commit the data in smaller batches.

**Comment by keithf4** [comment]
Also, constraint exclusion will automatically work for the control column, so you don't need to set that. The `p_constraint_cols` parameter is for if you need constraint exclusion on columns other than the control column. I've explained this more here  https://www.keithf4.com/managing-constraint-exclusion-in-table-partitioning/

**Comment by goldjee** [comment]
Thank you very much for detailed answer. I have reconfigured partitioning by time as follows:
```
select partman.create_parent(p_parent_table := 'data.dataMatch',
p_control := 'timeStart',
p_type := 'time',
p_interval := 'daily',
p_use_run_maintenance := true,
p_debug := true);
```
And partitioned the table using `partition_data.py`. Everything seems ok (the data has been moved correctly, partitions set). Except when I call `run_maintenance()` for the parent table I get following message:
> NOTICE:  run_maint: parent_table: data.dataMatch, v_last_partition: dataMatch_p2016_03_24
> 
> NOTICE:  run_maint: v_current_partition_timestamp: 2016-03-05 00:00:00, v_max_time_parent: <NULL>
> 
> NOTICE:  run_maint before loop: current_partition_timestamp: 2016-03-05 00:00:00, v_premade_count: 19, v_sub_timestamp_min: <NULL>, v_sub_timestamp_max: <NULL>
> 
> NOTICE:  Given parent table (data.dataMatch) not set up for constraint management (constraint_cols is NULL)
> CONTEXT:  SQL statement "SELECT partman.apply_constraints(p_parent_table := v_row.parent_table, p_job_id := v_job_id, p_debug := p_debug)"
> PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 304 at PERFORM
It seemed like an error for me. That was the reason why i had provided `p_constraint_cols` parameter to `create_parent()` earlier. Now I understand that it is nothing more than an informational message.
