### ISSUE TITLE
Is it possible to partition by alphabetical for the control column?

### ISSUE THREAD

**Issue by cdhouch** [keithf4/pg_partman#102]
We have multi TB tables containing medical codes that all start with an alphabetical character.  We have done partitioning by hand on these, but are switching everything over to pg_partman for consistency and ease of use.  Is it possible currently to somehow partition over alpha characters or could this feature be added in the future?

**Comment by keithf4** [comment]
The beginning of the README contains some info about this. At this time, pg_partman does not support partitioning outside time/id based methods. Doing so would add more complexity than I would like at this time. There is another extension linked to in the README that can do this (range_partitioning).

https://github.com/keithf4/pg_partman#pg-partition-manager

I understand you'd like all partitioning managed by a single extension. If you don't have very high transaction rates, range_partitioning may work for you in all cases and you can then use that instead. But if you need some better performance with time/serial partitioning, it may be better to use different extensions for each.

**Comment by cdhouch** [comment]
Thanks for the info Keith.  I apologize for missing this in the README.
