### ISSUE TITLE
After update from v2.2.3 to v2.3.1, pg_dump and reload of dump on new cluster fails 

### ISSUE THREAD

**Issue by smkkristensen** [keithf4/pg_partman#104]
Hi Keith,
Thanks for a great extension ;o)
I have a DB which were installed with pg_partman v.2.2.3 and subsequently updated to v2.3.1. Then I had to move it to another DB cluster and dumped the db with pg_dump, installed the relevant extensions on the new DB cluster, including pg_artman v.2.3.1 and loaded the dump file. However the load failed whith an error messgage:

psql:booklog.sql:49976335: ERROR:  null value in column "infinite_time_partitions" violates not-null constraint
DETAIL:  Failing row contains (booklog.gt_double_value, mts, id, 2500000000, null, 4, 4, 30, f, t, null, null, t, t, null, t, t, f, f, f).
CONTEXT:  COPY part_config, line 1: "booklog.gt_double_value	mts	id	2500000000	\N	4	4	30	f	t\N	\N	t	t	\N	t	t	f	f	f"

After some investigation I found out that the problem lies in the position of the infinite_time_partitions field in the part_config table. In the dumped database, the field is in the bottom of the table because the updates/pg_partman--2.2.3--2.3.0.sql adds this field. However, on the new database cluster where I installed pg_partman v2.3.1, the inifnite_time_partitions field is not in the same position in part_config as can be sen in pg_partman--2.3.1.sql which defines the part_config table. As a consequence, the reload of the part_config table with the COPY command fails.

The same situation is the case for the part_config_sub table.

In the specific case, I solved the issue by manually moving the infinite_time_partitions field to the end of the declaration of part_config in the installed extension file pg_partman--2.3.1.sql on the new database cluster before loading the dump file.

I suggest that all new fields in the partman control tables are always added at the end of the table definitions. Then migration of a partitioned databse to another database cluster will work seamlessly, irrespective of the sequence of updates performed on the pg_partman extension on the two database clusters.

Best regards,
Søren

**Comment by dturon** [comment]
Hi, you can try dump again if its posible with --column-inserts and then restore, is slower but columns can have different position:)

**Comment by keithf4** [comment]
Appologies on that. I try to keep the default order of the columns in order of general importance to the extension. The order of the table columns is also used throughout other functions just to keep some sanity for myself when I add new features.
I'd recommend going with @dturon 's method to ensure column ordering during inserts after an upgrade.

**Comment by keithf4** [comment]
I've added a note in the upgrade section of the README.md concerning this issue. Thanks for bringing it to my attention!

**Comment by smkkristensen** [comment]
Hi Keith and DTuron,

Thanks for your fast reply. The idea of using pg_dump --with-column-inserts is good for smaller datasets, however, I have a partitioned table with +1e9 records and it might pose a speed issue.

Thanks again for your help. I'll close the issue.

Best regards,
Søren

**Comment by keithf4** [comment]
If you've installed pg_partman in its own schema, then you can just exclude that from the pg_dump with -N. If not, can exclude its config tables with -T. I tested and this does work.
You can then dump the config tables themselves with -n or -t options to pg_dump.

**Comment by smkkristensen** [comment]
That was a neat solution. Thanks.

**Comment by bsebi** [comment]
Question related to this. Why when I try to dump the table partman.part_config I dont get the table creation instructions? When I dont use -n or -t switches on pg_dump I get the partman.part_config created on the new database.

**Comment by keithf4** [comment]
The creation of the part_config table is controlled by the CREATE EXTENSION command.

**Comment by bsebi** [comment]
CREATE EXTENSION is called when pg_dump is used without switches. I would like to dump partman schema with --column-inserts and the rest without column inserts. How can I dump just the partman schema(-n) in such a way that CREATE EXTENSION is called.

**Comment by keithf4** [comment]
Unfortunately there doesn't seem to be a way to dump the table schema of an extension, only its data. And the data is only dumped if the pg_catalog.pg_extension_config_dump() option is turned on for those tables (which it is for partman). So the only thing you can really do is dump the data out of the partman schema (by passing -n to pg_dump), but you'll have to run the CREATE EXTENSION command manually yourself if you're not dumping out the whole database.
