### ISSUE TITLE
PGSQL 9.5 UPSERT support on partitioned tables.

### ISSUE THREAD

**Issue by MikaelUlvesjo** [keithf4/pg_partman#105]
In pgsql a new function is added to INSERT called "UPSERT" in the form of "ON CONFLICT".

I would like to use that feature on a partitioned table but since the trigger is not passing the ON CONFLICT part of the insert query it is ignored.

e.g:
When running the following queries on a table that is not partitioned both run fine and we will have 3 rows in the table, but if the table is partitioned the second query will fail and we will only have 2 rows in the table.

INSERT INTO part_table (id,val) VALUES 
(1,'test1'), (2,'test2')  ON CONFLICT (id) DO NOTHING

INSERT INTO part_table (id,val) VALUES 
(2,'test2'), (3,'test3')  ON CONFLICT (id) DO NOTHING

When running the following queries on a table that is not partitioned both run fine and we will have 3 rows in the table where row with id 2 will have the val = "test22", but if the table is partitioned the second query will fail and we will only have 2 rows in the table id=3 is missing and row with id = 2 will have val = "test2".

INSERT INTO part_table (id,val) VALUES 
(1,'test1'), (2,'test2')  ON CONFLICT (id) DO UPDATE SET val=EXCLUDED.val

INSERT INTO part_table (id,val) VALUES 
(2,'test22'), (3,'test3')  ON CONFLICT (id) DO UPDATE SET val=EXCLUDED.val

**Comment by keithf4** [comment]
I'll see if I can add this in. Haven't done much testing against 9.5 features yet.
Keep in mind that any updates that would move a column from one child table to another (due to partitioning constraints) are not supported by pg_partman

**Comment by MikaelUlvesjo** [comment]
I'm my case it would be enough to define it one time and the have it used in all insert queries.
I have a data source that will give me duplicate rows and if I could define "ON CONFLICT (id) DO NOTHING" once for the partitioning of a table it would solve my problem.
I have tried to manually update the trigger function to include the ON CONFLICT statement and it does work until a new version of the trigger is generated.

**Comment by keithf4** [comment]
The issue I'm seeing now with this is how to managed the CONFLICT resolution. I have no way to predict how someone would want to resolve the issue and the possible resolutions are quite large. In your case DO NOTHING works fine. But that may not be what someone else needs to have done. Also there has to be a way to define which columns the CONFLICT should be handled for. There could be other unique constraints besides just a primary key.

I don't think there's going to be a quick resolution to this for right now unfortunately.

**Comment by MikaelUlvesjo** [comment]
If you allow users to define the "ON CONFLICT xxxx"  part for the trigger and document and/or warn that any update that will result in that the inserted row will have a value that do not belong in the partition will result in corrupt data and is not supported, so an SET on the field used for the partitionering is not supported in the same way that a UPDATE query that will change the value that the partitioning is created on.
It can be solved in creating an on BEFORE UPDATE trigger that checks the value the partition is created on and RAISE EXCEPTION if the value have changed to something that do not belong in this partition.

**Comment by keithf4** [comment]
This is adding far more complexity to the extension than I want to at this time. I will keep this open as a feature request to revisit when I have some time. If you want to give an attempt at a patch to incorporate this, I'd be happy to review it.
Also, I don't see a need for the BEFORE trigger you mentioned since the constraint will cause an error if data tries to be moved to another child table that it's not allowed to be in. Seems to be unnecessary overhead.

**Comment by MikaelUlvesjo** [comment]
Could you point me to the source where the trigger is created and the properties of the partition is set so I can use a property to store the "ON CONFLICT" sql as a property to be used by the create trigger function?

**Comment by keithf4** [comment]
Trigger functions are created with
https://github.com/keithf4/pg_partman/blob/master/sql/functions/create_function_id.sql
or
https://github.com/keithf4/pg_partman/blob/master/sql/functions/create_function_time.sql

Most partition properties are set on the parent and I do catalog lookups from there. For this, you'll likely have to use the `part_config` table to store this. There's also the `part_config_sub` table for sub-partitioning. 

Highly recommend reading over the docs closely and looking at how previous updates have been done.

**Comment by keithf4** [comment]
This has been added in version 2.5.0
