### ISSUE TITLE
Excluding child tables from retention

### ISSUE THREAD

**Issue by dodga** [keithf4/pg_partman#106]
Hi!

I was wondering if it is possible to exclude specific child tables from the retention policy of their parent.
More specifically, I want to partition by year and month (and maybe by day later on).
For the current year, the retention policy should be executed normally (e.g., keep the last month, archive any earlier months).
But I also want to keep certain tables (e.g., from three years ago) that should neither be archived (since I probably already have them in cold storage) nor deleted due to the retention policy.
I want the older tables as part of the partition, as I want that data included in queries to the parent table.
Is this possible?
I looked into the docs and did not find anything immediately apparent.
I was thinking about a manual insert into part_config or part_config_sub but I am wary about any implications...

Best regards, Alex

**Comment by keithf4** [comment]
There is nothing like this built in and not sure I would add anything like this. Would really make things complicated for a rarely used feature.
I'd recommend manually removing child partitions via your own methods. pg_partman currently does not go back and re-add old partitions unless you re-partition data that gets thrown into the parent. The suffixes all have a predictable naming pattern that is easily scripted in most languages. I lay it out in more detail in the migration doc.
https://github.com/keithf4/pg_partman/blob/master/doc/migration.md#step-3

**Comment by dodga** [comment]
I just renamed a child table and it seems to work as I intended.
So to be clear, I could add data to the hierarchy, organize it via partition_data, and then rename the child tables?
What happens when I insert/partition the data and run_maintenance is called (e.g., via cron or BGW)?

**Comment by keithf4** [comment]
Not sure if renaming will work in the long run. If you're changing the suffix value on the child table then you could actually break pg_partman's management since it uses the `show_partitions()` function internally to list child tables and if there's a bad suffix on a child table it could throw off the results of that function.

My suggestion was to not use pg_partman's retention system at all and remove the child tables you no longer need yourself.

Removing old child tables should not affect the maintenance of creating new tables as long as the child tables you're removing aren't in the range of the `optimize_trigger` configuration value.

Inserting data and/or partitioning data out doesn't affect the maintenance runs.

**Comment by dodga** [comment]
Oh okay, i.e., I leave retention at NULL and do maintenance manually (e.g., my moving tables myself to another schema and/or drop them)?
I guess I still need to use undo_partition either in PostgreSQL directly or via the Python script, no?
Is there a way to undo the partition (or a part of it, e.g., some child tables) without copying or moving any data?

**Comment by keithf4** [comment]
undo_partition() is solely for moving the data back into the parent. 
The most important thing you need to do to remove the child table from the partition set is uninherit (ALTER TABLE mychild NO INHERIT myparent;). Whether you move it to a different schema or drop it after that is up to you.

**Comment by dodga** [comment]
So I just use pg_partman normally without the retention, remove no longer needed tables via uninherit, and then maybe drop them.
Is there anything else I need to do w.r.t. to partman's configuration tables?

**Comment by keithf4** [comment]
That sounds like it should work. Nothing else I can think of needs to be done. If you have any issues with doing this, please let me know. No one I know has done anything like this (just removing specific old child tables and leaving others there), nor have I designed the extension with this in mind, so I can't honestly guarantee it will work perfectly. But I can't think of any reason right now why it wouldn't work.

**Comment by keithf4** [comment]
I'd recommend not dropping your tables (or at least not dropping them without dumping them out as a backup first) until you're sure this works ok.

**Comment by dodga** [comment]
Okay, I'll try that and let you know how it works out.
Thanks a lot!

**Comment by keithf4** [comment]
One thing you can check is, after uninheriting the old tables, run

`SELECT * FROM partman.show_partitions('myparent', 'DESC');` 

And see if the child tables come back in the expected order. If they do, that's one sanity check passed.
