### ISSUE TITLE
Performance in big databases could be better

### ISSUE THREAD

**Issue by Crack** [keithf4/pg_partman#107]
Slow performance in overcrowded database returns ;)
1000 namespaces, 97000 tables.

### 1. `show_partitions` is slow

It checks whether parent schema and table exist by issuing a query:
```sql
SELECT schemaname, tablename INTO v_parent_schema, v_parent_tablename
FROM pg_catalog.pg_tables
WHERE schemaname = split_part(p_parent_table, '.', 1)
AND tablename = split_part(p_parent_table, '.', 2);
```
which works along the following plan:

    Nested Loop  (cost=0.00..30373.78 rows=2 width=128)
      Join Filter: (c.relnamespace = n.oid)
      ->  Seq Scan on pg_class c  (cost=0.00..30306.15 rows=491 width=72)
            Filter: ((relkind = 'r'::"char") AND ((relname)::text = 'alarmreportentry'::text))
      ->  Materialize  (cost=0.00..30.82 rows=5 width=68)
            ->  Seq Scan on pg_namespace n  (cost=0.00..30.80 rows=5 width=68)
                  Filter: ((nspname)::text = 'activeview_3783'::text)

My pg_class has 746182 and this takes 110-330 ms, depending on db load and caches. It can be improved by casting `split_part` result to `name`:
```sql
SELECT schemaname, tablename
FROM pg_catalog.pg_tables
WHERE schemaname = split_part('activeview_3783.alarmreportentry', '.', 1)::name
AND tablename = split_part('activeview_3783.alarmreportentry', '.', 2)::name;
```
This works fast (10-40ms), using indexes on pg_class and pg_namespace:

    Nested Loop  (cost=0.70..16.76 rows=1 width=128)
      ->  Index Scan using pg_namespace_nspname_index on pg_namespace n  (cost=0.28..8.29 rows=1 width=68)
            Index Cond: (nspname = 'activeview_3783'::name)
      ->  Index Scan using pg_class_relname_nsp_index on pg_class c  (cost=0.42..8.45 rows=1 width=72)
            Index Cond: ((relname = 'alarmreportentry'::name) AND (relnamespace = n.oid))
            Filter: (relkind = 'r'::"char")

Other functions that split p_parent_table into schema and table name have the same issue.

### 2. run_maintenance does some unnecessary work
It runs check_subpart_sameconfig on all configured subpartitions. When `p_parent_table` is given shouldn't it look only for subpartitions of this one parent? I found it when looking at code, but have no subpartitions myself, so I don't know whether this overhead is significant..

**Comment by keithf4** [comment]
Thanks for the optimization tips! I'll work these in for the next patch.

For issue 1, it had actually been even worse before (see https://github.com/keithf4/pg_partman/issues/87).

**Comment by Crack** [comment]
Next one: in triggers for data when partitions don't match. Generated triggers check whether partition table exists:
```sql
            ELSE
                v_partition_name := partman.check_name_length('gpsinfo', to_char(v_partition_timestamp, 'YYYY_MM'), TRUE);
                SELECT count(*) INTO v_count FROM pg_catalog.pg_tables WHERE schemaname = 'activeview_75' AND tablename = v_partition_name;
                IF v_count > 0 THEN 
                    EXECUTE format('INSERT INTO %I.%I VALUES($1.*)', 'activeview_75', v_partition_name) USING NEW;
                ELSE
                    RETURN NEW;
                END IF;
            END IF;
```

I don't know whether PostgreSQL allows me to access query plan for queries in functions, but I have a simple test case that proves that this is slow:

A. Original query, takes ~220ms
```sql
DO $$
DECLARE
  v_table text := 'gpsinfo_p2016_06';
  v_cnt int;
BEGIN
  select count(*) into v_cnt from pg_tables where schemaname = 'activeview_75' and tablename = v_table;
  raise notice '%', v_cnt;
END$$
```
B. With explicit cast to `name`, takes 20-60ms:
```sql
DO $$
DECLARE
  v_table text := 'gpsinfo_p2016_06';
  v_cnt int;
BEGIN
  select count(*) into v_cnt from pg_tables where schemaname = 'activeview_75' and tablename = v_table::name;
  raise notice '%', v_cnt;
END$$
```

**Comment by keithf4** [comment]
I've pushed a branch for 2.3.3 up for evaluation that includes fixes for everything you've mentioned here. I adjusted run maintenance so it only checks sub-partition configs for tables being considered for maintenance that run. Good catch on that!

https://github.com/keithf4/pg_partman/tree/v2.3.3dev

I'm running it myself on some systems over the weekend and if there's no issues I'll be releasing it as a new version sometime next week. Figured I'd share it so you can evaluate it as well.

**Comment by Crack** [comment]
Nice :)

Right now I don't have a proper test environment, so I did a quick code review instead, learning a bit more about how partman works in the process. Just please note that I don't know PL/pgSQL well, I'm much more familiar with PL/SQL.

`check_parent` - does it need to query pg_tables at all? It could just split parent_table into schema and table and query directly? If it gets a nonexistent table it will fail with an exception anyway.

`check_subpart_sameconfig` - missing casts after call to split_part

There are some queries to pg_catalog tables where you didn't cast to `name` - shouldn't they be treated the same as pg_tables? Columns from catalog (namely - relname, nspname, attname) are also of type `name` (eq. `drop_constrainsts`, `drop_partition_*`).

BTW, I found an even better way to check whether table exists, but it's less portable (9.4+) and less readable than asking pg_tables: a call to `to_regclass`, followed by subsequent verification of returned oid type via `pg_table_is_visible`. Test on real data show a difference of... ~0,0004s, so just wanted to share something interesting.

**Comment by keithf4** [comment]
Guess that could be removed from `check_parent`. One of the main reasons I had been doing that was to provide clearer error messages, but looks like I didn't do that for this one anyway. I'll see about adding that fix and reviewing the other catalog calls in a future release.

**Comment by keithf4** [comment]
Released v2.3.3. Let me know if that helps with your performance issues at all. Will continue looking into these further for next release.

**Comment by Crack** [comment]
A quick test with running `run_maintenance(table, false, false, false)` on 10 tables, with all partitions already premade (so I measure primarily the constant part of maintenance):
* 2.3.2: 2.0s-2.1s
* 2.3.3: 0.24s-0.25s

With a difference of about 1.75s / 10 tables on a no-op run I can cut down my maintenance by 20 minutes, looks good.

**Comment by keithf4** [comment]
Awesome! Thanks for the testing stats!

**Comment by keithf4** [comment]
Since I was modifying many of the functions anyway to handle another issue, I got a lot more of these optimizations in place for v2.3.4. May still be missing in a few other places, but a large majority should be handled now and hopefully help performance. Thanks again!
