### ISSUE TITLE
[question] installation on windows

### ISSUE THREAD

**Issue by ngortheone** [keithf4/pg_partman#111]
Hi,

Is there a way to get pg_partman installed and working on windows?  
I have Postgres 9.4(binary installation) running on windows 2012 R2.
Unfortunately building postgres from source is not an option for me.

**Comment by keithf4** [comment]
Sorry, I don't have any installation methods that don't at least require `make` to create the plpgsql file. If you have access to any system where you can at least run that, you can copy the resulting `.sql` file and the `.control` file to the `share\extensions` folder of your postgresql installation. The C library stuff is only needed for the internal maintenance scheduling and you can skip that by passing `NO_BGW=1` to `make`.

If you want the scheduler, you'll have to find a way to compile it. The PostgreSQL wiki has some tips for doing that with contrib modules which should be similar to extensions.
https://wiki.postgresql.org/wiki/Building_and_Installing_PostgreSQL_Extension_Modules

**Comment by alvar-freude** [comment]
As workaround you may use PostgreSQL on Cygwin. This should work.
Nevertheless: I don't recommend running PostgreSQL on Windows – development installations may be an exception.

**Comment by ngortheone** [comment]
@alvar-freude could you please share your concerns about Postgres on Windows? 
I am using Postgres  both on Windows and Linux boxes for quite a long time (for 3 years already). There are no significant stability or performance issues that I have noticed. (At least last versions 9.3 and 9.4)

@keithf4 thanks for advice. I do not need scheduler so I will try to build SQL file on a linux box.

**Comment by Crack** [comment]
If you have at least some bash (from MSYS2, Git Bash, cygwin etc.) then you can use my make.sh script. It doesn't require make or a PostgreSQL installation.
```bash
#!/bin/bash
EXTENSION=pg_partman
VERSION=$(grep default_version $EXTENSION.control | \
          sed -e "s/default_version[[:space:]]*=[[:space:]]*'\([^']*\)'/\1/")

cat sql/types/*.sql > "${EXTENSION}--${VERSION}.sql"
cat sql/tables/*.sql >> "${EXTENSION}--${VERSION}.sql"
cat sql/functions/*.sql >> "${EXTENSION}--${VERSION}.sql"
```

**Comment by ngortheone** [comment]
@Crack thanks for the advice. I am closing this issue

**Comment by timbq** [comment]
Handy shell script, but for "modern" versions of partman, it is missing an additional line:
`cat sql/procedures/*.sql >> "${EXTENSION}--${VERSION}.sql"`
