### ISSUE TITLE
Multi-Table Partitions

### ISSUE THREAD

**Issue by RadioPlanner13** [keithf4/pg_partman#112]
I am not clear if pg_partman manages multiple linked tables.  The documentation only ever shows a single table.

**Updated numerous time during discussion**

I am not experienced at SQL, but understand relational databases well.  (Worked with them a good bit about 25 years ago!) . I have a "Master" table which cross references to 3 other Related tables which receive all the the incoming data for the database when it is being updated.  
The whole database is 100% created by a programme (no manual entries ever) as the data is derived from millions of lines of text to re-create Major events from thousands of minor events.  Thus I can re-use the same Key sequence for multiple things, rather than having multiple keys in the related tables.
The master has 32 columns, with Eight of these being Keys to other tables (Some of the tables also refer to sub-Related but these are more reference data, such as Number-->Day of Week as String etc.).

There is a single database with 4 tables of concern that contain the vast amount of data and then 4 more which hardly get added to at all (maybe 12 row updates per annum) - they don't need to be part of the partition management (suggestions about how to treat them would also be appreciated).

This is an outline of the master table:-
```
--First a SEQUENCE to keep track of insertions
CREATE SEQUENCE SSI_Seq;
--Now the Master Table
CREATE TABLE Master
(--Some fields
--Links shown for clarity
StartTime TIME,
InvolvedNumber_Key INTEGER,					--Related.ssi_Key
DestNum_Key INTEGER,						--Related.SSI_Key
OtherNumber INTEGER DEFAULT NULL,	               --Related.SSI_Key

---More Fields
Auto_key SERIAL									--Automatic Key For Indexing
)
WITH (
  OIDS=FALSE
 );
```
One of the Related Tables, where there can be one or many entries linking back to the Main Table
```
CREATE TABLE Related(--Some fields
SSI_Key  INTEGER,					
--Program inserts SSI_Key as generated by SSI_Seq (multiple rows can have the same value in 
--this table). This Key is used to keep track of relationships between Master and Related.  
--The value inserted into the Master table is unique to that table.
Auto_key SERIAL						--Automatic Key For Indexing
)
WITH (
  OIDS=FALSE
 );
```

Another RelatedTable, which can hold one or many events for Related
```
CREATE TABLE Events
(--Some fields
RelatedKey INTEGER,	                                                        --Refers to Related
AutoKey					
Auto_key SERIAL									--Automatic Key For Indexing
)
WITH (
  OIDS=FALSE
 );

```
There is another Related table, which I have omitted for convenience, which does not have a sub-Related, which would be treated the same way as the first Related.

The Partition would be based upon Main.StartTime with time partitioning (Monthly)
What I would like to know is how does pg_partman "know" the Related tables are connected to the main table (I have tried for 3 days to no avail to get the links to work using SQL but cannot get PG to cooperate)

I have read your Article #53 but did not fully understand all of the nuances.

Many thanks in advance.

**Comment by keithf4** [comment]
I'm really not sure I understand your issue. The parent table can only have partitioned child tables  that are directly related to the partitioning set.
The other issue you liked to basically says you can have foreign keys going from the partition set to other tables, but you cannot have foreign keys from other tables pointing back to the parent table of the partition set.

**Comment by RadioPlanner13** [comment]
I have updated the original question to make it clearer.  I would like to know how to connect the parent table to the database.  This is probably a PG issue, but it could also involve pg_partman in various ways.  I am not a DB person but rather a programmer who rashly stated that I could master databases sufficiently to complete this job, but 6 months of data has created a 39GB database, which needs to be partitioned.  I had originally thought of filling a database, renaming it after a period and then having a view into the combined databases, but that is a bit unwieldy, if I could get this working.

**Comment by keithf4** [comment]
Just to clarify, when you say `I have a "Master" database which cross references to 3 other child databases`, do you mean tables? That may be part of my confusion.

**Comment by RadioPlanner13** [comment]
Sorry for causing so much confusion - I sometimes suffer from a sort of lexdixia(!!) and mix words up. I have updated my original information and my comment.
There is a single database with 4 tables of concern that contain the vast amount of data and then 4 more which hardly get added to at all (maybe 12 updates per annum) - they don't need to be part of the partition management.

**Comment by keithf4** [comment]
If the table has to have a foreign key relationship TO it, then it cannot be partitioned with pg_partman and maintain data integrity. If it just needs to have foreign keys from it to other tables, then pg_partman can handle that and will automatically add any foreign keys created on the parent to any child tables. If there are no foreign keys, then you have nothing to worry about.

If you create the sequence as a default value on the parent table, then that default will be inherited to all child tables with that same sequence.

If you're just doing joins between all these tables via queries, that shouldn't be a problem and hopefully partitioning would help with that. If the older data is static, look into the additional constraints option to allow constraint exclusion to be more useful as well.

Things are a little clearer now, but still not 100% sure I understand what all you're looking for. Hope that helps.

**Comment by RadioPlanner13** [comment]
While you were responding, I was editing my original to make it clearer.
I have added the following comment into the Child table:-
_Program inserts SSI_Key as generated by SSI_Seq (multiple rows can have the same value in this table). This Key is used to keep track of relationships between Master and Child.  The value inserted into the Master table is unique to that table._


I have also added the following to my original statement:-
_There is a single database with 4 tables of concern that contain the vast amount of data and then 4 more which hardly get added to at all (maybe 12 updates per annum) - they don't need to be part of the partition management (suggestions about how to treat them would also be appreciated)._

Many thanks for your quick responses...

**Comment by keithf4** [comment]
You mention keeping track of a relationship between data in the master/parent and child. pg_partman assumes no data exists in the master table. The trigger redirects all incoming data to existing child tables. If a matching child table is not found, then the data goes to the parent and there is a function `check_parent()` to monitor for this. If data is not moved out of the parent, then this may cause `run_maintenance()` to not work properly in keeping up with new child table creation.

If you need data to exist in the master table for your architecture, then pg_partman will not work for you. However, I'm not sure if you're aware that you can just direct all queries to the parent and it will automatically see all data across all children.

**Comment by RadioPlanner13** [comment]
I understand what you mean about the master having no data itself and that it redirects to the appropriate named table for the (month).
 
I now suspect that what I have in mind will not happen.   Say I have partitioned master for March 2016 and I insert a record, which will be redirected to the appropriate partition table (don't have database actual names of the top of my head, but say it is `master_032016`).  What I would like to achieve is that during that entry of data by the associated programme, fields in the master would be filled with `InvolvedNumber_Key, DestNum_Key and OtherNumber`  and that a table called `child_032016` would exist to fill with appropriate data for the `child_032016.ssi_Key `in the table.  These entries would be reflected back when the database is being read.

As I said somewhere along the way, there is a single database with 4 tables of concern that contain the vast amount of data (all of which I would like to partition) and then 4 more tables which hardly get added to at all (maybe 12 updates per annum across all 4 of these non-partitioned tables) - they don't need to be part of the partition management.  
While the master table is about 30 columns wide, the others 3 tables of concern are only 5 to 10 columns wide BUT... there are on average about 10 entries in each for each row in the master (varying from 1 row to 75 or so rows). There is a single sequence (called `SSI_Seq` ) to keep the interconnection between them correct (as this is more efficient than using 3 different sequences).   I would like to use the creation of the set of Master table partitions to create the Child partition set of appropriately named tables so that data flows into and comes back as if it is a single database.  The flow of data into the tables would be controlled by a single time-based partition based upon `master.StartTime` field.

This assumption is based upon the thinking behind a relational database - i.e. that a single row in the Master Table links to one or more children table rows through the use of an Index. I thought that this would be a feature of the partitioning system and all I need is an indication of how to achieve this end in practical terms. 

Hopefully this makes my requirements clearer, because reading back I should have made a statement something like this at the start.  I suspect that it is not possible.

**Comment by keithf4** [comment]
This all comes down to what you mean by "related". Your terminology of using an index to relate/link  tables is unclear. If by an index, you mean an actual foreign key relationship (which requires an index to function efficiently), then as I've said above, it all depends on the direction of the FK relation. If there are foreign keys going to the partitioned table, it will not work due to the nature of how table inheritance works (this is explained in my blog post). If the relation is a foreign key going from the partitioned table to another table (that is not partitioned), things should work fine.

If the "link" between related tables is just via joins in queries, things should be fine.

**Comment by RadioPlanner13** [comment]
As I have said, I am not a database person, so I have difficulty find exprsessions that match those of the DB community.

Here is a simple query that returns fields that are connected through the independantly created Sequence (CREATE SEQUENCE SSI_Seq;)
```
SELECT 
  master.any_field, 
  master.starttime, 
  related.some_field
FROM 
  public.master, 
  public.related
WHERE  
   master.OtherNumber = related.SSI_Key
```
My code when filling a single row in the master works in the following manner:-
It fills fields in a row into the Master table and when it comes to the `Master.InvolvedNumber_Key`  it just inserts number generated by the Sequence `SSI_Seq` into that colum and then uses that same sequence number when inserting associated rows into the "Related" table, filling the `Related.SSI_Key` field with the number previously created by the SSI_Seq.  It then gets the sequence to generate a number for the `Master.DestNum_Key` again filling it into the relevant column in the Master table and then use that single number in the the multiple rows associated with that Master Row in the generated by the `SSI_Seq` sequence in the `Related.SSI_Key` column.  Finally it uses another number from the `SSI_Seq` to insert the `Master.OtherNumber` in a similar manner.  Thus, each row in the Master table has 3 unique values derived from the Sequence `SSI_Seq` across the columns - each providing a 'link relationship' to the Related table.  
When I look at the Related table I will see between 1 and about 20 entries each with the same `SSI_Seq` - generated number in that column.  Some of the entrie sin this table will be related back to `Master.InvolvedNumber_Key`, others to `Master.DestNum_Key`, and more to `Master.OtherNumber`.

Hope this makes the connection (not sure of the DB term) between tables clearer.


What I would propose to do (if this is feasible) is run Create_parent for the Master Table, using the master.starttime with time partitioning (Monthly).  I would then have to retro-fit that same field to each of the tables that have a relationship to the master so that they can be time partitioned using this new field.  Not very efficient, but it is the only way I can see to get it working.

My fuindamental issue is that it takes about 270 seconds to count the records in some of the related tables, even with an auto_key - nothing fancy just a simple `select count(*) from master;`.

**Comment by keithf4** [comment]
I'm not sure how else to explain this. If you must ensure data is consistent between different tables, meaning that a specific column's values must also exist in another table, then you must use a foreign key. It sounds like that may be what you're setting up here, but since you never use the term foreign key (which is part of the SQL standard and clearly defines how specific relations work together) I'm not sure if that's what you actually need. I highly recommend reading up on foreign keys to see if that's what you're trying to do here. If so, then I've explained the limitations with foreign keys and how I've implemented partitioning with pg_partman. 

If you do not need the data constraints that foreign keys provide, then I don't see there being any problem with using pg_partman for what you're doing.

**Comment by RadioPlanner13** [comment]
Ah Sorry - to me that name **FOREIGN key** is such a bad & mad name to put on a key that is internal to the database that I don't think of using it.  I have been using the term **key** but not **FOREIGN key**, because to me they are both the same thing.  Apologies about that.

That is exactly what I am using but to me it is just a key used by both tables, not a Foreign key to both tables.  HOWEVER I use it in a way that IS allowed but does not have references (something like` product_no integer REFERENCES products,`) built in - because PG does not seem ot allow me to do so (it complains about missing values in one column, even though this is not a requirement in the SQL standard).  
The person in our organisation who uses Business Objects has set up some pretty complex reports based upon multiple cross-relationships between the 4 tables in question and it recognises the keys fine when we build them graphically in the reporting engine.  This is why in an earlier post I mentioned that this is probably in the cross-over between pg_partman and PostgreSQL. (In my original post I said _**I have tried for 3 days to no avail to get the links to work using SQL but cannot get PG to cooperate**_ - the word **_links_** should now the replaced by **_foreign key_**)

I don't use these references in the table definitions, but would like to know if they were used, does pg_partman recognise and use them - or should I abandon the partitioning idea altogether and use a different (slower) approach?

**Comment by keithf4** [comment]
Since partitioning is not yet built into postgres, other systems have to be used together to make it work. There are several methods for doing this, but I use the method outlined in the documentation (http://www.postgresql.org/docs/9.5/static/ddl-partitioning.html - inheritance, triggers & constraints) with some tweaks to allow more features. I recommend reading up on those things, especially inheritance, since that, combined with everything else I've explained, answers your questions.

**Comment by RadioPlanner13** [comment]
Many thanks for all your patience with my questions.  Now with what you have explained to me I understand my way forward (not to use partition management at this time as PG does not yet have the functionality I need to be certain of getting exactly what I want.

Thanks again.
