### ISSUE TITLE
pg_partman partitions of manual partitions

### ISSUE THREAD

**Issue by sebroy** [keithf4/pg_partman#113]
I have a schema that uses a mixture of manually created table partitions and pg_partman partitions that isn't working as I'd like. I could use some direction; perhaps I'm doing something that doesn't make sense, or have made a mistake somewhere along the way.

I have statistical data in a table that I would like to age at various rates depending on the value of a particular column. For example, the top-level parent schema looks something like:

```
example=> \d+ stat_data;
                                     Table "seb.stat_data"
      Column       |            Type             | Modifiers | Storage  | Stats target | Description
-------------------+-----------------------------+-----------+----------+--------------+-------------
 data_id           | bigint                      | not null  | plain    |              |
 resolution        | smallint                    | not null  | plain    |              |
 timestamp         | timestamp without time zone | not null  | plain    |              |
 data              | text                        | not null  | extended |              |
Indexes:
    "stat_data_pkey" PRIMARY KEY, btree (data_id)
Triggers:
    insert_stat_data_trigger BEFORE INSERT ON stat_data FOR EACH ROW EXECUTE PROCEDURE stat_data_insert_trigger()
Child tables: stat_data_1h,
              stat_data_1m,
              stat_data_1s
```

Here, I have a `resolution` field which has a value of 1, 60, or 3600 depending on whether the datum represents data collected over 1 second, 1 minute, or 1 hour. I keep the 1-second data around for some some amount of time, the 1-minute data for a longer amount of time, and the 1-hour data for even more time.

In order to implement this scheme, I've manually created three child table partitions (as you can see above) with a manually configured trigger which inserts into the proper child table depending on the value of `resolution`. I then use `pg_partman` to create `timestamp` based table partitions of each of these in order to efficiently age out data at the appropriate rate. For example, for the 1-second resolution partition:

```
CREATE TABLE stat_data_1s (
        CHECK (resolution = 1)
) INHERITS (stat_data);

SELECT partman.create_parent('seb.stat_data_1s', 'timestamp', 'time', 'half-hour');
UPDATE partman.part_config SET retention='6 hours' WHERE parent_table='mds.stat_data_1s';
```

The problem that I have is that when I insert into the parent table, the rows are inserted into child tables (`stat_data_1s`, `stat_data_1m`, and `stat_data_1h`), but the trigger functions created by pg_partman that should insert the rows into the `timestamp` based children of these partitions don't seem to be working. Here's what the `stat_data_1s` table looks like:

```
hercules=> \d+ stat_data_1s;
                                    Table "seb.stat_data_1s"
      Column       |            Type             | Modifiers | Storage  | Stats target | Description
-------------------+-----------------------------+-----------+----------+--------------+-------------
 data_id           | bigint                      | not null  | plain    |              |
 resolution        | smallint                    | not null  | plain    |              |
 timestamp         | timestamp without time zone | not null  | plain    |              |
 data              | text                        | not null  | extended |              |
Indexes:
    "stat_data_1s_slice_timestamp_index" btree (slice_id, "timestamp")
Check constraints:
    "stat_data_1s_resolution_check" CHECK (resolution = 1)
Triggers:
    stat_data_1s_part_trig BEFORE INSERT ON stat_data_1s FOR EACH ROW EXECUTE PROCEDURE stat_data_1s_part_trig_func()
Inherits: stat_data
```

It appears on the surface that the trigger on the `stat_data_1s` table isn't firing at all when rows are inserted.

**Comment by keithf4** [comment]
Can you provide the source for your `stat_data_insert_trigger()` function?

**Comment by sebroy** [comment]
Yes, it is:
```
CREATE OR REPLACE FUNCTION stat_data_insert_trigger()
RETURNS TRIGGER AS $$
BEGIN
        IF (NEW.resolution = 1) THEN
                INSERT INTO stat_data_1s VALUES (NEW.*);
        ELSIF (NEW.resolution = 60) THEN
                INSERT INTO stat_data_1m VALUES (NEW.*);
        ELSIF (NEW.resolution = 3600) THEN
                INSERT INTO stat_data_1h VALUES (NEW.*);
        ELSE
                RAISE EXCEPTION 'Unsupported resolution';
        END IF;
        RETURN NULL;
END;
$$
LANGUAGE plpgsql;
```

**Comment by keithf4** [comment]
So, I'm able to reproduce this as you described, but why this is happening I'm still not sure. What's weird is sub-partitioning works just fine and inserts things into the lowest child table, firing each child table's trigger as expected. If you want to see this you can comment out the `BEGIN;` and `ROLLBACK;` lines in the `test/test-time-time-time-subpart.sql` and run pg_prove. 
```
pg_prove -ovf test/test-time-time-time-subpart.sql
```
This test does not run the undo functions, so leaves the 3-level sub-partition set in place when not run within a transaction. At first glance, not seeing anything different about what I did vs what you did. But maybe you'll spot something I missed. Will keep looking.

**Comment by keithf4** [comment]
Actually, just realized I ran my test wrong. I'd partitioned the `1s` table as you did but was trying to insert a resolution of `3600`. So, obviously that wouldn't work. I added some notices into your trigger function as well as mine to ensure both are firing. Are you sure you partitioned all 3 of your resolution tables before testing?
```
keith@keith=# select * from stat_data;
 data_id | resolution | timestamp | data 
---------+------------+-----------+------
(0 rows)

Time: 0.790 ms
keith@keith=# insert into stat_data (data_id, resolution) values (1, 1);
NOTICE:  partman trigger fired
CONTEXT:  SQL statement "INSERT INTO stat_data_1s VALUES (NEW.*)"
PL/pgSQL function stat_data_insert_trigger() line 4 at SQL statement
NOTICE:  stat_data_insert_trigger fired
INSERT 0 0
Time: 4.570 ms
keith@keith=# select * from only stat_data;
 data_id | resolution | timestamp | data 
---------+------------+-----------+------
(0 rows)

Time: 0.416 ms
keith@keith=# select * from only stat_data_1s;
 data_id | resolution | timestamp | data 
---------+------------+-----------+------
(0 rows)

Time: 0.467 ms
keith@keith=# select * from stat_data_1s_p2016_05_09_1330;
 data_id | resolution |         timestamp          |  data  
---------+------------+----------------------------+--------
       1 |          1 | 2016-05-09 13:47:51.725758 | «NULL»
(1 row)

Time: 0.465 ms
keith@keith=# select * from stat_data;
 data_id | resolution |         timestamp          |  data  
---------+------------+----------------------------+--------
       1 |          1 | 2016-05-09 13:47:51.725758 | «NULL»
(1 row)

Time: 0.877 ms
```

**Comment by keithf4** [comment]
Just realized the notices are out of order. That's because I put them at the end of the trigger function, so the reversed order makes sense. Sorry for the confusion there.

**Comment by sebroy** [comment]
I did partition the tables, and the partitions show up (they didn't show up above in my original post because retention dropped them all and hadn't created new ones due to the lack of new rows). I believe I've root-cause the problem. The issue is that timestamp column values of rows being inserted are UTC, while the table partitions generated by pg_partman are based on localtime, which is US/Pacific. So, I have these partitions:

```
Child tables: stat_data_1s_p2016_05_09_0900,
              stat_data_1s_p2016_05_09_0930,
              stat_data_1s_p2016_05_09_1000,
              stat_data_1s_p2016_05_09_1030,
              stat_data_1s_p2016_05_09_1100,
              stat_data_1s_p2016_05_09_1130,
              stat_data_1s_p2016_05_09_1200,
              stat_data_1s_p2016_05_09_1230,
              stat_data_1s_p2016_05_09_1300,
              stat_data_1s_p2016_05_09_1330
```

Meanwhile, rows inserted into the parent `stat_data_1s table`:
```
hercules=> select timestamp from stat_data_1s order by timestamp desc limit 5;
      timestamp
---------------------
 2016-05-09 18:59:06
 2016-05-09 18:59:06
 2016-05-09 18:59:05
 2016-05-09 18:59:05
 2016-05-09 18:59:05
(5 rows)
```

Mystery solved. The issue I need to address is ensuring that the tool that creates the schema (which is done using Flyway in Java) runs with a UTC timezone, the same as the postgres process (and the maintenance function) will run with.

**Comment by keithf4** [comment]
Timezones and daylight savings are both the worst.

Glad you were able to find the cause!
