### ISSUE TITLE
Why do we enforce minimum numeric range as 10?

### ISSUE THREAD

**Issue by yemkay** [keithf4/pg_partman#115]
Please consider this as just a question. I'd like to use this extension to partition my table on an integer column. Each of the values in this column could have thousands of entries and it makes sense for me to keep one partition of each value. But I understand the extension enforces a minimum numeric range to be 10. Is there any specific reason for this?

**Comment by keithf4** [comment]
The logic for creating new partitions wasn't working properly when a value of 1 or 2 was used. Discussed this previously in the two issues below. Right now I don't see a way to support both a single ID per partition as well as ranges of values at the same time.

https://github.com/keithf4/pg_partman/pull/15#commitcomment-5037258
https://github.com/keithf4/pg_partman/issues/39

**Comment by yemkay** [comment]
Thank you!
