### ISSUE TITLE
How to pre-make partitions till N? 

### ISSUE THREAD

**Issue by yemkay** [keithf4/pg_partman#116]
Hi, another question.

I'm partitioning my table B by id with run_maintenance disabled and range as 10 . Its not sub-partitioned.

Assuming the table has partitions till _p50. I noticed that when a record comes with id as 75, it will get inserted into the parent table.

The automatic creation of partitions work only if the id is sequential. This id is a primary key in another table A and I'd like to create partitions in table B, as and when the value of id grows in table A. I can do this from a trigger in A, but didn't find any relevant function to do so. Please advice.

**Comment by keithf4** [comment]
Serial partitioning in pg_partman is based entirely around the data that exists in the partition set itself at the time that maintenance runs, so I have no way to base that off of data that exists in another table.

You've got a few options here:

Set the premake configuration value higher to so it has more future tables available. There's no penalty for doing so other than you'll have a lot of extra partitions made that may not have been used yet.

Another option would be to set up the `check_parent()` function to run and monitor the parent table and if it finds anything, kick off the `partition_data_id()` function (or the python script) to move the data out of the parent and create child tables as needed.
