### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by 1803** [keithf4/pg_partman#117]
Are you planning on making pg_partman cross-platform?
Maybe I'm missing something and there's a way to build it for windows already?

**Comment by keithf4** [comment]
Please see https://github.com/keithf4/pg_partman/issues/111
It's as cross-platform as I'm able to make it at this time.

**Comment by 1803** [comment]
Oh, thanks a lot. Managed to build extension with BGW.
Used this article by Craig Ringer http://blog.2ndquadrant.com/compiling-postgresql-extensions-visual-studio-windows/
Maybe it'd be a good idea to describe the whole process. Can help.
