### ISSUE TITLE
rules are not applied to children tables

### ISSUE THREAD

**Issue by plockaby** [keithf4/pg_partman#121]
I have a simple rules on my auditing table:

```create rule forbid_update as on update to macpoll.macpoll do instead nothing;```

This rule is not persisted to the children tables when I run ```create_parent```.

**Comment by keithf4** [comment]
The postgresql inheritance system does not propagate rules to child tables. Triggers are not propagated either. Both are much trickier to handle than normal table properties. May see if I can do this if I can ever get a generic trigger inheritance system working (https://github.com/keithf4/pg_partman/issues/42).

**Comment by keithf4** [comment]
Added this to https://github.com/keithf4/pg_partman/issues/42 to see if it can be added as part of that feature. Closing this issue for now.
