### ISSUE TITLE
ID partitionning: Create partition for 1 exact value

### ISSUE THREAD

**Issue by thomasboussekey** [keithf4/pg_partman#124]
Hello,

I try to create an `ID partitionning` with one partition per integer.
We use a _human readable_ identifier, that is 12 digits long, and we want to create 1 partition per **exact value** of this identifier.

Looking into the code of the extension, I see that the lower value for parameter `p_interval` in the function `create_parent` is 10. So our **ids** are floored to the nearest tenth.

Have you already tried to change the `p_interval` minimal value to 1?

Thanks in advance for your help,
Regards,
Thomas

**Comment by keithf4** [comment]
Unfortunately, with the way I've implemented ID partitioning to work with ranges, I cannot support a single integer value per partition.

I discuss this in issue https://github.com/keithf4/pg_partman/issues/115 and also reference the other issues where this bug was discovered. 

The range_partitioning extension I mention in the README I believe should allow you to do this.

**Comment by thomasboussekey** [comment]
Hello Keith,

Thanks for your feedback.

Thanks for the information about `range_patitioning`, I didn't know this extension.

To be able to use your extension, we have modified our `ID` field, adding a final **0** digit, in order to align the partition name with the `ID` value, to ease support on the schema.

Are you interested in adding a new functionnality on `pg_partman` to manage single ID partitioning?
If yes, I'm interested in contributing.

Have a nice day,
Thomas

**Comment by keithf4** [comment]
Yeah, I was thinking I could possibly look into handling the situation for smaller partition intervals like that. If you'd like to do some work and create a pull request, I'd be happy to review it. Keep in mind it's not just single value partitioning that doesn't work. I know an interval of 2 does not work as well, so I just made it 10 as the minimum to avoid any issues for now.

**Comment by 1803** [comment]
As an alternative workaround one could use ID partition with partition interval say '10' and use `alter sequence [seq_name] increment by 10`.

**Comment by keithf4** [comment]
Just a note on this issue. Not sure this will ever work with pg_partman's trigger based partitioning nor the native range partitioning in 10. This would likely have to be a native list partition. Will see if there's any way to incorporate this option once a stable version of 10 has been released.

**Comment by keithf4** [comment]
So I haven't forgotten about this feature, but I don't think it will be something I'll be able to support in pg_partman. Having only a few values per child table is something that is definitely better done with the new LIST partition method mentioned previously and pg_partman is primarily designed to work with RANGE partitioning. I'll be happy to revisit this again in the future of someone has a workable solution that doesn't over-complicate the extension too much. For now I'm am going to be marking this "wontfix" and encourage anyone needing this to look into native LIST partitioning instead.
