### ISSUE TITLE
Allow trigger function to be optionally composable

### ISSUE THREAD

**Issue by vietord** [keithf4/pg_partman#128]
As is the trigger function returns NULL on successful insertion in order to halt the processing chain and avoid a double insert. However, that results in two key limitations: 

1. It makes it impossible to compose pg_partman managed partitions into scenarios which have additional before insert triggers.
1. It prevents using the view based 'instead of insert' workaround for returning row counts, which makes it difficult to use with many existing ORMs.

As a user I'd like to be able to specify whether pg_partman is operating standalone, and should return NULL, or is operating as part of a larger environment and return the NEW row, allowing other triggers to take further action on it. 

In practice all this boils down to is returning NEW or NULL based on configuration. Proposed implementation attached in #127 

I've only done limited testing on sub_partitions, but it does not seem like they'd require modification, and in my limited testing everything behaved as expected with the sub_partiton triggers remaining unmodified.

**Comment by keithf4** [comment]
Definitely like this option, but not so sure I like the configuration name chosen. It sort of makes sense with all the context given here, but I'd rather have it be more self-evident in the config name itself. Perhaps `trigger_return_null` with TRUE being the default value and FALSE doing what your proposed patch does?

**Comment by vietord** [comment]
That's a much better name, PR updated!

**Comment by keithf4** [comment]
I've got another release I'm working on to hopefully get out soon. Will get to reviewing this as soon as I can, but it may be a little while. Thanks!

**Comment by keithf4** [comment]
This feature has been added in version 2.6.0
