### ISSUE TITLE
hourly partitioning not working as expected?

### ISSUE THREAD

**Issue by broseed** [keithf4/pg_partman#131]
I'm using version 2.4.1.  I've setup hourly partitioning on a table. The BGW is running hourly maintenance.  While the initial call to create default hourly partitions work fine (I used 4 for premake), as those hours approach, new partitions are not created in the future and once the time passes for the latest partition, errors occur due to:

error: Table partition name requires a suffix value

What can I do to troubleshoot?  If I change the interval to daily instead of hourly, that seems to work fine.

**Comment by keithf4** [comment]
Can you send me the schema for your parent table and the full entry in the part_config table?

Is there any new data being inserted? By default, new partitions will not be created if no new data is being inserted. If there are gaps larger than your premake value between when data is inserted, then I advise making the premake (and maybe the optimize_trigger) value larger or making the partitioning interval larger.

**Comment by broseed** [comment]
It looks like setting 'infinite_time_partitions' to true resolved my issue.  Inserts into the table, in testing, is sporadic.  So, what I saw was:

- partitions were created with 5 hours of future intervals
- no data inserted into the master table during this time
- 6 hours later, all partitioned tables were deleted, even though I set 'retention' to 336 (2 weeks worth of hourly data)
- attempts to insert failed with the 'error: Table partition name requires a suffix value'

Is this expected behavior when partition tables are empty with run_maintenance as a BGW and 'infinite_time_partitions' set to false?

**Comment by keithf4** [comment]
No, that's not expected behavior for the insert. It should just be putting the data into the parent table if the children don't exist. Sounds like a syntax error somewhere in a code branch I wasn't testing.
Please share your table's schema and the entire entry in part_config for it.

As for the retention, if this is time-based partitioning, you should be entering a time interval, not an integer value. If it's time-based, it casts the retention value to the interval type, so you're value is being interpreted as 336 seconds
```
keith@keith=# select '336'::interval;
 interval 
----------
 00:05:36
(1 row)
```

**Comment by keithf4** [comment]
Were you able to find the cause of the insert errors? 
I've created some hourly partition sets myself and tested things out when maintenance hasn't been run for a while. It's just throwing the data into the parent as I was expecting.

If this is still an issue for you, I'll need a working example to cause the error to be able to debug the problem.

**Comment by broseed** [comment]
Sorry for the delayed reply.  It turns out the issue was not setting a default value for the timestamp column on the view where I'm inserting via an INSTEAD OF trigger. So, I'm all set.  Thanks for your help!

**Comment by keithf4** [comment]
Thanks for letting me know!
