### ISSUE TITLE
insert trigger doesn't play nice with ON CONFLICT 

### ISSUE THREAD

**Issue by coreyatmoat** [keithf4/pg_partman#132]
When doing
```
INSERT INTO my_partitioned_table
select <subquery>
ON CONFLICT(unique_key_part1,unique_key_part2)
DO update set some_value = EXCLUDED.some_value;
```

Instead of firing the ON CONFLICT, I get the error message 
```pg_partman insert into child table failed, row inserted into parent (schema.table_name). ERROR: duplicate key value violates unique constraint```

**Comment by keithf4** [comment]
There's a feature in 2.5.0 to automatically handle upsert in some cases for you.

Outside of that, I'm really not sure how well upsert is going to work with pg_partman in general. Inheritance makes it quite messy.

**Comment by coreyatmoat** [comment]
Indeed, on 2.3.3 here.

The workaround for this issue is simple, and I agree that inheritance makes it very complicated.

**Comment by keithf4** [comment]
See if the new feature in 2.5.0 handles this for you. If not, going to need a working example to reproduce the error.

**Comment by coreyatmoat** [comment]
Not sure I'll have the flexibility with this change, but I will update you if I do.

**Comment by keithf4** [comment]
Going to close this issue for now. If you have any issues with upsert that you think pg_partman should be able to handle, please create a new post.

**Comment by coreyatmoat** [comment]
I agree.
