### ISSUE TITLE
Adding or removing columns

### ISSUE THREAD

**Issue by ykim** [keithf4/pg_partman#133]
Can pg_partman handle the addition or removal of columns from partitioned tables? If not, are there specific instructions or guides on how to achieve this?

**Comment by keithf4** [comment]
Adding new columns should just work and is entirely dependent on the inheritance system in postgresql and has little to do with pg_partman itself.

Removing columns may be a bit trickier depending when the column was added. Andrew Dunstan wrote a short blog explaining this very well

http://adpgtech.blogspot.com/2015/07/dropping-columns-on-partitioned-tables.html

I do have plans on adding a function to drop columns and handle this automatically.

**Comment by ykim** [comment]
@keithf4: Thanks for the information. This is the exact answer I was looking for.  👍
