### ISSUE TITLE
Future partitions not created by run_maintenance()

### ISSUE THREAD

**Issue by kkartaltepe** [keithf4/pg_partman#136]
Like the comment in #80 mentions. I am having issues with getting future partitions to be created on a monthly table after manually dropping some child tables.

In this case there is data the current month but the next `premake` worth of months are not being created.

In order to reach this state I had all my data partitioned with the proper premake children created. Then I did `undo_partition` putting everything in the parent table, deleted all children, changed some indices on the parent, then re-partitioned with `partition_data_time`. This put all the data back into the proper tables but did not create any future partitions, even after rerunning `run_maintenance`.

This was in pg_partman 2.2.2

**Comment by keithf4** [comment]
Can you post the following:

- the `part_config` entry for this partition set, 
- the parent schema and full listing of all child tables (you can get this by doing `\d+ parent_table` in psql
- current max value of the entire partition set by doing `SELECT max(control) from parent_table`.

**Comment by kkartaltepe** [comment]
```
-[ RECORD 1 ]----------+-------------------
parent_table           | utility.dc_reading
control                | gw_ts_date_created
partition_type         | time
partition_interval     | 1 mon
constraint_cols        |
premake                | 5
optimize_trigger       | 4
optimize_constraint    | 30
epoch                  | f
inherit_fk             | t
retention              |
retention_schema       |
retention_keep_table   | t
retention_keep_index   | t
datetime_string        | YYYY_MM
use_run_maintenance    | t
jobmon                 | t
sub_partition_set_full | f
undo_in_progress       | t
```
```
postgres=# select max(gw_ts_date_created) from utility.dc_reading;
-[ RECORD 1 ]---
max | 2016-08-24
```

Schema over here since it probably wouldnt look very pretty in a comment.
https://gist.github.com/kkartaltepe/6358151a3bb74beeffabeee311c418e2

**Comment by keithf4** [comment]
The `undo_in_progress` column is set to true. Not sure how that happened if you recreated the entire partition set from scratch. That tells run_maintenance() to stop working because it thinks you're in the middle of unpartitioning things.

**Comment by kkartaltepe** [comment]
Well I did run `undo_partition` the to undo all the partitions in the very beginning since it was easier to shuffle some dates around if everything was just in the parent table. There were some issues like I ran out of space once while running `undo_partition` and had to run it a second time. Perhaps something during that process just left the flag set?

**Comment by kkartaltepe** [comment]
Can I safely just set that back to 'f' and everything will just work?

**Comment by keithf4** [comment]
Should be able to set that back yeah. 

I was under the assumption you ran the undo to completion then ran create_parent() again. That should have completely removed the entry in the part_config table and created a new one from scratch. If you only did that to move some of the data to the parent, then partitioned that again, it would leave it in the state you're in now.

**Comment by kkartaltepe** [comment]
Well it fully migrated all the data but It didnt remove the entry from part_config so I couldnt re-run `create_parent`. I'll just chalk it up to the running out of space during undo_partition.

Updating the `undo_in_progress` column and re-running `run_maintenance` did the trick.
Thanks for the assistance and I love the extension it makes managing partitions so much easier!

**Comment by keithf4** [comment]
No problem. Glad it was an easy fix :)
