### ISSUE TITLE
apply_privileges is slow

### ISSUE THREAD

**Issue by Crack** [keithf4/pg_partman#139]
Hi,

Database with lots of objects strikes back ;)

After installing pg_partman 2.6.0 I checked whether I can do some more optimizations and found that `apply_privileges` (called from `create_partition_*` functions) takes about 2.4s for each execution (privileges are already correct so it does no real work besides checking). The slow part turned out to be the call to `information_schema.table_privileges`, which in PostgreSQL is designed to never use any indexes - this view casts all PostgreSQL `name` columns to `text`, making all indexes unusable due to type incompatibility.

pg_partman should use its own implementation of [`table_privileges`](https://github.com/postgres/postgres/blob/REL9_4_STABLE/src/backend/catalog/information_schema.sql) view. In my tests I simplified the original view by removing casts and some unused columns:

``` SQL
CREATE OR REPLACE VIEW partman.table_privs AS
    SELECT u_grantor.rolname AS grantor,
           grantee.rolname AS grantee,
           nc.nspname AS table_schema,
           c.relname AS table_name,
           c.prtype AS privilege_type
    FROM (
            SELECT oid, relname, relnamespace, relkind, relowner, (aclexplode(coalesce(relacl, acldefault('r', relowner)))).* FROM pg_class
         ) AS c (oid, relname, relnamespace, relkind, relowner, grantor, grantee, prtype, grantable),
         pg_namespace nc,
         pg_authid u_grantor,
         (
           SELECT oid, rolname FROM pg_authid
           UNION ALL
           SELECT 0::oid, 'PUBLIC'
         ) AS grantee (oid, rolname)

    WHERE c.relnamespace = nc.oid
          AND c.relkind IN ('r', 'v')
          AND c.grantee = grantee.oid
          AND c.grantor = u_grantor.oid
          AND c.prtype IN ('INSERT', 'SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'REFERENCES', 'TRIGGER')
          AND (pg_has_role(u_grantor.oid, 'USAGE')
               OR pg_has_role(grantee.oid, 'USAGE')
OR grantee.rolname = 'PUBLIC');
```

and in `apply_privileges` changed all references to use this view (with proper casting of schema and table names to `name` type). Execution time dropped to 200 ms in first execution, and 100 ms in subsequent calls.

Can you integrate this change into pg_partman?

**Comment by keithf4** [comment]
Wow! Thank you! The apply_privileges stuff was pretty early in my design and I did go the easy route with information_schema. I'll definitely see about getting this into the next version.

**Comment by keithf4** [comment]
The below Gist contains the next patch update for pg_partman and includes this fix. If you've got time, please test it out in the environment where you encountered the performance issue and let me know how it goes. It's not the final version, so please don't install it on your prod system yet. I'll hopefully have the update out next week sometime then.

https://gist.github.com/keithf4/e86bafa682f086ad90b67e2240281f7d

**Comment by Crack** [comment]
Works ok.

By the way, how about moving comments in functions a bit lower, after `AS $$` (and after `AS` in view), so that they are retained in database?

**Comment by keithf4** [comment]
Not a bad idea. I'll see about doing that another time when I have to change something in most of the functions.

**Comment by keithf4** [comment]
I've pushed up v2.6.1 with these changes.
Waiting on tagging a new version while I evaluate it further on current systems.

**Comment by keithf4** [comment]
v2.6.1 tag has been released

**Comment by lorenzolucioni** [comment]
Regarding the "table_privs" view, I got a permission issue when selecting from pg_authid:
"ERROR:  permission denied for relation pg_authid".

Probably it depends on my effort (that seems succesful done) in use partman without really install is as extension. I solved replacing pg_authid with pg_roles. 
Maybe this replacement worths to be merged in partman.

Thank you,
Lorenzo

**Comment by keithf4** [comment]
Thanks for the note. I'll see if that may be able to be used. I assume this may because you're trying to run it in RDS? Normally the superuser you're running partition maintenance as isn't that limited.
