### ISSUE TITLE
Partitioned table is occupying 300GB of space despite no entries

### ISSUE THREAD

**Issue by yemkay** [keithf4/pg_partman#144]
We have recently partitioned a master table of with couple of millions of rows. This table is partitioned by "id range". There are 7 child tables created under this master table and entries are going into the child table during insert. All these are managed by pg_partman extension.

While running this query, the master table is shown to occupy about 300GB of disk space. This is strange because this table has no entries and I could confirm that by running check_parent() function. 

```
SELECT nspname || '.' || relname AS "relation",pg_size_pretty(pg_relation_size(C.oid)) AS "size"  FROM pg_class C  LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
WHERE nspname NOT IN ('pg_catalog', 'information_schema')  ORDER BY pg_relation_size(C.oid) DESC  LIMIT 30;

```

We never had this problem while partitioning this table in other environments where the data is not that much. Could this be due to unreleased disk space during partitioning?

**Comment by keithf4** [comment]
Sounds like bloat. 

https://www.keithf4.com/checking-for-postgresql-bloat/#why

If the rowcount on the parent table is showing zero, you should be able to run a VACUUM FULL on it with little interruption and get all the space back. The above blog post also discusses a tool for detecting bloat I've worked on.

**Comment by keithf4** [comment]
Closing issue for now. If you have any further question, please reopen.
