### ISSUE TITLE
Documentation for time-custom

### ISSUE THREAD

**Issue by gregn610** [keithf4/pg_partman#146]
I'd like to partition by financial year but can't see the way forward with create_parent().
Could we please get an example of how to use time-custom.

Thank you
~~~
time-custom
Allows use of any time interval instead of the predefined ones below. Works the same as "time".
Note this method uses a lookup table as well as a dynamic insert statement, so performance will not be as good as the predefined intervals. So, while it is more flexible, it sacrifices speed.
Child table creation is kept up to date by run_maintenance() function.
~~~

**Comment by keithf4** [comment]
Sorry for lack of clarity, but there's really nothing much more complex about setting it up. Just use `time-custom` as the partitioning type and then you can set any valid value for the PostgreSQL interval type above 1 second. The section you quoted there is just a notice to let you know it won't be as performant as the pre-set interval values of the normal `time` partitioning.

It's also discussed a little further in the summary section at the top of the documentation. 
https://github.com/keithf4/pg_partman/blob/master/doc/pg_partman.md#custom-time-interval-considerations

**Comment by keithf4** [comment]
Also in your case, I'm not sure there is a way to partition by financial year. That's not really a different interval of time. I'd suggest monthly or quarterly in your case.
