### ISSUE TITLE
Need help using drop_partition_id()

### ISSUE THREAD

**Issue by Hawker65** [keithf4/pg_partman#147]
Hello,
I'm trying to use `drop_partition_id()` as such : 

    SELECT partman.drop_partition_id(test.part_test, p_keep_table := FALSE);

The problem is that I get the following error :
 
    ERROR:  missing FROM-clause entry for table "test"

Here, `test` is a schema and `part_test` is a table within that schema. This tabled was partitioned by date, and then by id. If you happen to know the solution, feel free to post it.

Thank you for reading.

**Comment by keithf4** [comment]
If that's exactly how you're entering it, the first value to the function is a text value, so it has to be surrounded by single quotes.
```SELECT partman.drop_partition_id('test.part_test', p_keep_table := FALSE);```

**Comment by Hawker65** [comment]
Thanks, it's working, but I get another error:

    ERROR:  Configuration for given parent table with a retention period not found: test.part_test
    CONTEXT: 
    DETAIL: 
    HINT: 

I've searched inside the source code and apparently, the partition interval `v_partition_interval` is NULL but my table is partitioned as such : 

    part_test
    part_test_p2016_11_03
    part_test_p2016_11_03_p0
    part_test_p2016_11_03_p10
    part_test_p2016_11_03_p20
    ...
    part_test_p2016_11_15_p20

I don't understand what this variable is associated to. Sorry if these are beginner mistakes, I'm not that good with SQL.

**Comment by Hawker65** [comment]
Also, what is the difference between `undo_partition_id()` and `drop_partition_id`?

**Comment by rodo** [comment]
Hi @Hawker65,

Did you have a look at the python script shipped with partman ? May be it'll be useful for to drop your partitions, all is documented here https://github.com/keithf4/pg_partman/blob/master/doc/pg_partman_howto.md#undo-partitioning-simple-serial-id

**Comment by Hawker65** [comment]
Hi, I have used the SQL function which basically does the same thing but I was wondering if there was a way to undo all the partitioning in only one instruction. Also, I didn't understand very well the difference between `undo_partition_id()` and `drop_partition_id()` (or time). From what I understand, `undo_partition_id()` removes the of partitioning of a table and transfers the content to the parent. Is `drop_partition_id()` just removing the partitions that are too old?

**Comment by keithf4** [comment]
`drop_partition()` should rarely ever be called manually. As the partman.md file states, it's mostly used for maintenance and is called automatically by run_maintenance(). Not sure it should be giving that retention error, but that's one of the main things it's used for.

`undo_partition()` and it's related functions are for moving all the data in child tables back into the parent. If no additional parameters for it are set, all the plpgsql function will do is move a single child back into the parent. You have to set the parameters for it to do more. If you're undoing an entire partition set, it's recommended to use the python script that rodo mentioned. The plpgsql function does everything all in one single transaction whereas the script will commit in batches.

**Comment by keithf4** [comment]
A `DROP TABLE` is good enough to remove any table from the partition set. However, if that table is still part of the static section of the trigger, it could cause problems. I'd highly recommend looking into the retention system vs manually removing them if it's going to be a regular occurrence.

**Comment by keithf4** [comment]
Please read this section of the documentation

https://github.com/keithf4/pg_partman/blob/master/doc/pg_partman.md#destruction-functions

`drop_partition()`  needs some way to know what tables you're trying to drop. So you either have to configure the retention policy for that partition set, or pass the appropriate parameters to the function. Otherwise it has no idea what partitions it is you're trying to get rid of.

**Comment by Hawker65** [comment]
Thanks for the answers. Basically, what we are trying to do is to partition daily but remove the old partitions manually for internal reasons. So, if we partition with a 4 day interval, we'll have to run `run_maintenance()` at least twice a day and set `retention = NULL` in the `part_config` table? 

Thank you so much for the answers

**Comment by keithf4** [comment]
If you must run this manually, just call `drop_partition_time()` and pass the appropriate interval value for the retention parameters to that function. You can then leave the retention values in `part_config` NULL.

**Comment by Hawker65** [comment]
Understood. Many thanks!

**Comment by keithf4** [comment]
FYI, if you're paranoid about losing data and want to make retention maintenance easier, look at the options available to dump the child tables out. Or just use the option to move the child table to a different schema. You can then come back and check the data in those moved children and either drop them or move them back or their original schema and re-inherit them.
