### ISSUE TITLE
Handle Epoch Milliseconds

### ISSUE THREAD

**Issue by madisonleavo** [keithf4/pg_partman#150]
Allow "column that the partitioning will be based on" to handle both seconds and milliseconds from epoch.

**Comment by keithf4** [comment]
Adding note here for future reference:

Change `epoch` column to be a text type with constrained values of 'none', 'second', 'millisecond'. Avoids adding another config option to allow this.

**Comment by keithf4** [comment]
I've got the update file to add support for millisecond epoch partitioning in the Gist below. If you'd like to give it a try and let me know if it works ok for you, I'd appreciate the extra eyes.

Note this is not the final revision for the next version of pg_partman, so please don't install this on any production systems.

https://gist.github.com/keithf4/dd3e7eb1786518a74268af3ce76245f7

You can place this in the `.../share/extension` folder wherever that's located on your system then just run `ALTER EXTENSION pg_partman UPDATE TO '2.6.3';`

**Comment by keithf4** [comment]
This feature has been added in version 2.6.3. I've implemented it as stated above where the epoch config option is now a text field that accepts 'none', 'seconds', or 'milliseconds'. Any current epoch partition sets will be set to "seconds" automatically when the extension update is installed.
