### ISSUE TITLE
Amazon RDS compatibility with PG_PARTMAN 2.6.2

### ISSUE THREAD

**Issue by thomasboussekey** [keithf4/pg_partman#152]
Hello,

I'm using pg_partman on 2 type of `postgresql` instances:
* On premise linux servers
* Amazon RDS postgresql instances.

On my last installation attempt on an `Amazon RDS postgresql` instances, I tried to use `PG_PARTMAN` version **2.6.2**.
I'm using the sql script (ex:`/usr/pgsql-9.5/share/extension/pg_partman--2.6.2.sql`) contained in the extension replaction `@extschema@` by `partman`, my partitioning management schema.

It generated errors like this one:
```shell
ERROR: permission denied for relation pg_auhtid
```
My previous installation was performed successfully with version **2.5.0**.
I performed a `DIFF` check between the SQL scripts of versions **2.5.0** and **2.6.2**.

```shell
diff /usr/pgsql-9.5/share/extension/pg_partman--2.5.0.sql /usr/pgsql-9.5/share/extension/pg_partman--2.6.2.sql | grep authid
>          pg_authid u_grantor,
>            SELECT oid, rolname FROM pg_authid
```

I'm reinstalling with version **2.5.0**.

It seems that the pg_authid is hard to access or doesn't exist on RDS instances...

Is there a workaround to keep `PG_PARTMAN` working with `Amazon RDS postgresql` instances?

Regards,
Thomas

**Comment by keithf4** [comment]
There is a pending push request to fix the pg_authid permissions issue (https://github.com/keithf4/pg_partman/pull/151). It will hopefully be in the next release.

**Comment by thomasboussekey** [comment]
Thank you Keith for the update!

Have a nice day,
Thomas

**Comment by keithf4** [comment]
Please see update in Issue 151. Right now I cannot support a change to using information schema due to pretty significant performance bottlenecks. Please contact AWS support about this if you really need pg_partman to work in RDS.

**Comment by thomasboussekey** [comment]
Hello Keith,

I've compiled the commit on a production database, managing hundreds of
partitions.

No performance bottleneck encountered for the moment.
But we will onle begin a test campaign on Monday.

Many thanks for the information,
I keep in touch with you to inform you on our tests.

Regards,
Thomas

2016-12-16 20:35 GMT+01:00 Keith Fiske <notifications@github.com>:

**Comment by keithf4** [comment]
This issue becomes a problem when your system catalogs have enough objects in them that doing a sequential scan on tables like pg_class and pg_attribute become a much more expensive operation. Most people rarely encounter that many tables unless that start partitioning, which is why it's a more sensitive thing to be aware of in this extension. If you look through the source, you'll see I've done many casts to the internal type `::name` whenever querying system catalogs because that is the data type the indexes are created on. Information schema views unfortunately often don't do this cast.

**Comment by hekike** [comment]
@thomasboussekey did it work for you at the end of the day?

**Comment by thomasboussekey** [comment]
Hello all,

It's in production, since december.

There are few users, and very few inserts.
No problem were encountered.

We plan to move our European production database, in the coming weeks (150
K rows/day), I will have a better feedback in this context.

Regards,
Thomas

2017-03-23 15:29 GMT+01:00 Peter Marton <notifications@github.com>:

**Comment by hekike** [comment]
How much table and partition do you plan to maintain with `pg_partman`?
Right now we are testing it with 4 tables and 56 partitions. (14 days data retention) on RDS.

**Comment by thomasboussekey** [comment]
Hello Peter,

4 tables are partitionned
2 of them have 60 partitions (One per managed point of sales)
2 of them have one partition per day (3 months retention set today).

Thomas

2017-03-23 20:28 GMT+01:00 Peter Marton <notifications@github.com>:

**Comment by hekike** [comment]
Thanks, Thomas!

Sounds promising.

**Comment by thomasboussekey** [comment]
Hello,

I'm creating a brand new **AWS RDS** `pg_partman` database.

Postgresql RDS version: 9.5.3
Pg_partman version: 2.6.4

In order to make the correct completion of the `pg_partman--2.6.4.sql` successful, I have updated it to `pg_partman--2.6.4.rds.sql` enclosed to this message.
[pg_partman--2.6.4.rds.sql.zip](https://github.com/keithf4/pg_partman/files/885797/pg_partman--2.6.4.rds.sql.zip)


Here is my little changelog:
* Add **@extschema@**
  * For `CREATE TYPE`: One occurence
  * For `CREATE TABLE`: Three occurences
  * On function call `pg_catalog.pg_extension_config_dump`
  * Into index creation for table **custom_time_partitions**
* Change synthax into function creation:
  * Previous synthax: `CREATE FUNCTION` 
  * New synthax: `CREATE OR REPLACE FUNCTION @extschema@.`

For execution into the `pg_partman` schema named: **partman**, I have executed the following steps:
1. Customize the **SQL** script with the shell command:

Assuming my **SQL** file is located on /tmp/pg_partman--2.6.4.rds.sql
Output **SQL** script will be: `/tmp/pg_partman--2.6.4.rds.2.sql`

```shell
partmanSchema=partman
sed -e "s/@extschema@/${partmanSchema}/g" /tmp/pg_partman--2.6.4.rds.sql | sed -e 's/SELECT pg_catalog.pg_extension_config_dump/--SELECT pg_catalog.pg_extension_config_dump/g' > /tmp/pg_partman--2.6.4.rds.2.sql


## Drop and recreate the target partman schema
psql --command="drop schema ${partmanSchema} cascade; create schema ${partmanSchema};"

## Create pg_partman objects into the target partman schema
psql --file=/tmp/pg_partman--2.6.4.rds.2.sql

## Apply matheusespanhol RDS patch
psql --command="drop view ${partmanSchema}.table_privs ;"
psql --command="CREATE VIEW ${partmanSchema}.table_privs AS SELECT grantor::name,grantee::name,table_schema::name,table_name::name,privilege_type::text FROM information_schema.table_privileges;"
```


The output is:

```
CREATE TYPE
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE FUNCTION
ALTER TABLE
ALTER TABLE
CREATE FUNCTION
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
CREATE VIEW
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION

```

1. Then, test that it works:

```sql

DROP SCHEMA IF EXISTS test cascade;
CREATE schema test;
CREATE TABLE test.part_test (col1 serial, col2 text, col3 timestamptz NOT NULL DEFAULT now());

SELECT partman.create_parent('test.part_test', 'col3', 'time', 'daily');
```
And the result is:

```
 SELECT partman.create_parent('test.part_test', 'col3', 'time', 'daily');
 create_parent 
---------------
 t
(1 row)
```

@keithf4 , do you think it can be interesting to re-integrate parts of the `SQL` modifications listed in the file for standard installation?

Hope this helps,
Have a nice week-end,

Thomas

**Comment by keithf4** [comment]
I appreciate the work to get pg_partman working in RDS, but at this time it's not something I'm going to work to support until Amazon provides a means to actually install it as an extension. Without that, it's very difficult for me to provide a means of supporting people running it there since there's really no consistent way to do so.

No objection to you running it there if you can get it working, but it's just not something I can support right now.

**Comment by thomasboussekey** [comment]
Hello @keithf4 & @hekike ,

Yesterday, I met our AWS account manager with one AWS solution architect.

I asked them to add `pg_partman` into the authorized extensions for **RDS**.

I keep you informed of their answer.

Regards,
Thomas

**Comment by hekike** [comment]
@thomasboussekey wow, thanks!

Maybe we should try to convince GCP as well:
https://cloudplatform.googleblog.com/2017/03/Cloud-SQL-for-PostgreSQL-managed-PostgreSQL-for-your-mobile-and-geospatial-applications-in-Google-Cloud.html

https://cloud.google.com/sql/docs/postgres/extensions

**Comment by thomasboussekey** [comment]
Thanks for the information about GCP (I wasn't aware of it!!)

**Comment by hekike** [comment]
@thomasboussekey I've seen a presentation where they asked the audience to recommend extension for final version, but I didn't find it for you :/

So probably it's the right time to do :)

**Comment by keithf4** [comment]
@thomasboussekey thanks I appreciate the effort in getting AWS to adopt it :)

**Comment by vershaarora** [comment]
@keithf4  how do we chcek current installed version of partman?

**Comment by keithf4** [comment]
Use the `\dx` option in psql to check the version of any installed extension. 

Since this was asked in the RDS issue, I'm assuming maybe you somehow got this installed there? If that's the case, and it was not installed as an extension, then there is no reliable way to know which version is installed without an exhaustive comparison of each function's code.

**Comment by thomasboussekey** [comment]
`\dx` doesn't mention extention **pg_partman** as it is installed with scripts.

I have checked into the version upgrade scripts, ex: .../extension/pg_partman--3.0.2--3.1.0.sql  , and as versioning is manged through extension, there is no mention of version ID.

A clue can be to use the version upgrade script in order to identify the version of **pg_partman** installed.
> Perhap's, that there is a function that is update at every version and it can limit the investigation time!

**Comment by keithf4** [comment]
As I've said before, I'm not going out of my way to make this extension more compatible with RDS when the simple solution for much better long term support is for them to just allow third-party extensions and stop restricting normal system catalog access methods. Especially for those extensions that don't require any additional C libraries like this one. I simply don't have the time for that unfortunately.
