### ISSUE TITLE
partition_data.py not moving data in sub-partitions?

### ISSUE THREAD

**Issue by hunleyd** [keithf4/pg_partman#154]
Here's my sequence of steps:
1. first, I partition by an ID: SELECT create_parent('bohcafeorders.cafe_ord', 'cafe_nbr', 'id', '100', p_use_run_maintenance := true);
2. distribute the existing data: python partition_data.py -c host=localhost -p bohcafeorders.cafe_ord -t id -i 100
3. sub-partition by TIME: SELECT partman.create_sub_parent('bohcafeorders.cafe_ord', 'business_date', 'time', 'yearly');
4. re-distribute the existing data: 
  python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p203800 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p204400 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p600600 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p600700 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p600900 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p601000 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p601100 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p601200 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p601300 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p601400 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p601500 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p601600 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p601700 -t time -i 100
 python partition_data.py -c 'host=localhost dbname=pan_mwapp' -p bohcafeorders.cafe_ord_p601800 -t time -i 100

This is where it breaks down. The output looks like:

```
Attempting to turn off autovacuum for partition set...
	... Success!
Total rows moved: 0
Running vacuum analyze on parent table...
Attempting to reset autovacuum for old parent table and all child tables...
	... Success!
```

Each iteration of the script runs w/o issue, but the data doesn't move:

```
pan_mwapp=# SELECT * FROM partman.check_parent() ORDER BY 1;
          parent_table          | count
--------------------------------+--------
 bohcafeorders.cafe_ord_p203800 |  46857
 bohcafeorders.cafe_ord_p204400 |  47256
 bohcafeorders.cafe_ord_p600600 | 285089
 bohcafeorders.cafe_ord_p600700 | 289570
 bohcafeorders.cafe_ord_p600900 |  69680
 bohcafeorders.cafe_ord_p601000 | 202799
 bohcafeorders.cafe_ord_p601200 | 204978
 bohcafeorders.cafe_ord_p601300 |  72149
 bohcafeorders.cafe_ord_p601400 |  29729
(9 rows)
```

I have no idea what I've done wrong. Any pointers? TIA

**Comment by keithf4** [comment]
You're passing an integer based interval (`-i 100`) to a time based parent. Try passing an actual postgresql `interval` value or just leaving it off to commit in the default interval value.

**Comment by hunleyd** [comment]
Oh dear lord. I can't believe how long I looked at that and _still_ didn't see it. Thanks, Keith!

**Comment by keithf4** [comment]
Yeah. Odd that it didn't actually do anything, though. Thought it may have just committed in tiny batches. Let me know if it works
```
keith@keith=# select '100'::interval;
 interval 
----------
 00:01:40
(1 row)
```

**Comment by hunleyd** [comment]
I just left it off and used the default. Worked like a charm. :)
