### ISSUE TITLE
run_maintenance() not creating future partitions

### ISSUE THREAD

**Issue by noahbullock** [keithf4/pg_partman#156]
I am not able to get run_maintenance to create new partitions (indeed it is several partitions behind the present date). Per #136, I checked to see if undo_in_progress was set to 'true' for any of my partitions, but it is 'false' for all of them. I'm running version 2.6.0 on Postgres 9.5.

**Comment by keithf4** [comment]
Is there any new data being inserted according to the timestamp in the control column? By default, new partitions are only created in time series partitioning if new data is added. You can change the config option `infinite_time_partitions` to true if you want new partitions to keep being created even if there's no new data.

**Comment by noahbullock** [comment]
There is new data, but it didn't start coming in until several months after the initial partition set / historical data was set up, so it postdated the most recent partition tables that had been created. I changed `infinite_time_partitions` to true (per above), ran `partition_data_time` until it returned '0' to clean out the parent tables, and now `run_maintenance` works as expected. Thanks for you help and for this excellent extension.
