### ISSUE TITLE
wrong partition chosen by trigger

### ISSUE THREAD

**Issue by FlorianIragne** [keithf4/pg_partman#157]
Hi,

i use latest version of pg_partman on postgresql 9.6, to partition a huge table. Once the table is partitioned, some data failed to be inserted into the partition chosen by the trigger function.

partition structure:
 `id         | integer                  | non NULL Par défaut, nextval('log_id_seq'::regclass) | plain`
 `start      | timestamp with time zone | non NULL                                                             | plain`
 `stop       | timestamp with time zone | non NULL                                                             | plain `
table is partitioned on a daily basis on the "start" field

the constraint for the table for 2016-12-19 is:
`"log_p2016_12_19_partition_check" CHECK (start >= '2016-12-18 23:00:00+00'::timestamp with time zone AND start < '2016-12-19 23:00:00+00'::timestamp with time zone)`

When i try to insert the following record, this partition is chosen but the constraint check obviously fails:
`INSERT INTO "log" ("start", "stop") VALUES ('2016-12-19 23:33:31+00:00', '2016-12-19 23:35:34+00:00');`

If i look at the trigger function that chooses the partition, i can see that the problem either comes from the to_char(v_partition_timestamp, 'YYYY_MM_DD') that returns 2016_12_19 instead of 2016_12_20 (to meet the partition constraint check), or the definition of the check itself.

Or i may use pg_partman in the wrong way?

I've pushed my tests a little bit further. At the creation time, my server timezone was set to "localtime", which means for me "Europe/Paris". If i set server timezone to UTC, drop the last created partition and run_maintenance(), i can see that the last table is created with the proper constraint. 

with timezone='Europe/Paris' :
`"log_p2017_01_02_partition_check" CHECK (start >= '2017-01-01 23:00:00+00'::timestamp with time zone AND start < '2017-01-02 23:00:00+00'::timestamp with time zone)`

with timezone="UTC" :
`"log_p2017_01_02_partition_check" CHECK (start >= '2017-01-02 00:00:00+00'::timestamp with time zone AND start < '2017-01-03 00:00:00+00'::timestamp with time zone)"`

Anyway, i'm looking for the best way to solve this issue. I've currently altered the constraints on each partition and left UTC as my server timezone.

Thanks for any feeback/suggestion

**Comment by FlorianIragne** [comment]
well, actually, i planned to altered the constraint until i realized that it can't be done this way. I have to undo and then redo partitioning. The table is around 600Go so it will take a while to do this.

A better idea? 
Thanks

**Comment by keithf4** [comment]
Are you running the maintenance function from a client that has a different timezone than the server itself? That is the only case where I've seen this happen so far. The client and server timezones must match.

**Comment by FlorianIragne** [comment]
the maintenance function is run from psql client on the server or from a cron job. The initial partitions were made using the python script you provide.

**Comment by keithf4** [comment]
Ok. Then you have to make sure the timezone on the client matches whatever the server has. You can set that on a session basis.

**Comment by keithf4** [comment]
Was that script run on the server itself, or from another client?

Does the database itself run with a different timezone than the server?

**Comment by FlorianIragne** [comment]
the script was run on the server and the database server is now set to utc, the hardware server as timezone Europe/Paris.

When i first ran the partition script, the db was "localtime" so "Europe/Paris" i think.

As for the "correction" part, do you have a better option than undo and then redo partitionning?

thanks for your help

**Comment by keithf4** [comment]
If the constraints themselves are wrong, there's no easy fix other than altering each child's constraint or repartitioning.

If it's the partitioning function that's wrong, you can just run pg_partman's `create_function_time()`.

If you've gone and changed the timezone, then the easiest thing would probably be to repartition it.

Still not sure how you got into this situation without the client & server having different timezone settings. If you can give me a set of steps that recreates this problem without having that difference, I can look into it. Without that, unfortunately there's not much else I can do to help here.

**Comment by FlorianIragne** [comment]
thanks for your advice.

I'll try to reproduce it on another server and i'll let you know if i find how it went wrong the first time
