### ISSUE TITLE
UPDATE from 1.7.2 to 2.6.3

### ISSUE THREAD

**Issue by lexferro** [keithf4/pg_partman#159]
I was updating an installation from 1.7.2 to 2.6.3, it is a very simple use of the extension (just one table with a monthly partition), nothing very complex.
When I run 
`ALTER EXTENSION pg_partman UPDATE TO '2.6.3'; `
I was getting an error 
` ERROR:  no existe la relaciÃ³n Â«custom_time_partitionsÂ» ` (it doesn't exists the relation <<custom_time_partition>>). 
To fix this error, I've just commented (pg_partman--2.3.1--2.3.2.sql)
`-- SELECT pg_catalog.pg_extension_config_dump('part_config_sub', '');`
`-- SELECT pg_catalog.pg_extension_config_dump('custom_time_partitions', '');`

And apparently all is working well.

**Comment by keithf4** [comment]
Hmm... that seems odd. Does the table `custom_time_partitions` exist for you as part of the pg_partman extension? That should have been created back in version 1.6.0. You can do
```
\dx+ pg_partman
```
in psql to see

But now that I look back at it, custom time partitions were only supported in versions 9.2+ so if you had a version previous to that at the time, it may not have been created.

**Comment by keithf4** [comment]
Actually, I found the issue and my last guess what right. In the update to 1.6.0, it would only create that table if the current version of postgresql was 9.2+

https://github.com/keithf4/pg_partman/blob/master/updates/pg_partman--1.5.1--1.6.0.sql#L99

So, if you upgraded from 9.1 to a later version of postgres, that table may never get created. I'll see if I can fix the 2.0.0 upgrade file to create that table if it doesn't exist. That should solve this issue for anyone else doing a similar upgrade to what you were doing.

Thanks for reporting the issue!

**Comment by keithf4** [comment]
You'll probably want to create that table for yourself so your code is consistent. Here's the DDL for it:
```
CREATE TABLE IF NOT EXISTS @extschema@.custom_time_partitions (
    parent_table text NOT NULL
    , child_table text NOT NULL
    , partition_range tstzrange NOT NULL
    , PRIMARY KEY (parent_table, child_table));
CREATE INDEX IF NOT EXISTS custom_time_partitions_partition_range_idx ON custom_time_partitions USING gist (partition_range);
SELECT pg_catalog.pg_extension_config_dump('custom_time_partitions', '');
```
Note the IF NOT EXISTS clause to CREATE INDEX was a 9.5+ feature, so if you're on a previous version of PostgreSQL, just remove that clause and check that you don't have double indexes on the table.

**Comment by lexferro** [comment]
I think I did on 9.3 version, and the first install was the version 1.7.2.
Anyway, I created the table but the last select
`SELECT pg_catalog.pg_extension_config_dump('custom_time_partitions', '');` 
shows this error:  `ERROR:  pg_extension_config_dump() just can be called from SQL executed by CREATE EXTENSION` (I translated it, the error was in spanish, so it's not literally)

**Comment by keithf4** [comment]
Ok. My next update will have that command in as part of it. It will also try to create the table if it does not exist. So you should be all set after that.

**Comment by keithf4** [comment]
Sorry, didn't get this fix into 2.6.4. I'm working on 3.0.0 and the fix will be in that one.

**Comment by keithf4** [comment]
v3.01 has been released and fixed this issue. Thanks again!

**Comment by lexferro** [comment]
Thanks to you!
Great Work!

2017-04-10 21:20 GMT+02:00 Keith Fiske <notifications@github.com>:
