### ISSUE TITLE
Edge case experienced

### ISSUE THREAD

**Issue by BobSherer** [keithf4/pg_partman#160]
Keith,

My co-worker built up a new development server with postgres 9.6.
I installed the latest pg_partman (as of 1/23) to the server, using make NO_BGW=1 install.
Dumped the non-partman schema objects from our 9.2 postgres server
Created the database on the new server, 
Ran the following successfully:
  CREATE SCHEMA partman;
  CREATE EXTENSION pg_partman SCHEMA partman;
Restored the schema to the new server.
And, tried the following ... with the subsequent error result:

`SELECT partman.create_parent('public.cins_all', 'alert_ts', 'time', 'monthly', p_premake := 6);
ERROR:  No child tables created. Unexpected edge case encountered. Please report this error to author with conditions that led to it.
CONTEXT: PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,boolean,text,boolean,text,text,boolean,boolean,boolean) line 348 at RAISE
DETAIL: 
HINT: 
CONTEXT:  PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,boolean,text,boolean,text,text,boolean,boolean,boolean) line 527 at RAISE`

Here is the part_config output from the old server:
> select * from partman.part_config ;
>          parent_table         |    type     | part_interval |  control   | constraint_cols | premake | inherit_fk | retention | retention_schema | retention_keep_table | retention_keep_index | datetime_string |            last_partition             | use_run_maintenance | jobmon | undo_in_progress 
> ------------------------------+-------------+---------------+------------+-----------------+---------+------------+-----------+------------------+----------------------+----------------------+-----------------+---------------------------------------+---------------------+--------+------------------
>  public.cins_all              | time-static | 1 mon         | alert_ts   |                 |       6 | t          |           |                  | t                    | t                    | YYYY_MM         | public.cins_all_p2017_07              | t                   | t      | f

I didn't think upgrading was really an option. So ... help! What other info do you need? Or, what did I do wrong in the create_parent or earlier?

And, we could start over with postgres 9.5 if that would help. But, I'm assuming we might hit a similar wall if we did that.

Thank you,
Bob

**Comment by keithf4** [comment]
I've actually encountered that edge case myself in development work and updated that error message for future versions. Make sure none of the child tables for that partition set exist already before you try partitioning the parent.

**Comment by keithf4** [comment]
If you're just experimenting with upgrading postgresql, you shouldn't have to recreate any partition sets. Config data should be preserved along with the partition sets themselves.

**Comment by BobSherer** [comment]
When I restore the data, the data will be in the child tables already. (We are restoring data from 2015 and 2016 to this server.) I figured I would have to run create_parent to build the part_config record using the new layout, so the server is ready in case we start sending over current data and cross into new months. (I do intend to have cron keep up with that.)

I guess I can drop the child tables, run create_parent, and then make sure all of the older child tables are built before I restore the data. Is that correct?

**Comment by keithf4** [comment]
You should just be able to do a dump/restore from your old database to the new one. As long as you've installed the pg_partman extension files, the restore will install the pg_partman extension first and then populate the config data into it. 

If that doesn't work, please show me the steps you took so I can recreate the issue.

**Comment by BobSherer** [comment]
There is still a problem.
I dropped and recreated my database on the 9.6 server.
I took a schema only backup from the 9.2 server and ran it on 9.6.
Dumped data only from 9.2.
Restored it on 9.6 and the first table it tried to load was partman.part_config, which threw an error due to no type column in the 9.6 part_config table.

`--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = partman, pg_catalog;

--
-- Data for Name: part_config; Type: TABLE DATA; Schema: partman; Owner: cins
--

COPY part_config (parent_table, type, part_interval, control, constraint_cols, premake, inherit_fk, retention, retention_schema, retention_keep_table, retention_keep_index, datetime_string, last_partition, use_run_maintenance, jobmon, undo_in_progress) FROM stdin;
public.cins_all time-static     1 mon   alert_ts        \N      6       t       \N      \N      t       t       YYYY_MM public.cins_all_p2017_07        t       t       f
public.cins_ip_alert_summary    time-static     1 mon   summary_ts      \N      6       t       \N      \N      t       t       YYYY_MM public.cins_ip_alert_summary_p2017_07   t       t       f
\.

`

Resulting error:
'# psql -U cins -f /home/Bob/bstest.sql 
SET
SET
SET
SET
SET
SET
psql:/home/Bob/bstest.sql:17: ERROR:  column "type" of relation "part_config" does not exist
psql:/home/Bob/bstest.sql:18: invalid command \N
psql:/home/Bob/bstest.sql:19: invalid command \N
psql:/home/Bob/bstest.sql:20: invalid command \.
psql:/home/Bob/bstest.sql:22: ERROR:  syntax error at or near "public"
LINE 1: public.cins_all time-static     1 mon   alert_ts        
        ^
'

Let me know if you need any more details. And, thank you for your awesome response times and this great partitioning tool.

Bob

**Comment by keithf4** [comment]
You've got the latest pg_partman package installed on 9.6 but you're trying to restore a dump that has an older version installed. Two options:

- Upgrade pg_partman to the latest version on your original system first. Then do the dump/restore.

- Download the exact version of pg_partman you have installed on the old system to the new one. You can find all versions here: https://github.com/keithf4/pg_partman/releases Run the make/install for that one so the files the dump restore uses are the same. Do not run CREATE EXTENSION yourself. A restore simply runs `CREATE EXTENSION ...` itself. It does not recreate individual extension objects. Then upgrade your new system to the latest pg_partman.

**Comment by BobSherer** [comment]
That makes sense. Thank you!
