### ISSUE TITLE
Incredibly useful create_partition_time is undocumented

### ISSUE THREAD

**Issue by kkartaltepe** [keithf4/pg_partman#161]
Very useful for creating partitions (correctly) prior to loading historic data. 

There is no other way to create past partitions besides just dumping data into the parent table and calling the documented `partition_data_time` function. However this leads to the case of needing enough spare disk space for twice as much data as you loading (to store it in the parent, then store it in the children, then finally vacuum full the parent) or a dance of loading just enough data, calling `partition_data_time`, loading some more, wash, rinse, repeat.

**Comment by keithf4** [comment]
I hadn't even thought about that! I'll see if I can adjust the documentation and make a note of it.

Thanks!

**Comment by keithf4** [comment]
v3.01 has been released and has this added to the documentation along with the create_function_*() functions as well. Thanks!
