### ISSUE TITLE
UPSERT DO NOTHING throws an exception.

### ISSUE THREAD

**Issue by Freyr666** [keithf4/pg_partman#162]
Hi there. I have a table, partitioned by time column, which has unique constrain. Sometimes dublicate values appear, one in parent table and one in child partition. So when i call partman.partition_data_time it throws an exception:

Parent table is created with p_upsert := 'ON CONFLICT (time) DO NOTHING'

```
ERROR:  duplicate key value violates unique constraint "table_p2017_01_time_key"
DETAIL:  Key (time)=(2017-01-26 15:07:43) already exists.
CONTEXT:  SQL statement "WITH partition_data AS (
                        DELETE FROM ONLY public.table WHERE time >= '2017-01-01 00:00:00+03' AND time < '2017-02-01 00:00:00+03' RETURNING *)
                     INSERT INTO public.table_p2017_01 SELECT * FROM partition_data"
PL/pgSQL function partman.partition_data_time(text,integer,interval,numeric,text,boolean) line 181 at EXECUTE
```

I want values to move into child tables when they are unique and to be deleted if they are already in the child table. What should i do? 

Though
```
WITH partition_data AS (DELETE FROM ONLY public.table WHERE time >= '2017-01-01 00:00:00+03' AND time < '2017-02-01 00:00:00+03' RETURNING *)
INSERT INTO public.table_p2017_01 SELECT * FROM partition_data ON CONFLICT (time) DO NOTHING;
```
works fine, it seems that `partman.partition_data_time` does not even use ON CONFLICT statement. What is wrong with that?

I use pg_partman95.x86_64 version 2.6.2-1.f24 for postgres 9.5 from yum postgres repo on fedora 24.

Thanx.

**Comment by keithf4** [comment]
Yeah, I don't have UPSERT set up in the partitioning function and I'm not really sure there's an easy way to do this in a general case. I have no way to really account for data going to both the child and parent if there is a valid child for the data to go to. That is a situation that should not be happening.

For now, I'd suggest just doing the data move manually as you did in your second statement. If this is going to be an ongoing issue, I'd question how you're getting data both into the child and the parent if your conflict column is the same as the partitioning column and try to solve that.

**Comment by Freyr666** [comment]
Ok, another question if you please. 

I've noticed that if the p_upsert arg is set then data be inserted only in child tables. If the p_upsert is not set it seems that data is inserted in parent table and then is moved to the child table, so if i push data twice so the same records are going to exist in both child and parent tables which leads to such troubles. Is that kind of behaviour intended?

**Comment by keithf4** [comment]
The trigger on the parent table reroutes data immediately to the target table, it does not insert there then move it. If you insert the same data twice, and you have a unique constraint, you should get a conflict error on the child table (unless you have UPSERT turned on to handle it). If you don't have a constraint, your data will be duplicated in the child (or kept in the parent if the child is removed in the mean time). The only time data should be going into the parent table is when the child table for that data does not exist. 

Do keep in mind that constraints are not enforced across an entire partition set. They are only enforced per child table and only on the parent. This is a limitation of Postgres itself and there's not much that can be done about it at this time without some pretty severe performance implications.

If you could give me something where I could reproduce what you're seeing, I could try to investigate what the problem could be.

**Comment by Freyr666** [comment]
>If you don't have a constraint

Well, in that particular case i had unique constraint.

However,  what if i have several columns, combination of which should be unique? For example i have `key, time`, i want to have a unique combinations of key and time, unique constraint for the time column is not enough. I use `PRIMARY KEY(key,time))` which works as unique constraint for a tuple of keys AFAIK. Is this ok for time partitioning?

**Comment by keithf4** [comment]
You can have whichever constraint you want. It still will only be enforced per-table and not for the entire partition set. And that should still not cause data to go into the parent.

**Comment by Freyr666** [comment]
>You can have whichever constraint you want. It still will only be enforced per-table and not for the entire partition set. And that should still not cause data to go into the parent.

Ok, so i have a table

```
  CREATE TABLE IF NOT EXISTS table
(priority     INTEGER,
 err_code     INTEGER,
 err_ext      INTEGER,
 errors_cnt   INTEGER,
 pid          INTEGER,
 multipid     BOOLEAN,
 param_1      INTEGER,
 param_2      INTEGER,
 time         TIMESTAMP,
 PRIMARY KEY(priority,err_code,err_ext,time))
```

i've enabled partman

```
SELECT * FROM partman.create_parent((SELECT current_schema) || '.' || table, 'time', 'time', 'monthly')
```

but 

```
INSERT INTO table
(priority,err_code,err_ext,errors_cnt,pid,multipid,param_1,param_2,time)
VALUES (1,21,51,30,2090,'0',6,133162,'2017-1-31 15:29:19.000000 +3:0:0'),(2,35,52,184,2011,'0',531,0,'2017-1-31 15:29:19.000000 +3:0:0');
```

writes values to the parent partition, not to the `table_p2017_01`

when i have a unique constraint on time it seems to be working, but in that particular case it requires `SELECT * FROM partman.partition_data_time((SELECT current_schema) || '.table');` call to move entries from parent table to child.

**Comment by keithf4** [comment]
Had to adjust some things in your commands to account for your tablename being a keyword. Also your create_parent table statement requires single quotes around the parent table name as well. But all appears to be working properly as far as I can see running version 2.6.3
```
keith@keith=# \dx
                                   List of installed extensions
    Name    | Version |   Schema   |                         Description                          
------------+---------+------------+--------------------------------------------------------------
 dblink     | 1.2     | public     | connect to other PostgreSQL databases from within a database
 pg_cron    | 1.0     | public     | Job scheduler for PostgreSQL
 pg_jobmon  | 1.3.3   | jobmon     | Extension for logging and monitoring functions in PostgreSQL
 pg_partman | 2.6.3   | partman    | Extension to manage partitioned tables by time or ID
 pgtap      | 0.98.0  | public     | Unit testing for PostgreSQL
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
(6 rows)


keith@keith=# CREATE TABLE IF NOT EXISTS "table"                                                                      
keith-# (priority     INTEGER,
keith(#  err_code     INTEGER,
keith(#  err_ext      INTEGER,
keith(#  errors_cnt   INTEGER,
keith(#  pid          INTEGER,
keith(#  multipid     BOOLEAN,
keith(#  param_1      INTEGER,
keith(#  param_2      INTEGER,
keith(#  time         TIMESTAMP,
keith(#  PRIMARY KEY(priority,err_code,err_ext,time));
CREATE TABLE
Time: 46.030 ms
keith@keith=# \d+ table
                                    Table "public.table"
   Column   |            Type             | Modifiers | Storage | Stats target | Description 
------------+-----------------------------+-----------+---------+--------------+-------------
 priority   | integer                     | not null  | plain   |              | 
 err_code   | integer                     | not null  | plain   |              | 
 err_ext    | integer                     | not null  | plain   |              | 
 errors_cnt | integer                     |           | plain   |              | 
 pid        | integer                     |           | plain   |              | 
 multipid   | boolean                     |           | plain   |              | 
 param_1    | integer                     |           | plain   |              | 
 param_2    | integer                     |           | plain   |              | 
 time       | timestamp without time zone | not null  | plain   |              | 
Indexes:
    "table_pkey" PRIMARY KEY, btree (priority, err_code, err_ext, "time")


keith@keith=# SELECT * FROM partman.create_parent((SELECT current_schema) || '.' || 'table', 'time', 'time', 'monthly');
 create_parent 
---------------
 t
(1 row)

Time: 490.452 ms

keith@keith=# \d+ table
                                    Table "public.table"
   Column   |            Type             | Modifiers | Storage | Stats target | Description 
------------+-----------------------------+-----------+---------+--------------+-------------
 priority   | integer                     | not null  | plain   |              | 
 err_code   | integer                     | not null  | plain   |              | 
 err_ext    | integer                     | not null  | plain   |              | 
 errors_cnt | integer                     |           | plain   |              | 
 pid        | integer                     |           | plain   |              | 
 multipid   | boolean                     |           | plain   |              | 
 param_1    | integer                     |           | plain   |              | 
 param_2    | integer                     |           | plain   |              | 
 time       | timestamp without time zone | not null  | plain   |              | 
Indexes:
    "table_pkey" PRIMARY KEY, btree (priority, err_code, err_ext, "time")
Triggers:
    table_part_trig BEFORE INSERT ON "table" FOR EACH ROW EXECUTE PROCEDURE table_part_trig_func()
Child tables: table_p2016_10,
              table_p2016_11,
              table_p2016_12,
              table_p2017_01,
              table_p2017_02,
              table_p2017_03,
              table_p2017_04,
              table_p2017_05,
              table_p2017_06


keith@keith=# INSERT INTO "table"
(priority,err_code,err_ext,errors_cnt,pid,multipid,param_1,param_2,time)
VALUES (1,21,51,30,2090,'0',6,133162,'2017-1-31 15:29:19.000000 +3:0:0'),(2,35,52,184,2011,'0',531,0,'2017-1-31 15:29:19.000000 +3:0:0');
INSERT 0 0
Time: 6.337 ms
keith@keith=# select * from "table";
 priority | err_code | err_ext | errors_cnt | pid  | multipid | param_1 | param_2 |        time         
----------+----------+---------+------------+------+----------+---------+---------+---------------------
        1 |       21 |      51 |         30 | 2090 | f        |       6 |  133162 | 2017-01-31 15:29:19
        2 |       35 |      52 |        184 | 2011 | f        |     531 |       0 | 2017-01-31 15:29:19
(2 rows)

Time: 3.654 ms
keith@keith=# select * from only "table";
 priority | err_code | err_ext | errors_cnt | pid | multipid | param_1 | param_2 | time 
----------+----------+---------+------------+-----+----------+---------+---------+------
(0 rows)

Time: 2.044 ms
keith@keith=# select * from "table_p2017_01";
 priority | err_code | err_ext | errors_cnt | pid  | multipid | param_1 | param_2 |        time         
----------+----------+---------+------------+------+----------+---------+---------+---------------------
        1 |       21 |      51 |         30 | 2090 | f        |       6 |  133162 | 2017-01-31 15:29:19
        2 |       35 |      52 |        184 | 2011 | f        |     531 |       0 | 2017-01-31 15:29:19
(2 rows)

Time: 2.009 ms

```

**Comment by Freyr666** [comment]
Cool, that works. Now i'm really confused about why it does not work in production.

I've noticed that newly created tables works, but after some time the problem appear.

I've created new table. It works. But the old table from which i've taken the example does not work. Both tables have the same preferences.But i've noticed that now any entries are being written in the parent table in the case of broken table. How could this be happening?

**Comment by keithf4** [comment]
If the trigger hasn't been altered, the only thing that should cause data to go to the parent would be if the child table is missing. Unless you added something odd to the INSERT ... ON CONFLICT clause? I can't account for all possible cases that could be entered there.

Try comparing the trigger function source on production to a newly created one. Also, are the pg_partman versions the same? Could've possibly been a bug fix.

**Comment by Freyr666** [comment]
One more question if you please. Should i call partition_data_time function manually if i have jobmon enabled? Would bgm automatically create child partitions for me?

**Comment by keithf4** [comment]
`partition_data_time` is only used for moving data out of the parent table into the children. So it's not something that should normally be called very often. If called, it will create the child table if necessary.

The function you're looking for is `run_maintenance`. That is what creates new partitions. If you have the background worker enabled, that function is run for you automatically as long as the proper configuration values are set in the postgresql.conf.

**Comment by keithf4** [comment]
And since you mentioned it, pg_jobmon is just for logging and monitoring partition maintenance. It does not run anything for you, it only logs what something else runs (in this case pg_partman) and provides a means for you to make sure it's running without any issues.

**Comment by Freyr666** [comment]
>is only used for moving data out of the parent table into the children.

But the data should be rerouted to the children table by the trigger, so there is no reason to call `partition_data_time` at all, right?

**Comment by keithf4** [comment]
The function exists for initially setting up partitioning on an existing table with data. It's also there just in case data does get put into the parent for some reason (someone inserts data that has no existing child table).

Once everything is set up and all data is moved to the children, there should be no need to call it further, correct.
