### ISSUE TITLE
partitioning trigger returning new or new.column in all cases

### ISSUE THREAD

**Issue by herwigg** [keithf4/pg_partman#163]
I was wondering whether the trigger that is created on the partitioned table and maintained by run_maintenance could always return NEW instead of return NULL as is now the case. The reason for asking is that we have a JAVA application on top of PG and it expects tables that are defined with a serial column to return a "natively generated identity value" However the trigger funcion returns null and return currval('sequence name') does not work, return new DOES work and new.id ( id is the name of the column that has the  auto generated sequence value) contains the currval of the just inserted id. I have adapted the trigger function to test this, but as you know, run_maintenance dynamically re-generates this trigger so my changes get lost. Is there a way to implement this or to add it to your code ? Thank you btw for implementing partitioning.

**Comment by keithf4** [comment]
Version 2.6.0 has this feature as a configuration option in the `part_config` table as well as a parameter to `create_parent()`. See the documentation for `create_parent()` for an explanation of how this works and how you must then handle data not going to both the child and the parent.

**Comment by herwigg** [comment]
Thank you for your answer. It is great that it exists, The manual says: " You are then responsible for handling the return value in another trigger appropriately. Otherwise, this will cause new data to go into both the child and parent table of the partition set." Do you have any example that could clarify this. I do not know how to write such a trigger: an instead of trigger on the master table or ... Any helpmor hints would be greatly appreciated. btw it is exactly what happens for the time being, I have implemented the flag and the record gets inserted twice.

**Comment by keithf4** [comment]
Don't have any working examples since this isn't a feature I actually use myself. Easiest thing would be to have your trigger return NULL after it does what you need it to do.

Also just be extra careful in the order that your triggers fire. They currently run alphabetically, so name them accordingly so the one that returns NULL runs last.

**Comment by herwigg** [comment]
I have been able to resolve this issue with info in this link: http://stackoverflow.com/questions/83093/hibernate-insert-batch-with-partitioned-postgresql
Thanks very much for the help, much appreciated.

**Comment by keithf4** [comment]
Curious which of those solutions you went with. The double-trigger and RULE method both have caveats that need to be dealt with that are not mentioned in that post.

**Comment by herwigg** [comment]
Ok,

It still is in develoment env. I might add that we  never update the table,
it is a logging table but is rarely used and mainly for reporting purposes
but not really operational data. So basically insert and select and data >3
months old archived to csv.
Ok, what I did was to create a view select * from the 'master' partitioned
table.
A rule on  insert into the 'master' partitioned table to do instead an
insert in the view.
An on insert on each row trigger on the view that executes
the xts_action_log_part_trig_func(). The latter is the trigger that is
maintained automatically by the partman extension.
Here is the code:
create or replace view xts_action_log_view as select * from xts_action_log;
-- create trivial wrapping view

create RULE xts_action_log_rule AS
      ON INSERT TO xts_action_log
      DO INSTEAD insert into xts_action_log_view VALUES (NEW.*);

CREATE TRIGGER xts_action_log_view_trigger
   INSTEAD OF INSERT ON xts_action_log_view
   FOR EACH ROW EXECUTE PROCEDURE xts_action_log_part_trig_func();
I just tried it out and it worked, but I did not test it thoroughly yet.
Let us hope with native partitioning in Postgres 10 that it works in
completely transparant (and maintenance free) manner.

Kind regards,
Herwig

2017-02-02 16:04 GMT+01:00 Keith Fiske <notifications@github.com>:

**Comment by keithf4** [comment]
Ok. That should work fine. I'd debated adding that sort of view option to pg_partman, but had never gotten around to testing it. With 10 coming out, I likely won't anymore.

PostgreSQL 10 makes this much, much easier. The RETURNING clause works and it also reports back the number of rows affected. I gave an example in another similar question recently: https://github.com/keithf4/pg_partman/issues/164
