### ISSUE TITLE
insert trigger with return id

### ISSUE THREAD

**Issue by demeenta** [keithf4/pg_partman#164]
I think that to resolve this issue there is to add to (only) all first INSERT in the trigger (part_trig_func): return NEW, this works in test for me for now.....

For example:
```
        ELSIF NEW.var_id >= 0 AND NEW.id < 100 THEN 
            INSERT INTO public.data_p0 VALUES (NEW.*); RETURN NEW; 
        ELSIF NEW.var_id >= 200 AND NEW.id < 300 THEN 
            INSERT INTO public.data_p200 VALUES (NEW.*) ; RETURN NEW;
        ELSIF NEW.var_id >= 300 AND NEW.id < 400 THEN 
            INSERT INTO public.data_p300 VALUES (NEW.*) ; RETURN NEW;
```
I tried with insert only and for now I added this change manually.
I not sure really, I'm wrong?

**Comment by keithf4** [comment]
The RETURNING clause does not work because if you RETURN NEW in the partition trigger, then data will insert to both the child and the parent table. There is unfortunately no simple way around this at this time. 

However, native partitioning in PostgreSQL 10 does solve this problem! Here you can see that it works with some testing that I've been doing lately
```
keith@keith=# select version();
                                                      version                                                      
-------------------------------------------------------------------------------------------------------------------
 PostgreSQL 10devel on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit
(1 row)

Time: 0.463 ms

keith@keith=# \d+ partman_test.time_taptest_table
                                  Table "partman_test.time_taptest_table"
 Column |           Type           | Collation | Nullable | Default | Storage  | Stats target | Description 
--------+--------------------------+-----------+----------+---------+----------+--------------+-------------
 col1   | integer                  |           |          |         | plain    |              | 
 col2   | text                     |           |          |         | extended |              | 
 col3   | timestamp with time zone |           | not null | now()   | plain    |              | 
Partition key: RANGE (col3)
Partitions: partman_test.time_taptest_table_p2015 FOR VALUES FROM ('2015-01-01 00:00:00-05') TO ('2016-01-01 00:00:00-05'),
            partman_test.time_taptest_table_p2016 FOR VALUES FROM ('2016-01-01 00:00:00-05') TO ('2017-01-01 00:00:00-05'),
            partman_test.time_taptest_table_p2017 FOR VALUES FROM ('2017-01-01 00:00:00-05') TO ('2018-01-01 00:00:00-05'),
            partman_test.time_taptest_table_p2018 FOR VALUES FROM ('2018-01-01 00:00:00-05') TO ('2019-01-01 00:00:00-05'),
            partman_test.time_taptest_table_p2019 FOR VALUES FROM ('2019-01-01 00:00:00-05') TO ('2020-01-01 00:00:00-05'),
            partman_test.time_taptest_table_p2020 FOR VALUES FROM ('2020-01-01 00:00:00-05') TO ('2021-01-01 00:00:00-05')

keith@keith=# INSERT INTO partman_test.time_taptest_table values (1, 'stuff', now()) returning col1;
 col1 
------
    1
(1 row)

INSERT 0 1
```

**Comment by topwik** [comment]
interesting. i've got a docker image running postgres 10: PostgreSQL 10.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18) 6.3.0 20170516, 64-bit

using pg_partman 3.2.1: NOTICE: version "3.2.1" of extension "pg_partman" is already installed

i created some tables and thought that recent version of pg_partman would work nicely with postgres10. however, i don't get a row back via insert returning out of the box....

**Comment by keithf4** [comment]
Make sure you are creating a natively partitioned table, not a trigger-based one. RETURNING will only work with native partitioning, even in PG10+

**Comment by topwik** [comment]
so i can still use pg_partman but the table create must use the postgres partition by keyword, is that correct? i read even with pg10 partitioning, that pg_partman is still a helpful tool for running the maintenance on partitions i am assume....

**Comment by keithf4** [comment]
Correct, you have to define the parent table as being natively partitioned first and then run create_parent() on it with the partition_type being "native". And yes, you still need something to create new partitions over time for you with native, so pg_partman is still useful there.

**Comment by topwik** [comment]
right on, sounds cool. thanks the insights.

**Comment by topwik** [comment]
@keithf4  are you able to point me to any resource that could help me with managing indexes on child tables using pg_partman with postgres10 native partitioning? i can't create the index on the parent table but there seems to be a way to leverage a template table that partman would use to pass on indexes to child tables? I can't seem to find any details on how to specify the template. cheers,

**Comment by keithf4** [comment]
A template table is automatically created for you in the schema that the pg_partman extension is installed to. Note that indexes you create on that default template after the partition set is already set up won't be automatically added to the child tables that already exist.

You can also provide a pre-created template table with your desired indexes & FKs as a parameter to the `create_parent()` function. 

You can see what the template table is for a partition set by looking at the `part_config` table entry for that partition set. You can also add or change the template table at any time by updating that column.

See the docs for the function parameter and table config info.

Note that only PG10 requires that you create all indexes and foreign keys on the template table. For PG11, only unique indexes and primary keys that don't include the partition key require the template table. Regular indexes and FKs can be created on the parent table in PG11. I would highly recommend upgrading to PG11 soon just to make partition management easier.
