### ISSUE TITLE
Remove doc about incompatibility with Postgres 9.6

### ISSUE THREAD

**Issue by tbeadle** [keithf4/pg_partman#166]
At https://github.com/keithf4/pg_partman#installation, it says:

Requirement: PostgreSQL 9.4 & 9.5 (currently incompatible with 9.6)

but this is apparently not the case any more with v2.6.3, which I am so happy about.  Thank you for fixing that incompatibility!

**Comment by keithf4** [comment]
Woops! Thanks!

**Comment by tbeadle** [comment]
Wow, that was quick, but don't you want it to say:
"Requirement: PostgreSQL 9.4, 9.5, or 9.6"

**Comment by keithf4** [comment]
Yeah. I'll get it fixed better next release. Mostly wanted to get that incompatibility warning removed.
