### ISSUE TITLE
maintenance job recreating subpartitions after subpartitioning undone 

### ISSUE THREAD

**Issue by francoisbeaulieu** [keithf4/pg_partman#168]
Hi,

Running pg_partman 2.6.4 on pgsql 9.4

I removed my subpartitioning scheme using undo_partition.py After completed, I checked partman.part_config and only the parent tables were listed there. Now, I see that some subpartitions have been recreated and checking jobmon.job_detail indicates that it's the maintenance loop that did it. I'm not sure how to go about determining why.

**Comment by keithf4** [comment]
Can you provide the config dump and schema for the tables involved?

**Comment by francoisbeaulieu** [comment]
It's been making them once a week for 2 weeks. (I believe the maintenance job is set to run weekly as well). It only creates a single subpartition in the last partition in creates for each table. It also happens on my prod box, which is running pg_partman 1.8.6, so I assume it has somthing to do with my specific combination of options for the partitioning scheme, or with the way I ran undo_partition.py.

If you look at my dump of partman.part_config in ticket #167 you'll see that the subpartition was not there last week; it's from the same DB instance.

As requested: 
[subpartbug_168.zip](https://github.com/keithf4/pg_partman/files/812274/subpartbug_168.zip)

**Comment by keithf4** [comment]
Ahh I see the problem. I don't ever remove the entry from the `part_config_sub` table as part of the undo process. Just delete the entry from there and the sub partitions should stop being created.

I'll work on a fix for this for the next version. Thanks for helping debug the issue!

**Comment by keithf4** [comment]
v3.01 has been released and fixed this issue. It also contains quite a lot of other changes, so please review the CHANGELOG before upgrading. Thanks!
