### ISSUE TITLE
How to update existing partition trigger to return NEW instead of NULL?

### ISSUE THREAD

**Issue by broseed** [keithf4/pg_partman#170]
I have an existing partition set created by pg_partman which is currently set to return NULL (the default).  How can I update the existing trigger to instead return NEW so other triggers on the table can run (understanding they will have to prevent entries going into the master and child tables)?

I understand how to make this happen via the create_parent function on a new partition, but this question is updating an already-existing partition set.

Thanks,
Dylan

**Comment by keithf4** [comment]
Set the config value in `part_confg` (and `part_config_sub` if necessary). Then you can wait until the next partition is created, which will update the trigger function. 
Or you can run `create_function_id('parent_table')` or `create_function_time('parent_table')` manually to force the trigger function to update immediately.

**Comment by broseed** [comment]
Perfect - thank you!
