### ISSUE TITLE
Is there an easy way to rename a pg_partman managed/partitioned table?

### ISSUE THREAD

**Issue by kayvonr** [keithf4/pg_partman#172]
Hey there - we are very big fans of the extension! So, say we have a table `foo` with columns `key1, value1` with time-based partitioning. Now, we want to add a column in the middle of foo (e.g. `key2` after column `key1`). Given the amount of data we have in the table and the number of columns (more than 2, trimmed down for the example), it's easiest normally to create a new table `foo_new` with columns `key1, key2, value1`, dump all the data in there, and then swap table names. however, the issue of the triggers, functions, and sub-table names gets in the way there. 

searching for ways to rename in the partman docs led me to the migration guide [here](https://github.com/keithf4/pg_partman/blob/master/doc/migration.md). After reading, it seems like the easiest way to swap table names is to delete all the triggers from old table and new table, rename all the sub-tables appropriately (`foo` becomes `foo_old`, `foo_p2017_03_13` becomes `foo_old_p2017_03_13`, etc...) , and then re-run `create_parent()` to re-generate the triggers and such. is this the best/recommended way? or is there a built-in way in partman to rename a table and update everything related to it (triggers, insert function, sub-tables, etc...)? 

Thanks so much!

**Comment by keithf4** [comment]
The steps in your second paragraph honestly seem the best way. I believe that create_parent() should handle the child tables already existing and just avoid trying to make them again. If not, may have to rethink this strategy.

Another thing to be aware of is that the code generated in the trigger function itself has its child table names based on what the parent table's name is, so as long as the parent and child table names are consistent with each other, the trigger function that is created should be fine. Recommend just checking over the trigger function code to make sure it's naming the tables properly.

Either way, if it works or not, please let me know. Steps used here may be useful when trying to work out a migration plan for Postgres 10 and getting a table migrated to a native partition set.

**Comment by kayvonr** [comment]
Great ok, thanks for the quick reply. Will test out this week and update here with results

**Comment by kayvonr** [comment]
so, that all worked fine, with an error at one point of: "No child tables created. Unexpected edge case encountered. Please report this error to author with conditions that led to it.", which I figured out how to fix.

Here's what I did, swapping `foo` and `foo_new`:

- for both tables, drop the partman trigger as well as the actual insert function
- rename `foo` to `foo_old` & rename its child tables from `foo_p2017...` to `foo_old_p2017...`
- same thing for `foo_new` except renamed to `foo`
- renamed the entries for `foo` and `foo_new` in partman.part_config table to `foo_backup`, so I could reference the settings when re-creating the partman entry after the swap.
- ran `partman.create_parent` for `foo`, which is now the new table. Here is where I encountered that exception. It seems as though in sql/functions/create_parent.sql:368 `create_parent` will fail if it can't create any child partitions at all (is my understanding there correct?), in my case because they all already existed. since we premake far ahead, i just dropped the newest partition and then re-ran `create_parent`. It now had at least one table to create and completed successfully

and everything seems to be working fine.

**Comment by keithf4** [comment]
Thanks for that! Yeah, I've since realized that error occurs when there are already child tables existing for a table given to create_parent(). I'll see about changing the error message given and stop if from raising a full exception that stops it running and just give a warning.
