### ISSUE TITLE
new partitions not created if no data inserted

### ISSUE THREAD

**Issue by ultimoamore** [keithf4/pg_partman#175]
I'm using pg_partman to partition data in zabbix. Everything works fine for tables that zabbix writes to, while partitions for tables that are empty (but might be written if zabbix config changes) are not created:

 public | history_log                | table    | zabbix
 public | history_log_p2017_03_31    | table    | zabbix
 public | history_log_p2017_04_01    | table    | zabbix
 public | history_p2017_03_31        | table    | zabbix
 public | history_p2017_04_01        | table    | zabbix
 public | history_p2017_04_02        | table    | zabbix
 public | history_p2017_04_03        | table    | zabbix
 public | history_p2017_04_04        | table    | zabbix
 public | history_p2017_04_05        | table    | zabbix
 public | history_p2017_04_06        | table    | zabbix
 public | history_p2017_04_07        | table    | zabbix

For example, the history_log partitions were created some days ago. After the creation I had 8 history_log_p* tables; now the scheduler is removing the old ones (which is expected) but not creating the new ones. history_p* tables instead seems fine; the only difference I can find is that history_log tables are empty (zabbix is not writing any data to it, which at the moment is ok) while history_p* tables are written to. The config seems the same for both.

**Comment by keithf4** [comment]
This is the default behavior to keep needless partitions from being created on empty tables and also to be consistent with how serial partitioning works. If you need partitions to continue being created even with no data, look at setting `infinite_time_partitions`

**Comment by ultimoamore** [comment]
damn I didn't see that option!!! I updated the partman.part_config table, called run_maintenance and it worked, thank you very much.
