### ISSUE TITLE
Is current README up to date regarding 9.6 and the BGW?

### ISSUE THREAD

**Issue by tdraegen** [keithf4/pg_partman#178]
Right now the README says: WARNING: The pg_partman background worker is currently incompatible with PostgreSQL 9.6. It runs fine in 9.4 and 9.5. I'm still working on trying to figure out what the issue is.

However, v2.6.3 looks to have fixed compatibility with 9.6?

**Comment by keithf4** [comment]
Apologies, the README is not up to date on that. I expect to have the next version out next week and will have that note removed. Thanks!

**Comment by keithf4** [comment]
v3.0.1 is out and this warning has been removed. Thanks!
