### ISSUE TITLE
Postgres 10 native partitioning MAXVAL/MINVAL/overflow partition support?

### ISSUE THREAD

**Issue by kkartaltepe** [keithf4/pg_partman#179]
I'm not entirely sure how supportable this even is the current devel release of postgres 10, but will there be any chance to support a MAXVAL child which extends for whatever the current normal child interval is to the max insertable value. This would act as a kind of overflow table to support similar usage as the parent table in pg_partman style partitioning.

Its unfortunate native partitioning seems to have overlooked this imo critical feature but maybe there is something partman can do.

From what I can tell (from https://www.postgresql.org/docs/devel/static/ddl-partitioning.html#ddl-partitioning-declarative-maintenance ) the only way to support this would be to detach the overflow partition, create next child partition, migrate data, and then reattach the overflow table with new lower bound. There quite a few issues with this exact methodology but maybe there is a better way to do this or the partition devs will see this and be inspired :)

**Comment by keithf4** [comment]
The problem with the overflow partition is that it always has to be exclusive of other child tables. Native partitions cannot have overlapping constraints. So it needs a lower boundary, which will always keep changing as new child tables are added.

There is discussion of having a supported DEFAULT partition, but even then it still has limitations when you then want to move the data out of the child. A lot of this centers around needing a sort of global index support constraints across multiple tables.

For now, if you need to be able to account for data that doesn't fit in a child table, you'll have to use the old trigger based method.

**Comment by kkartaltepe** [comment]
I hadnt even heard about the discussion of DEFAULT when I was asking around. Nice to know there is talk about supporting this natively.

Just wanted to toss this out as an idea but its understandable to just leave it to pg_partman partitions.

**Comment by keithf4** [comment]
The current discussion and patch thread is here

https://www.postgresql.org/message-id/flat/CAH2L28tbN4SYyhS7YV1YBWcitkqbhSWfQCy0G%3DapRcC_PEO-bg%40mail.gmail.com#CAH2L28tbN4SYyhS7YV1YBWcitkqbhSWfQCy0G=apRcC_PEO-bg@mail.gmail.com
