### ISSUE TITLE
Server is version 9.6, library is version 9.4

### ISSUE THREAD

**Issue by camodor** [keithf4/pg_partman#185]
Hi!
I'm use postgresql 9.4 with pg_partman.
After pg_upgrade 9.4 -> 9.6  i reinstall pg_partman (1.make uninstall, 2.make install)
When i start postgresql, in logs
FATAL:  incompatible library "/usr/lib/postgresql/9.6/lib/pg_partman_bgw.so": version mismatch
DETAIL:  Server is version 9.6, library is version 9.4.
LOG:  database system is shut down.
What am I doing wrong?
best regards

**Comment by keithf4** [comment]
Sounds like you didn't rebuild pg_partman with the 9.6 binaries. Make sure the pg_config that's in your PATH when you run `make` is the one for 9.6. 

Or, if you don't need the C libraries for the background worker that runs automatic maintenance, remove pg_partman from the `shared_preload_libraries` in postgresql.conf.

**Comment by camodor** [comment]
gcc: error: /usr/share/dpkg/no-pie-compile.specs: No such file or directory
<builtin>: recipe for target 'src/pg_partman_bgw.o' failed
make: *** [src/pg_partman_bgw.o] Error 1
I'm uninstall pg_partman ( make uninstall)
Then git clone, and make.

**Comment by keithf4** [comment]
This sounds like a problem with your build environment and unfortunately I'm not sure what that could be. This builds fine for me on multiple platforms (many flavors of linux and also solaris).

This is the closet thing I could find googling around for what the issue may be

https://www.mail-archive.com/debian-dpkg-bugs@lists.debian.org/msg16535.html

**Comment by keithf4** [comment]
Also, try doing a `make clean` first to ensure you're rebuilding the new library.
