### ISSUE TITLE
mixing partman and sharding

### ISSUE THREAD

**Issue by DLqmap** [keithf4/pg_partman#186]
Hi,
we're exploring the possibility to mix pg_partman with pg_citus  (postgres extension for data sharding).
In our scenario we would have a table with monthly partitions manged by partman. 
Now, we would like each partition to be sharded across multiple db nodes. the creation/distribution of these shards with citus is possible by calling  some functions. In this scenario anyway we would have to manually check after run_maintenance executes and run the distribution function for each new partition created by partman. So I was looking if it's possible to hook custom code at the end of run_maintenance, and possibly get the list of newly created partitions. In case this is not possible (as I suspect) how would you achieve that?

**Comment by keithf4** [comment]
Yeah, there's not really any way to automatically know if maintenance makes a new partition from the maintenance run itself.. You could possibly use the show_partitions() function as a monitor for which partitions exist for a set, though, and if it changes, trigger your citus functions.

**Comment by ozgune** [comment]
@DLqmap / @onderkalaci -- I wanted to drop a *side note* in this issue about partitioning support in Citus. We're working on this feature for our 7.0 release; and we're looking at both pg_partman and partitioning improvements in PG 10.0.

If you could share a few details with us about your use-case in the related issue, that would help us with scoping the requirements for sharding + partitioning: https://github.com/citusdata/citus/issues/183

**Comment by keithf4** [comment]
Closing this issue here since this was fixed upstream in https://github.com/citusdata/citus/issues/183
```
As of Citus 7.2, pg_partman works on distributed tables with native PG10 partitioning.
```
