### ISSUE TITLE
`create_parent` Failing for PG 10 (Beta 1) Due to Version Number

### ISSUE THREAD

**Issue by lycovian** [keithf4/pg_partman#187]
Attempting to test the latest `master` checkout for pg_partman with the most recent PG 10 (beta 1).  Code installs correctly but fails to run during `partman.check_version(text)`:
```

mach=# alter extension pg_partman update to '3.0.1';
ALTER EXTENSION
mach=# create schema test;
CREATE SCHEMA
mach=# create table test.part_test(col1 serial, col2 text, col3 timestamptz not null default now());
CREATE TABLE
mach=# select partman.create_parent('test.part_test', 'col3', 'partman', 'daily');
ERROR:  invalid input syntax for integer: "10beta1"
CONTEXT: PL/pgSQL function partman.check_version(text) line 20 at IF
PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,boolean,boolean,boolean) line 142 at IF
DETAIL:
HINT:
CONTEXT:  PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,boolean,boolean,boolean) line 632 at RAISE
```

**Comment by keithf4** [comment]
I actually have a fix for this ready to go. Hopefully have 3.0.2 out this wee!

**Comment by onderkalaci** [comment]
Do you have any timeline for a stable release with `pg_10`?  Thanks!

**Comment by keithf4** [comment]
"Stable" with pg10 will be when pg10 is actually out. That's estimated for something in 4th quarter 2017. Anything could change and I'll be keeping an eye out for issues between now and then.

**Comment by keithf4** [comment]
Version 3.0.2 has been released with this fix. Should work fine in any pre-stable release from now on.
