### ISSUE TITLE
pg_partman 3.0 on yum.postgresql.org

### ISSUE THREAD

**Issue by dev1ant** [keithf4/pg_partman#188]
On apt.postgresql.org the only available now version is `3.0.1-1.pgdg14.04+1` while on yum.postgresql.org the newest is `2.6.2-1.rhel6`. Do you know who is building pg_partman for yum.postgresql.org?

**Comment by keithf4** [comment]
Please send a message to the yum repo mailing list (below). I'm not sure who is maintaining that package.

pgsql-pkg-yum@postgresql.org

**Comment by dev1ant** [comment]
https://www.postgresql.org/message-id/B9A8E153-9691-4A2E-BEE8-11408C30F592%40simply.name

**Comment by keithf4** [comment]
Thanks!
