### ISSUE TITLE
Do not allow last child table to be dropped in retention (Was: SELECT partman.run_maintenance(); is failing)

### ISSUE THREAD

**Issue by amikhile** [keithf4/pg_partman#189]
we have postgres 9.6.2 and partman 3.0.1
when run partman.run_maintenance() function executed we get an error

ERROR:  Child table given does not exist (<NULL>)
CONTEXT: PL/pgSQL function show_partition_info(text,text,text) line 38 at RAISE
SQL statement "SELECT child_start_time                                              FROM partman.show_partition_info(v_parent_schema||'.'||v_last_partition, v_row.partition_interval, v_row.parent_table)"
PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 157 at SQL statement
DETAIL: 
HINT: 
CONTEXT:  PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 358 at RAISE
********** Error **********

Where should we look for a problem?

**Comment by keithf4** [comment]
Can you give me some more details on your setup? What version of pg_partman? How many partition sets do you have set up? If it's not many, can you try running run_maintenance for each one individually to see which one may be the problem (you can pass the parent table name as a parameter to run_maintenance())

If you can narrow it down to a specific partition set, can you provide the part_config table entry (and part_config_sub if it's sub partitioned). Also provide the output of either \d+ in psql for that parent table or run show_partitions() for that partition set.

**Comment by amikhile** [comment]
We have 12 partition sets, All of them configured in the same manner.
We are not using BGW and run the run_maintenance() from our code.
Recently moved from postgres 9.4.2 and pg_partman 1.8.5 where no such issues were observed.
For testing purposes we set the retention to 2 days.
Some of the tables are partinioned well, and some are not. On this system currently problem with 4 tables out of 12.
Part_config is the same for all tables. No Sub partitioning.
here is an example of part_config row:
collector.page_metrics,	part_day,	partman,	1 day,	null,	3,	4,	30,	none,	t,	2 days,	null,	f,	t,	f,	YYYY_MM_DD,	on,	t,	f,	f,	f,		,t


For a table without problems:
avdb=# Select partman.show_partitions('collector.synthetic_transactions');
                show_partitions
------------------------------------------------
 (collector,synthetic_transactions_p2017_06_10)
 (collector,synthetic_transactions_p2017_06_11)
 (collector,synthetic_transactions_p2017_06_12)
 (collector,synthetic_transactions_p2017_06_13)
 (collector,synthetic_transactions_p2017_06_14)
 (collector,synthetic_transactions_p2017_06_15)
 
 
 For a table with problem:
 avdb=# Select partman.show_partitions('collector.synthetic_sla');
            show_partitions
---------------------------------------
 (collector,synthetic_sla_p2017_06_08)

 
 for executing: SELECT partman.run_maintenance('collector.synthetic_sla', true, false, true);
 output:
 
 ERROR:  Child table given does not exist (collector.synthetic_sla_p2017_06_08)
CONTEXT: PL/pgSQL function show_partition_info(text,text,text) line 38 at RAISE
SQL statement "SELECT child_start_time                                              FROM partman.show_partition_info(v_parent_schema||'.'||v_last_partition, v_row.partition_interval, v_row.parent_table)"
PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 157 at SQL statement
DETAIL: 
HINT: 
CONTEXT:  PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 358 at RAISE
********** Error ********** 

if i delete this one existing partition manually so there is no partitions left, then i get the error: ERROR:  Child table given does not exist (<\NULL\>) 



avdb=# \d+ collector.synthetic_sla;
                                   Table "collector.synthetic_sla"
         Column         |          Type          | Modifiers | Storage  | Stats target | Description
------------------------+------------------------+-----------+----------+--------------+-------------
 start_time             | bigint                 | not null  | plain    |              |
 end_time               | bigint                 | not null  | plain    |              |
 execution_plan_id      | bigint                 | not null  | plain    |              |
 agent_group_id         | bigint                 | not null  | plain    |              |
 transaction_name       | character varying(255) | not null  | extended |              |
 violation_performance  | integer                | not null  | plain    |              |
 violation_availability | integer                | not null  | plain    |              |
 violation_accuracy     | integer                | not null  | plain    |              |
 violation_execution    | integer                | not null  | plain    |              |
 good_executions        | integer                | not null  | plain    |              |
 total_executions       | integer                | not null  | plain    |              |
 part_day               | date                   | not null  | plain    |              |
Indexes:
    "synthetic_sla_pkey" PRIMARY KEY, btree (start_time, execution_plan_id, transaction_name, agent_group_id)
    "synthetic_sla_end_time_index" btree (end_time)
Triggers:
    aa_sync_part_day BEFORE INSERT ON collector.synthetic_sla FOR EACH ROW EXECUTE PROCEDURE collector.sync_part_day()
    synthetic_sla_part_trig BEFORE INSERT ON collector.synthetic_sla FOR EACH ROW EXECUTE PROCEDURE collector.synthetic_sla_part_trig_func()
Child tables: collector.synthetic_sla_p2017_06_08

**Comment by keithf4** [comment]
```
(collector,synthetic_sla_p2017_06_08)

for executing: SELECT partman.run_maintenance('collector.synthetic_sla', true, false, true);
output:

ERROR: Child table given does not exist (collector.synthetic_sla_p2017_06_08)
[...]
```
This error does not make any sense and doesn't match your original error (the child table name is null). Can you give me the part_config entry for it along with the \d+ from the parent table for it?

```
if i delete this one existing partition manually so there is no partitions left, then i get the error: ERROR: Child table given does not exist (<\NULL>)
```
All partition sets must have at least one child table with pg_partman. There is no way around this. If you're encountering this error and the partition set has no children, try removing its entry from the part_config table (grab a copy of it first for backup/reference) then repartitioning it.

If you have retention set to remove old tables but are not entering any new data, consider setting the `infinite_time_partitions` option so that it will still continue to create new time-based child tables even when no new data is being entered. I can't remember if I have retention set to never drop the last partition. If not, I'll see if I can fix that.

**Comment by amikhile** [comment]
> This error does not make any sense and doesn't match your original error (the child table name is null). Can you give me the part_config entry for it along with the \d+ from the parent table for it?

I will try to explain this more, what happened is that i got this error for page_metrics table 
`ERROR:Child table given does not exist (collector.page_metrics_p2017_06_08)`

so i thought that something is wrong with this parttition, and deleted it manually, then i have left only with parent page_metrics table and when i tried to run_maintenance again i got 
 `ERROR:  Child table given does not exist (<NULL>)


This is the part_config row:
collector.page_metrics,	part_day,	partman,	1 day,	null,	3,	4,	30,	none,	t,	2 days,	null,	f,	t,	f,	YYYY_MM_DD,	on, t,	f,	f,	f,	,t

`avdb=# \d+ collector.page_metrics;
                                     Table "collector.page_metrics"
           Column           |          Type          | Modifiers | Storage  | Stats target | Description
----------------------------+------------------------+-----------+----------+--------------+-------------
 start_time                 | bigint                 | not null  | plain    |              |
 duration                   | bigint                 | not null  | plain    |              |
 proxy_id                   | character varying(255) | not null  | extended |              |
 application_id             | character varying(255) | not null  | extended |              |
 page_id                    | character varying(255) | not null  | extended |              |
 page_count_sum             | bigint                 |           | plain    |              |
 page_good_count_sum        | bigint                 |           | plain    |              |
 page_latency_max           | bigint                 |           | plain    |              |
 page_latency_avg           | bigint                 |           | plain    |              |
 page_browser_latency_avg   | bigint                 |           | plain    |              |
 page_browser_count_sum     | bigint                 |           | plain    |              |
 page_network_latency_avg   | bigint                 |           | plain    |              |
 page_network_count_sum     | bigint                 |           | plain    |              |
 page_server_latency_avg    | bigint                 |           | plain    |              |
 page_server_count_sum      | bigint                 |           | plain    |              |
 page_latency_violation_sum | bigint                 |           | plain    |              |
 page_error_violation_sum   | bigint                 |           | plain    |              |
 part_day                   | date                   | not null  | plain    |              |
Indexes:
    "page_metrics_pkey" PRIMARY KEY, btree (start_time, proxy_id, application_id, page_id)
Triggers:
    aa_sync_part_day BEFORE INSERT ON collector.page_metrics FOR EACH ROW EXECUTE PROCEDURE collector.sync_part_day()
    page_metrics_part_trig BEFORE INSERT ON collector.page_metrics FOR EACH ROW EXECUTE PROCEDURE collector.page_metrics_part_trig_func()
`

`

When you say repartition? By using what function? this table is now empty
Lets focus on the error i have when there is still one partition available
`ERROR:Child table given does not exist (collector.page_metrics_p2017_06_08)`

What can be the cause for this?

**Comment by keithf4** [comment]
I believe the reason for the error you're getting is because the table involved (collector.page_metrics_p2017_06_08) is older than your retention period (2 days). As I mentioned above, it doesn't look like I'm accounting for the last child table being dropped if it's older than the retention period. I'll work on seeing if I can fix this. So what's happening here is that since that's the last child table left in the partition set, it's hitting a race condition in the run_maintenance() function's calling of show_partition_info() when that final partition is dropped. 

I'm curious why there are no partitions that exist between June 8th and now. You're down to a single partition left because retention has been pruning them. If that is due to there being no data inserted, then I highly recommend setting the `infinite_time_partitions` for any of the partition sets you have retention set and are not getting continuous data throughout the configured retention period. Without that set, even if I fix the above bug that's dropping the last child table, you'd instead run into data being inserted into the parent table (or insertion failure with native partitioning) since maintenance would not keep up with creating current child tables.

The easiest way to fix this situation would be to insert some current data (based on the part_day column) into the partition set. That would likely put data into the parent table. You can then run the partition_data function (either the plpgsql function or the python script). That will create the relevant child table(s) and move the data to them. Maintenance should work from that point forward as long as you either keep inserting current data or set the `infinite_time_partitions` flag in the config table.

**Comment by amikhile** [comment]
Thank you,

I will set the infinite_time_partitions to true ans see if this eliminate the issue for us.

**Comment by DLqmap** [comment]
adding more details as we're experiencing the same error hoping it could be useful for its resolution:

we're randomly (meaning maintenance on the table works for 2 weeks then suddenly starts failing) getting the following error:

2017-08-06 07:28:19.532 CEST [15400] LOG:  pg_partman dynamic background worker (dbname=gps_data) dynamic background worker initialized with role postgres on database gps_data
2017-08-06 07:28:19.634 CEST [15400] ERRORE:  Child table given does not exist (history.gps_paths_filtered_p2017_08_04)
        CONTEXT: funzione PL/pgSQL show_partition_info(text,text,text) riga 38 a RAISE
        istruzione SQL "SELECT child_start_time                                              FROM partman.show_partition_info(v_parent_schema||'.'||v_last_partition, v_row.partition_interval, v_row.parent_table)"
        funzione PL/pgSQL partman.run_maintenance(text,boolean,boolean,boolean) riga 157 a istruzione SQL
        istruzione SQL "SELECT "partman".run_maintenance(p_analyze := true, p_jobmon := true)"
        DETAIL:
        HINT:
2017-08-06 07:28:19.634 CEST [15400] CONTESTO:  funzione PL/pgSQL partman.run_maintenance(text,boolean,boolean,boolean) riga 358 a RAISE
        istruzione SQL "SELECT "partman".run_maintenance(p_analyze := true, p_jobmon := true)"
2017-08-06 07:28:19.636 CEST [6781] LOG:  processo di lavoro: pg_partman dynamic background worker (dbname=gps_data) (PID 15400) è uscito con codice di uscita 1


part_config for the table:

SELECT * FROM partman.part_config WHERE parent_table = 'history.gps_paths_filtered';

 parent_table | control | partition_type | partition_interval | constraint_cols | premake | optimize_trigger | optimize_constraint | epoch | inherit_fk | retention | retention_schema |retention_keep_table | retention_keep_index | infinite_time_partitions | datetime_string | automatic_maintenance | jobmon | sub_partition_set_full | undo_in_progress | trigger_exception_handling | upsert | trigger_return_null 
 ----------------------- | ---------- | ---------------- | -------------------- | ----------------- | --------- | ------------------ | --------------------- | ------- | ------------ | ----------- | ------------------ | ---------------------- | ---------------------- | -------------------------- | ----------------- | ----------------------- | -------- | ------------------------ | ------------------ | ---------------------------- | -------- | ---------------------
 history.gps_paths_filtered | write_date | partman        | 1 day              |                 |       4 |                4 |                  30 | none  | t          | 1 day     |                  | f                    | t                    | f                        | YYYY_MM_DD      | on                    | t      | f                      | f                | f                          |        | t

parent table definition:
gps_data=# \d+ history.gps_paths_filtered
Tabella "history.gps_paths_filtered"

 Colonna | Tipo | Modificatori | Memorizzazione | Dest. stat. | Descrizione 
 --------------------------------- | -------------------------- | -------------- | ---------------- | ------------- | -------------
 ogc_fid                          | bigint                   | non null     | plain          |             | 
 rid                              | character varying(100)   |              | extended       |             | 
 package_time                     | timestamp with time zone | non null     | plain          |             | 
 last_gps_time                    | timestamp with time zone | non null     | plain          |             | 
 last_db_time                     | timestamp with time zone |              | plain          |             | 
 points_filtered_old_gps_time     | smallint                 | non null     | plain          |             | 
 points_filtered_invalid_speed    | smallint                 | non null     | plain          |             | 
 points_filtered_outside_italy    | smallint                 | non null     | plain          |             | 
 points_filtered_same_gps_time    | smallint                 | non null     | plain          |             | 
 points_filtered_too_close_point  | smallint                 | non null     | plain          |             | 
 points_filtered_invalid_gps_time | smallint                 | non null     | plain          |             | 
 points_filtered_too_far_point    | smallint                 | non null     | plain          |             | 
 write_date                       | timestamp with time zone | non null     | plain          |             | 

Indici:
    "history_gps_paths_filtered_pk" PRIMARY KEY, btree (ogc_fid)
    "history_gps_paths_filtered_idx" btree (write_date) WITH (fillfactor='90')

**Comment by keithf4** [comment]
I think you may be running into a race condition with setting the partition interval to the same value as the retention period. And this isn't a race condition I'm likely going to try and handle. You're essentially trying to make a partition set with a single table which makes no sense from a design perspective. Try setting retention to at least a week for daily partitioning.

I also see no child tables listed in you're \d+ output, which will break pg_partman and, with the latest patch, should never be allowed to happen through normal maintenance. If that's the case, you will need to fix that by creating a child table manually or redo the partition setup.

**Comment by keithf4** [comment]
Sorry for the delay on this. Automatic retention will now no longer drop the last child table in any partition set as of v3.1.0. If you have any issues let me know.
