### ISSUE TITLE
Error inserting record with timestamp field when using arbitrary time interval partitions

### ISSUE THREAD

**Issue by akula1001** [keithf4/pg_partman#191]
Using partman 3.0.2 with postgres 9.5

Steps to reproduce:
```
create table foo(id serial, ts timestamp not null);
select partman.create_parent(p_parent_table:='public.foo', p_control:='ts', p_type:='partman', p_interval:='1 day');
insert into foo(ts) values(now());
```

Error:
```
ERROR:  operator does not exist: tstzrange @> timestamp without time zone
LINE 3:         WHERE c.partition_range @> NEW.ts
                                        ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
QUERY:  SELECT c.child_table, p.upsert                                      FROM partman.custom_time_partitions c
        JOIN partman.part_config p ON c.parent_table = p.parent_table
        WHERE c.partition_range @> NEW.ts
        AND c.parent_table = 'public.foo'
CONTEXT:  PL/pgSQL function foo_part_trig_func() line 9 at SQL statement
```

The issue is present when partitioning against `timestamp without time zone` fields since the range comparison happens against `tstzrange` in `custom_time_partitions`.

**Comment by keithf4** [comment]
Honestly, really not sure how to handle this one. The custom_time_partitions table uses the tstzrange type to store the range for each child table. Could possibly see about a second column with the tsrange type, but then I'd have to add some logic in to see which of the data types was actually in use by the partition set. Seems to be getting overly complicated.

Given a choice of which to use, tstzrange seemed better than tsrange. From frequent discussions, the use of timestamp without time zone is usually not what people want to use and, when they do, it doesn't work as they think it does. There are cases where timestamp without time zone may be valid, but they are far and few between. There are many blog posts about this

https://www.depesz.com/2014/04/04/how-to-deal-with-timestamps/

http://justatheory.com/computers/databases/postgresql/use-timestamptz.html  (see the comments where it's clarified that is can work with partitioning fine and is actually preferred).

For now, if you cannot change to using timestamptz, I suggest using one of the pre-set time intervals. Unless you really need less than 15 minutes or more than 1 year for an interval, I've found them to work in the vast majority of cases, even if you're trying to manage retention. You may just need to keep a bit more data than you originally intended.
