### ISSUE TITLE
Change premake and optimize_trigger values, child table creation and move data from parent table to child table

### ISSUE THREAD

**Issue by julianopg** [keithf4/pg_partman#194]
Hi Keith

I have partitioned myschema.mytable per month with default values (premake=4 and optimize_trigger=4):
`SELECT partman.create_parent('myschema.mytable', 'time_stamp', 'partman', 'monthly');`

And changed the part_config to create 10 partitions before and 10 partitions after the current month:
`UPDATE partman.part_config SET premake = '10', optimize_trigger='10' WHERE parent_table = 'myschema.mytable'`

And executed the maintenance functions to update:
`SELECT partman.run_maintenance();`

```
\d+ myschema.mytable
Child tables: myschema.mytable_p2017_03,
              myschema.mytable_p2017_04,
              myschema.mytable_p2017_05,
              myschema.mytable_p2017_06,
              myschema.mytable_p2017_07,
              myschema.mytable_p2017_08,
              myschema.mytable_p2017_09,
              myschema.mytable_p2017_10,
              myschema.mytable_p2017_11
```

So the new partitions were not created until add data and run the maintenance function again, but only the future partitions have been created:
```
INSERT INTO myschema.mytable (id, type_id, time_stamp) values ('Test',9999,'now()')
SELECT partman.run_maintenance();
\d+ myschema.mytable
Child tables: myschema.mytable_p2017_03,
              myschema.mytable_p2017_04,
              myschema.mytable_p2017_05,
              myschema.mytable_p2017_06,
              myschema.mytable_p2017_07,
              myschema.mytable_p2017_08,
              myschema.mytable_p2017_09,
              myschema.mytable_p2017_10,
              myschema.mytable_p2017_11,
              myschema.mytable_p2017_12,
              myschema.mytable_p2018_01,
              myschema.mytable_p2018_02,
              myschema.mytable_p2018_03,
              myschema.mytable_p2018_04,
              myschema.mytable_p2018_05
```

The data I have created today is correctly in the month partition:
```
SELECT partman.run_maintenance();
SELECT * FROM myschema.mytable_p2017_07;
Id | id_type | time_stamp
'Test',9999,'2017-07-25 09:50:34.320685+00'
```

But the data created before the partitioning wasn't moved to the child table and still there in the parent table:
```
SELECT * FROM myschema.mytable where src_id = 'Test'
Id | id_type | time_stamp
'Test',9999,'2017-07-25 09:50:34.320685+00'
'Test',9999,'2017-07-25 08:47:14.520131+00'
```

So I'm curious to know 3 things, please:

1. What is s the command to set premake=10 and optimize_trigger=10 in the function partman.create_parent() instead of alter the table partman.part_config;

2. Why the premake=10 haven't created the previous partitions? (the most recent data is January and there is an interval to July - today)

3. Why wasn't the existent data moved from the parent table to the child table?

Regards

**Comment by keithf4** [comment]
The only time past partitions are ever created is during initial setup, so if you want 10 past partitions, pass the premake value to `create_parent()`. Normal maintenance only ever creates future partitions.

Please continue to read the documentation. When a child table doesn't exist for the data that is input, it is put into the parent. Normal maintenance never moves data, as that could cause significantly long runtimes & transactions if a lot of data was dumped into the parent. There are other functions and scripts for moving the data out of the parent. Look into `partition_data_time()` and the `partition_data.py` script.

**Comment by julianopg** [comment]
Hi Keith

Many thanks for the prompt reply

Understood! I have partitioned a 21GB table that contains data since 2010 in a test server using the below command with success: 
Partition all data in a parent table. Commit after each partition is made. (Monthly partition interval)
python partition_data.py -c "host=localhost dbname=mydatabase" -p myschema.mytable -t time
This took about 2 hours to move all the rows!

So, what batch (-b) and interval (-i) values do you recommend to this busy production server (monthly partition interval)? I'd like to avoid all the data out in a single transaction and cause serious contention & I/O issues maybe add the pause in between batches to limit I/O activity
i.e:  python partition_data.py -p schema.parent_table -t time -i "1 week" -b 10

**Comment by keithf4** [comment]
Unless all your data is in a single month, it won't move it all in a single transaction when you use the python script. At most, 1 month of data would be moved before the first commit by default. The interval value passed to the script all depends on how much data there is per batch. I'd recommend a value that commits at least every minute or so. So, may want to try a 1 day interval to start.

If you want to partition all the data with a single run of the script, you don't want to set the `-b` option. That tells it how many times to commit before it stops running. So with your given command it would run 10 batches of 1 week data and then stop. The `-b` option is mostly useful if you need to have longer pauses after moving some data due to I/O constraints.

**Comment by julianopg** [comment]
Thank you for your clear and helpful explanation. I have the last one question

I will check a window to do everything in a single run script, if I can not do it, I will use the `-b 12` option to move the data of 1 year each day (Monthly partition interval), like this: 

`partition_data.py -p schema.parent_table -t time  -b 12`

So, do I need to execute this command every day to move 12 months of data per day, is that right?

**Comment by keithf4** [comment]
That will move 12 months of data (committing after each month) per run of that command, yes.

**Comment by julianopg** [comment]
Thanks 😄
