### ISSUE TITLE
Moving data with partition_data.py

### ISSUE THREAD

**Issue by julianopg** [keithf4/pg_partman#195]
Hi Keith

I'm moving the data from a huge table by year using the script:
`python partition_data.py -c "host=localhost dbname=mydb" -p myschema.mytable -t time -b 12`

Is it possible start to move the data from most recent year first and continue moving the old years later when I execute the script again?

**Comment by keithf4** [comment]
Check the `--order` option. 

You can pass `--help` to any of the python scripts for a full list of options.

**Comment by julianopg** [comment]
Lovely! It worked like a charm 😃
