### ISSUE TITLE
pg_partman (Windows install support)

### ISSUE THREAD

**Issue by gabrieledonufrio** [keithf4/pg_partman#197]
I am not able to install the pg_partman on windows, still I think is the best implementation ever.
Is there a windows install for pg_partman?
(I was not sure of the name until I find this article https://www.keithf4.com/postgresql-10-built-in-partitioning/ )

thks in advance

**Comment by keithf4** [comment]
The only install method I officially support is running `make` on the source. Please see Issue https://github.com/keithf4/pg_partman/issues/111 for some advice from others that have gotten this working on Windows.
