### ISSUE TITLE
pgxs.mk is missing (postgresql 10)

### ISSUE THREAD

**Issue by amenzhinsky** [keithf4/pg_partman#198]
Hi there!

I'm using `http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg` and trying to build v3.1.0 against the postgresql-10 package and getting this error:

```
make install 
Makefile:28: /usr/lib/postgresql/10/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target '/usr/lib/postgresql/10/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.
```

Any ideas?

**Comment by amenzhinsky** [comment]
Silly me, needed to install postgresql-server-dev-10.

**Comment by aaronArinder** [comment]
Thanks, @amenzhinsky, this helped me figure out what I needed.
