### ISSUE TITLE
Partitioning data during upgrade

### ISSUE THREAD

**Issue by amikhile** [keithf4/pg_partman#202]
We are on pg_partman 3.1.0 and postgres 9.6.3.
During upgrade we want to create partitions for existing tables.
What is the best approach we can take here? 
Currently we implemented this approach:
1) Renaming the table A to A_old (with the data)
2) Creating new table A (using LIKE)
3) Adding row to the part_config for this table
4) Creating function and trigger to inserting data for the correct partition.
5) Copy data from A_old to A

the partitions are created in the past because we are setting the premake parameter as a retention parameter.
Now we are facing the problem of having partitions created for half a year ahead.
So what is the best way to create partitions for the old data in the past?

**Comment by keithf4** [comment]
First can you clarify what you are upgrading?

**Comment by amikhile** [comment]
We are upgrading our server, when on new version we added partitioning to tables, So during server upgrade we need to partition the old data.

**Comment by keithf4** [comment]
If the tables are not already partitioned, then just go through the normal procedures outlined in the howto document. For the old, trigger-based method before PG10, you can run it on a live table with only a minimal downtime to turn the old table into the parent of the partition set. After that, all the data lives in the parent table so you'll have to move the data out to the children. Using the provided python script is the recommended method so it commits data in batches. It will create all necessary child tables as needed when you use that script.

Recommend making a copy of one of your current tables, including data, to test the process out so you're sure how it works and what the outcome is.

**Comment by amikhile** [comment]
Ok, Thanks you
