### ISSUE TITLE
Set template table owner to be the same as partitioned table owner

### ISSUE THREAD

**Issue by marcocitus** [keithf4/pg_partman#203]
Currently, the auto-generated template table used for defining indexes in native partitioning is always owned by superuser. It would be useful in multi-user scenarios if the template table had the same owner as the partitioned table.

**Comment by keithf4** [comment]
Good catch. Will try and get that in. Will also have to make sure to give usage on the partman schema to the table owner.

**Comment by keithf4** [comment]
This ownership issue has been fixed in v3.1.1. It won't go back and fix any existing partition set template tables, but it should take affect on any newly created ones that use the auto-generated one.
