### ISSUE TITLE
run_maintenance() does not remove old partitions

### ISSUE THREAD

**Issue by lorenzolucioni** [keithf4/pg_partman#204]
Hi,

I configured correctly (I guess) the partman config table, as in this how-to:
https://github.com/keithf4/pg_partman/blob/master/doc/pg_partman_howto.md
but run_maintenance() does not drop all the previous partitions.

This is my configuration:
"public.sla_apache_logs_raw";"event_ts";"time";"7 days";"";4;4;30;FALSE;TRUE;"180 days";"";FALSE;TRUE;FALSE;"IYYY"w"IW";TRUE;TRUE;FALSE;FALSE;FALSE;"''";TRUE
where:
retention='180 days'
retention_keep_table=FALSE

When I execute 
select partman.run_maintenance('public.sla_apache_logs_raw');
old partitions are not dropped.

You probably would know which version of Partman I'm running. 
How can I get the version?

Regards,
Lorenzo

**Comment by keithf4** [comment]
You can get the version of any extension using `\dx` in psql
```
keith@keith=# \dx
                               List of installed extensions
    Name    | Version |   Schema   |                     Description                      
------------+---------+------------+------------------------------------------------------
 pg_partman | 3.1.1   | partman    | Extension to manage partitioned tables by time or ID
 pgtap      | 0.99.0  | public     | Unit testing for PostgreSQL
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
(3 rows)
```
Can you please provide your config info in context with the table column names? You can make it easily readable by toggling extended display mode on (`\x`)
```
keith@keith=# \x
Expanded display is on.
keith@keith=# select * from partman.part_config;
-[ RECORD 1 ]--------------+-------------------------------------------------
parent_table               | partman_test.time_taptest_table
control                    | col3
partition_type             | native
partition_interval         | 1 day
constraint_cols            | «NULL»
premake                    | 6
optimize_trigger           | 6
optimize_constraint        | 30
epoch                      | none
inherit_fk                 | t
retention                  | «NULL»
retention_schema           | «NULL»
retention_keep_table       | t
retention_keep_index       | t
infinite_time_partitions   | f
datetime_string            | YYYY_MM_DD
automatic_maintenance      | on
jobmon                     | t
sub_partition_set_full     | f
undo_in_progress           | f
trigger_exception_handling | f
upsert                     | 
trigger_return_null        | t
template_table             | partman.template_partman_test_time_taptest_table
```
This will make it a lot easier to try and recreate your issue.

Can you also provide the full schema layout of the partitioned table itself (`\d+`) along with the current date on your system at the time you're doing run maintenance? This way I can set up the same set of child tables that you have to check what may be wrong with retention management. For example:
```
keith@keith=# \d+ partman_test.time_taptest_table
                                  Table "partman_test.time_taptest_table"
 Column |           Type           | Collation | Nullable | Default | Storage  | Stats target | Description 
--------+--------------------------+-----------+----------+---------+----------+--------------+-------------
 col1   | integer                  |           | not null |         | plain    |              | 
 col2   | text                     |           |          |         | extended |              | 
 col3   | timestamp with time zone |           | not null | now()   | plain    |              | 
Indexes:
    "time_taptest_table_pkey" PRIMARY KEY, btree (col1)
Triggers:
    time_taptest_table_part_trig BEFORE INSERT ON partman_test.time_taptest_table FOR EACH ROW EXECUTE PROCEDURE partman_test.time_taptest_table_part_trig_func()
Child tables: partman_test.time_taptest_table_p2018_01_12,
              partman_test.time_taptest_table_p2018_01_13,
              partman_test.time_taptest_table_p2018_01_14,
              partman_test.time_taptest_table_p2018_01_15,
              partman_test.time_taptest_table_p2018_01_16,
              partman_test.time_taptest_table_p2018_01_17,
              partman_test.time_taptest_table_p2018_01_18,
              partman_test.time_taptest_table_p2018_01_19,
              partman_test.time_taptest_table_p2018_01_20,
              partman_test.time_taptest_table_p2018_01_21,
              partman_test.time_taptest_table_p2018_01_22,
              partman_test.time_taptest_table_p2018_01_23,
              partman_test.time_taptest_table_p2018_01_24,
              partman_test.time_taptest_table_p2018_01_25,
              partman_test.time_taptest_table_p2018_01_26,
              partman_test.time_taptest_table_p2018_01_27,
              partman_test.time_taptest_table_p2018_01_28
Has OIDs: yes

keith@keith=# select now();
              now              
-------------------------------
 2018-01-16 11:53:51.767571-05
(1 row)
```

**Comment by lorenzolucioni** [comment]
tpbicube=> select * from partman.part_config;

-[ RECORD 2 ]--------------+---------------------------
parent_table               | public.sla_apache_logs_raw
control                    | event_ts
partition_type             | time
partition_interval         | 7 days
constraint_cols            | 
premake                    | 4
optimize_trigger           | 4
optimize_constraint        | 30
epoch                      | f
inherit_fk                 | t
retention                  | 180 days
retention_schema           | 
retention_keep_table       | f
retention_keep_index       | t
infinite_time_partitions   | f
datetime_string            | IYYY"w"IW
use_run_maintenance        | t
jobmon                     | t
sub_partition_set_full     | f
undo_in_progress           | f
trigger_exception_handling | f
upsert                     | 
trigger_return_null        | t



tpbicube=> \d+ public.sla_apache_logs_raw
                                  Table "public.sla_apache_logs_raw"
       Column        |            Type             | Modifiers | Storage  | Stats target | Description 
---------------------+-----------------------------+-----------+----------+--------------+-------------
 log_applicationkey  | text                        |           | extended |              | 
 event_ts            | timestamp without time zone | not null  | plain    |              | 
 transportstatuscode | bigint                      |           | plain    |              | 
 latency             | bigint                      |           | plain    |              | 
 xrequestid          | text                        |           | extended |              | 
Indexes:
    "idx_event_ts_sla_apache_logs_raw" btree (event_ts)
    "idx_log_applicationkey_sla_apache_logs_raw" btree (log_applicationkey)
    "idx_xrequest_sla_apache_logs_raw" btree (xrequestid)
Triggers:
    sla_apache_logs_raw_part_trig BEFORE INSERT ON sla_apache_logs_raw FOR EACH ROW EXECUTE PROCEDURE sla_apache_logs_raw_part_trig_func()
Child tables: sla_apache_logs_raw_p2017w29,
              sla_apache_logs_raw_p2017w30,
              sla_apache_logs_raw_p2017w31,
              sla_apache_logs_raw_p2017w32,
              sla_apache_logs_raw_p2017w33,
              sla_apache_logs_raw_p2017w34,
              sla_apache_logs_raw_p2017w35,
              sla_apache_logs_raw_p2017w36,
              sla_apache_logs_raw_p2017w37,
              sla_apache_logs_raw_p2017w38,
              sla_apache_logs_raw_p2017w39,
              sla_apache_logs_raw_p2017w40,
              sla_apache_logs_raw_p2017w41,
              sla_apache_logs_raw_p2017w42,
              sla_apache_logs_raw_p2017w43,
              sla_apache_logs_raw_p2017w44,
              sla_apache_logs_raw_p2017w45,
              sla_apache_logs_raw_p2017w46,
              sla_apache_logs_raw_p2017w47,
              sla_apache_logs_raw_p2017w48,
              sla_apache_logs_raw_p2017w49,
              sla_apache_logs_raw_p2017w50,
              sla_apache_logs_raw_p2017w51,
              sla_apache_logs_raw_p2017w52,
              sla_apache_logs_raw_p2018w01,
              sla_apache_logs_raw_p2018w02,
              sla_apache_logs_raw_p2018w03,
              sla_apache_logs_raw_p2018w04,
              sla_apache_logs_raw_p2018w05,
              sla_apache_logs_raw_p2018w06,
              sla_apache_logs_raw_p2018w07



tpbicube=> select now();
              now              
-------------------------------
 2018-01-17 14:43:04.940389+01
(1 row)

**Comment by keithf4** [comment]
So just doing the date math, you don't have any partitions that are older than 180 days ago
```
keith@keith=# select extract(week from now() - '180 days'::interval);
 date_part 
-----------
        29
(1 row)
```
Your oldest is the week that is exactly 180 days ago. Retention only drops things older than the given time period. So, there's nothing for retention to drop given what you have now. When next week roles around, week 29 should eventually be dropped.

**Comment by lorenzolucioni** [comment]
I see just now that the command:
tpbicube=> \d+ public.sla_apache_logs_raw
returns partitions from w29, but, instead, on the Database old partitions are still in place (even not returned by \d+):
...
sla_apache_logs_raw_p2017w26
sla_apache_logs_raw_p2017w27
sla_apache_logs_raw_p2017w28
sla_apache_logs_raw_p2017w29
...

Does it means that the oldest ones are no loger childs but are even not dropped by partman?

Regards,
Lorenzo

**Comment by keithf4** [comment]
So, by default the retention system does not drop the tables, it just uniherits the them. So they still exist in the database, but the parent doesn't see them anymore as part of the partition set. That is the default setting because I purposely set the defaults to be the least destructive. 

I do see that your config has `retention_keep_tables` set to false. Was that just recently changed? If so, maintenance isn't going to know about the old tables anymore because they're not part of the inheritance tree so you will have to drop them manually. Any future tables should be destroyed now that you have the keep setting set to false. If that doesn't happen, please let me know.

**Comment by lorenzolucioni** [comment]
Well you are right. 
Do be sure, I've changed to 150 days (instead of 180 days, since it's fine for us to drop some old ones) and executed the run_maintenance.
Partman dropped few tables in the middle (from 180 to 150 days ago) and left again the old ones, becausa of the reason you explained.
So no bug at all.

Thanks and best regards,
Lorenzo

**Comment by keithf4** [comment]
Glad to help you get things figured out and that it wasn't a bug. :)
