### ISSUE TITLE
Postgres 10 native automatic partition creation

### ISSUE THREAD

**Issue by sebrestin** [keithf4/pg_partman#205]
As I understand this is not available at the moment only by running run_maintenance().

Is there a plan for it? Or maybe a workaround?

**Comment by keithf4** [comment]
I've not heard of any plans for core postgres automatically making new partitions any time in the near future. If there is, it's likely quite a ways off.

**Comment by bsebi** [comment]
I was referring if there are any plans to add such a feature into Partman.

**Comment by keithf4** [comment]
pg_partman already has a feature to do maintenance for you without having to manually call run_maintenance(). Look into setting up the background worker described in the README and doc file.
