### ISSUE TITLE
Run_maintenance(); will not create new partitions if it is not run for prolonged period of time before usage.

### ISSUE THREAD

**Issue by LaVoCG** [keithf4/pg_partman#227]
I develop on local machine, which ends up being offline for the night. For testing I use partitioning setup with subpartitions: Daily->hourly. 
After leaving for the night, on the next day running run_maintenance(); does not create new partitions.

if that command is not run in timeframe, table/subtables have defined range for, it stops working properly - does not create new partitions;

Using PostgreSQL 10.4. and native partitioning.

While, yes, in production environment it would not be an issue, as server would be always online or with very little downtime, regularly running run_maintenance command. But the issue exists and it breaks auto maintenance functionality if it is let to be skipped.

**Comment by keithf4** [comment]
Is there new data being entered? If not, pg_partman by default does not create new partitions. If you want it to create new partitions when there is no new data, and it is time-based, you can set the `infinite_time_partitions` option in the config table.

**Comment by LaVoCG** [comment]
Adding new data when current_timestamp(); is further ahead than created partitions exist for, always return SQL error addressing that no partition was found. Note: it is native partition with sub-partitioning. Trying to run run_maintenance(); results in no new created partitions. In the end new data has nowhere to go.

**Comment by keithf4** [comment]
True. Looks like you will need the `infinite_time_partitions` option then. I believe that should cause it to catch up and create all the intervening partitions since there is no newer data than the oldest child table that had existed before.

**Comment by LaVoCG** [comment]
Ok. Figured as much. Though if I temporarily enable it, run run_maintenance(); partitions are created. 
Solves that issue. But if I after that disable, infinite parameter, and run run_maintenance(); (after waiting some time but this time within time range partitions are created for), no new partitions. Would expect for it to work after it has catched up. 

Also, How is it handling retention policy (with table dumps) with that config option enabled?

**Comment by keithf4** [comment]
Without that option enabled, new partition creation in based on the data in the partition set, not the latest partition created. So I recommend just leaving the option on for your testing or in any situation where there won't be any new data being entered but you want the child partition creation to keep caught up with "now".

Retention policy is not affected by that option. Retention will always drop tables that have expired data based on what you set it to. However, it should never drop the last partition in a set since that is required for pg_partman to function. So if you don't use things for a while, run maintenance with retention enabled, you could end up with a single partition left in your set.

**Comment by LaVoCG** [comment]
Another case. If the timeframe of skipping run_maintenance() is long enough, it fails at retention. It is trying to drop the last partition in partition set, thus failing. My temporary fix for this - move retention code bit after partition creation in run_maintenance(); function. (for time based partitions)

**Comment by keithf4** [comment]
When you say maintenance is failing, do you mean it's throwing an error or that it doesn't remove the last partition? As I said in my previous response, it will never remove the last partition. Otherwise it could never know where to pick up again from in the future.

If it's throwing an error, can you please give me the error it's throwing, your part_config contents and the schema of your table? It should not be throwing any errors, but it will throw a WARNING to let you know that there was an attempt to drop the final partition. This is intentional.

**Comment by LaVoCG** [comment]
reverted that temporary fix, to get that error again.

```
someDB=# select run_maintenance(NULL, true, true, true);
NOTICE:  run_maint: v_partition_expression: created_at
NOTICE:  run_maint: parent_table: public.activity_log, v_last_partition: activity_log_p2018_08_09_1710
WARNING:  Attempt to drop final partition in partition set public.activity_log as part of retention policy. If you see this message multiple times for the same table, advise reviewing retention policy and/or data entry into the partition set. Also consider setting "infinite_time_partitions = true" if there are large gaps in data insertion.).
ERROR:  Child table given does not exist (public.activity_log_p2018_08_09_1710)
CONTEXT: PL/pgSQL function show_partition_info(text,text,text) line 38 at RAISE
SQL statement "SELECT child_start_time                                              FROM public.show_partition_info(v_parent_schema||'.'||v_last_partition, v_row.partition_interval, v_row.parent_table)"
PL/pgSQL function run_maintenance(text,boolean,boolean,boolean) line 157 at SQL statement
DETAIL: 
HINT: 
CONTEXT:  PL/pgSQL function run_maintenance(text,boolean,boolean,boolean) line 360 at RAISE
```

and relevant output from /dt in psql both before and after running run_maintenance() when it fails:
```
 public | activity_log                  | table | postgres
 public | activity_log_p2018_08_09_1530 | table | postgres
 public | activity_log_p2018_08_09_1540 | table | postgres
 public | activity_log_p2018_08_09_1550 | table | postgres
 public | activity_log_p2018_08_09_1600 | table | postgres
 public | activity_log_p2018_08_09_1610 | table | postgres
 public | activity_log_p2018_08_09_1620 | table | postgres
 public | activity_log_p2018_08_09_1630 | table | postgres
 public | activity_log_p2018_08_09_1640 | table | postgres
 public | activity_log_p2018_08_09_1650 | table | postgres
 public | activity_log_p2018_08_09_1700 | table | postgres
 public | activity_log_p2018_08_09_1710 | table | postgres

```

part_config contents:
```
INSERT INTO public.part_config
(parent_table, control, partition_type, partition_interval, constraint_cols, premake, optimize_trigger, optimize_constraint, epoch, inherit_fk, retention, retention_schema, retention_keep_table, retention_keep_index, infinite_time_partitions, datetime_string, automatic_maintenance, jobmon, sub_partition_set_full, undo_in_progress, trigger_exception_handling, upsert, trigger_return_null, template_table, publications)
VALUES('public.activity_log', 'created_at', 'native', '00:10:00', NULL, 4, 4, 30, 'none', true, '1 hours', 'archive', true, true, true, 'YYYY_MM_DD_HH24MI', 'on', true, false, false, false, '', true, 'public.template_public_activity_log', NULL);
```

Table schema:
```
CREATE TABLE public.activity_log (
	id serial NOT NULL,
	log_name varchar(255) NULL,
	description text NOT NULL,
	subject_id int4 NULL,
	subject_type varchar(255) NULL,
	causer_id int4 NULL,
	causer_type varchar(255) NULL,
	properties text NULL,
	created_at timestamp NOT NULL DEFAULT (now() at time zone 'Europe/Riga'),
	updated_at timestamp NULL DEFAULT (now() at time zone 'Europe/Riga')
) PARTITION BY range (created_at) ;
```

**Comment by keithf4** [comment]
Thanks. I got things set up and will see what happens after a while.

**Comment by keithf4** [comment]
I've been able to reproduce this bug, so I'll work on trying to get a fix for it into the next release. I am working on a larger release at the moment that may take a while, so it may get delayed until then. Fortunately you said you were only running into this in testing, and in the most common use case, maintenance will be running on a regular basis so it shouldn't be something people will commonly run into.

Thanks for reporting the issue and your patience while trying to debug it!

**Comment by LaVoCG** [comment]
No problem. These kinds of obscure issues are hard to find as they occur in uncommon scenarios.

**Comment by froossv** [comment]
I'm running monthly->daily partitions and had this same issue. But setting infinite_time_partitions to true fixed the issue where not running run_maintenance() for a period of time and then running it created the partitions. Today's date is 24 June and I started partitioning at the start of this month so only partition was created for May, April, March, July, August and September (premake = 4) (only 1st day of each month existed). But after setting infinite_time_partitions = true created partitions for all days for the previous months. How to disable this feature? (pic attached)
![Screenshot from 2019-06-24 18-07-47](https://user-images.githubusercontent.com/16957582/60019281-24a6dc80-96ab-11e9-9210-f47944f5a4f3.png)

**Comment by keithf4** [comment]
There is no way to "disable" what you're encountering here. `infinite_time_partitions` is doing what it's designed to do and not caring about the data that exists in the partition set and creating all necessary partitions to catch up with "now".

Unless you have a specific need for organizing your data into month/day subpartitions, I don't recommend doing so. It gives you no performance benefit (it actually makes it worse). Unless there is some business requirement for this sort of data organization, subpartitioning is only of benefit when you're getting into extreme amounts of data in a single partition set (100s of terabytes or petabytes). Especially when all levels are the same data type.

I recommend setting a single partition level that fits whatever need you have for data retention or the optimal data size of your queries.

**Comment by froossv** [comment]
Yes i read before that there are no performance benefits but there is a business requirement in my context so i have partitioned as so. It's ok then i'll take care of the rest. Thank you for the quick reply :)

**Comment by keithf4** [comment]
So wish I'd taken the time to look into the cause of this earlier because it was a very easy fix. Anyway, below is a diff for a literal single function argument change to resolve this. I should have a new release out next week hopefully, but if you want to give it a test before then I'd appreciate it.
```
diff --git a/sql/functions/drop_partition_time.sql b/sql/functions/drop_partition_time.sql
index 36e89c3..dfbc710 100644
--- a/sql/functions/drop_partition_time.sql
+++ b/sql/functions/drop_partition_time.sql
@@ -135,8 +135,9 @@ WHERE schemaname = split_part(p_parent_table, '.', 1)::name
 AND tablename = split_part(p_parent_table, '.', 2)::name;
 
 -- Loop through child tables of the given parent
+-- Must go in ascending order to avoid dropping what may be the "last" partition in the set after dropping tables that match retention period
 FOR v_row IN 
-    SELECT partition_schemaname, partition_tablename FROM @extschema@.show_partitions(p_parent_table, 'DESC')
+    SELECT partition_schemaname, partition_tablename FROM @extschema@.show_partitions(p_parent_table, 'ASC')
 LOOP
     -- pull out datetime portion of partition's tablename to make the next one
      SELECT child_start_time INTO v_partition_timestamp FROM @extschema@.show_partition_info(v_row.partition_schemaname||'.'||v_row.partition_tablename
@@ -289,4 +290,3 @@ HINT: %', ex_message, ex_context, ex_detail, ex_hint;
 END
 $$;

**Comment by keithf4** [comment]
Apologies on the delays getting this issue fixed. This should no longer be an issue as of v4.2.0. Thanks for reporting it!

**Comment by sr250230** [comment]
Thanks, I have faced the same issue. After updating  infinite_time_partitions to true, partitions got created with the run_maintenance() function.

update partman.part_config set infinite_time_partitions=true ;
