### ISSUE TITLE
Support for sub-partitioning

### ISSUE THREAD

**Issue by keithf4** [keithf4/pg_partman#26]
Implement a method to allow child tables to themselves be parent tables of another partition set.

**Comment by keithf4** [comment]
Added in 1.8.0

**Comment by davidblewett** [comment]
Does this mean that data remains in the intermediate levels of the chain? I.e., in your example "Sub-partition Time->Time->Time: Yearly -> Monthly -> Daily", does data remain in the Yearly and Monthly partitions? Or does it only finally reside in the Daily set?

**Comment by keithf4** [comment]
It resides in the lowest level (daily in this case). The main advantage of subpartitioning in postgresql is to avoid the constraint exclusion checks and directly query the exact interval of data that you're looking for by explicitly naming the partition instead of using a WHERE clause. It's only really a concern with extremely large data sets that I've seen. But I had many people asking me for this feature at conferences (one person I know that actually had such large data sets), so I put the work into doing it.
