### ISSUE TITLE
Deadlock Detected...

### ISSUE THREAD

**Issue by isaiasanchez** [keithf4/pg_partman#32]
I'm having this issue when running run_maintenance() in a very busy database system and child tables aren't created making the parent table receive data and have to run partition_data.py constantly to clean parent tables. Do you have an idea of how to avoid deadlocks? maybe if run_maintenance()  locks the table before any other transaction until it finishes all set of child table creation. Maybe with an external script in python.

**Comment by keithf4** [comment]
1.8.0 has been released and has a new argument to run_maintenance() to specify an individual partition sets to run it on. Also, setting the use_run_maintenance() column to in the part_config table will allow to you  call run_maintenance() without a parameter and avoid having it touch partition sets where you need it called individually.
Sorry for the delay getting this out. Hopefully this helps!

**Comment by isaiasanchez** [comment]
Yes, sure. I wil test it and get back to you.

**Comment by isaiasanchez** [comment]
This release works great. Also disabling analyze is helping me with deadlocks and child creation runs faster. At the end of all childs creation I am running an ANALYZE over the parent tables and everything is going very good.

**Comment by keithf4** [comment]
Great to hear! Thanks for the feedback.

**Comment by isaiasanchez** [comment]
would you upload it to PGXN?

**Comment by keithf4** [comment]
Done! Was a big change so wanted to test it on some local systems for a bit too. So far looks ok.
*fingers crossed*
