### ISSUE TITLE
mailing list

### ISSUE THREAD

**Issue by rdp** [keithf4/pg_partman#34]
Hey, I didn't see an easy way to 'ask a question' or 'suggest a feature' might be nice to have a mailing list of some type for that purpose created.
Cheers!
-roger-
[the feedback was "dang, I really wanted it to at least be an option to automatically create new partitions, what we want to have is basically oracle's interval partitioning but for postgres"]
Thanks!

**Comment by keithf4** [comment]
I've updated the documentation in 1.8.0 so hopefully things are clearer.

**Comment by rdp** [comment]
thank you.
