### ISSUE TITLE
run_maintenance is not working

### ISSUE THREAD

**Issue by Sam2002** [keithf4/pg_partman#39]
id-Static partitioning is not working probably, when using the extension on a table with data inserted, all pre-partition data does not go to child tables and after running run_maintenance, no child tables are being created, how is it possible to overcome this problem?

**Comment by keithf4** [comment]
I'm going ahead with changing the minimal interval for serial partitioning to 10 in the next version. Should avoid confusion like this and even that is still far lower an interval than I'd ever suggest partitioning a table.

**Comment by keithf4** [comment]
v1.8.2 has been released with the above mentioned fix.
