### ISSUE TITLE
feature request: Hybrid mode

### ISSUE THREAD

**Issue by adunstan** [keithf4/pg_partman#40]
I'd like a mode that would use non-dynamic SQL to manage data within premake intervals of the current timestamp and dynamic sql (possibly with partition table creation too) for events outside that range, rather than putting those events in the parent table. So this would be a hybrid of dynamic and static.

**Comment by keithf4** [comment]
I'd initially had an option so you could avoid having the dynamic fallback portion of the trigger and stick with the old static method. Now that I'm looking things over, I'm wondering if that's really even needed at all and I should just force all triggers to be this new hybrid? Thought I'd run that question by you in case you could think of any scenario where that dynamic fallback wouldn't be desired. Without it, the data would just go to the parent anyway.

**Comment by adunstan** [comment]
Presumably it will still go into the parent if the partition doesn't exist. For my purposes I cant think of any good reason not to do this, but I'm not familiar with the way everyone else is using the package. If I were designing it from scratch that's what I'd do, though.

**Comment by keithf4** [comment]
Yup, it goes to the parent. So I have my update with the dynamic option backed up. Will do the release without it for now and see how it goes. Thanks for the quick response!

Just FYI, my next version will be 2.0.0 and 9.4+ only with this feature. I'm adding a background worker and using some other newer features and figured this drastic of a change was a good a time as any to introduce this newer version requirement. So apologies if you won't be able to use this hybrid feature on current clients on older versions. More incentive to upgrade! :D

**Comment by adunstan** [comment]
I can manage without for existing clients. But thanks.

**Comment by keithf4** [comment]
Apologize for how long this took. If you'd like to test this out, I've got a release candidate for v2.0.0 posted with this feature added. You can migrate existing partition sets to this hybrid trigger as well.

https://github.com/keithf4/pg_partman_v2RC1

**Comment by keithf4** [comment]
Version 2.0.0 has been released with this feature. Let me know if you have any issues.
