### ISSUE TITLE
incremental index creation

### ISSUE THREAD

**Issue by adunstan** [keithf4/pg_partman#41]
I'd like to be able to add an index to the parent and then run reapply_indexes.py to have it propagated to the children without having it drop and recreate all the exisiting indexes. Alternatively, a separate script to do this.

**Comment by keithf4** [comment]
Sorry for the delay on working on this. Was trickier than I initially thought and needed time to really test it properly. Here's a link to a gist with a new script that I believe does what you're looking for. Would appreciate if you could give it a test and make sure it works ok. If so, will include it with the next release

https://gist.github.com/keithf4/787a1a86e1d36ea64a13

**Comment by adunstan** [comment]
Seems to be working as expected.

**Comment by keithf4** [comment]
Great! Thanks for the feedback. Will include this in my next release.

**Comment by keithf4** [comment]
Released v1.8.2 that contains this script. Thanks for the tip!
