### ISSUE TITLE
epoch partitioning

### ISSUE THREAD

**Issue by menardorama** [keithf4/pg_partman#44]
Hi,

We use pg_partman since a year but we are facing table size issues.

We use id-static partitionning for our table (zabbix), but we see that run_maintenance procedure take ages to complete (when it complete) because of this query 
  EXECUTE 'SELECT '||v_row.control||' - ('||v_row.control||' % '||v_row.part_interval::int||') FROM '||v_row.parent_table||'
            WHERE '||v_row.control||' = (SELECT max('||v_row.control||') FROM '||v_row.parent_table||')' 
            INTO v_current_partition_id;

The fact is the explain plan will be awfull and will consume all ressources.

I think that epoch based partitionning could handle the issue, do you think that it's something feasable ?

**Comment by keithf4** [comment]
I've had an idea for doing this in my notes for a while (suggested from other zabbix users). I think after I get the hybrid issue (https://github.com/keithf4/pg_partman/issues/40) taken care of, this may be easier to pull off. Unfortunately I can't give you any time estimates on when that wlll be.

But, looking at the code for getting the current max value again, may have an idea how to make that more efficient in the mean time. :)

Also, not sure if you checked the lasted version notes, you can now call run_maintenance() on individual partition sets. So one taking a really long time won't hold up all the others.

**Comment by menardorama** [comment]
Hi

Thanks for your reply, I didn't saw that run_maintenance can be called for individual partition set, I'll have a look.

In the mean time I was thinking of creating another partition type (epoch based instead of ids), would it fit to you if do it and push it ?

**Comment by keithf4** [comment]
I have quite a lot of changes planned for the hybrid mode patch, so I'd rather not add epoch to the extension at this time. You are free to fork the extension and add the feature yourself if you need it before I'm able to provide it, but I unfortunately will not be able to merge it.

**Comment by menardorama** [comment]
Hi

Any news on this request ? Or is the current version is OK to implement it on my side ?

**Comment by keithf4** [comment]
Sorry for the long delay. Paying client work takes priority. :)  I'll hopefully have v2.0.0 out soon. It's taken me a while to be happy with my first version of a background worker, this being my first time really writing any C code.

**Comment by keithf4** [comment]
Sorry this has taken so long, but version 2.2.0 is out and has a flag option to enable epoch partitioning. Let me know if this works ok for you!
