### ISSUE TITLE
run_maintenance with analyze sets to false still analyzes if extra constraints are specified

### ISSUE THREAD

**Issue by lucasmo** [keithf4/pg_partman#45]
When running `run_maintenance(null, false)`, analyzing isn't done on creation of new child tables. However, analyzing is still performed if `partman.part_config` has a non-null value in the `constraint_cols` column for the specified parent table.

**Comment by lucasmo** [comment]
It would also be great if run_maintenance could return some status information that suggests it created a new table. I am experiencing deadlocks on very large partition sets when analyzing and creating new tables happens in the same transaction.

**Comment by keithf4** [comment]
Sorry, I see where I missed passing the "analyze" flag to the apply_constraints() function in run_maintenance(). Will work on fixing that.
If you've got pg_jobmon installed, you should be able to see if/when a new partition is made during a run_maintenance() call. I realized I forgot to add the analyze step to jobmon logging and and am working on getting that added in as well.
Will see if I can add some output to run_maintenance() as well, but not sure exactly what would be the most useful at this time. Will keep it in my notes to consider.

**Comment by keithf4** [comment]
I've pushed out version 1.8.1 with a fix for the forced analyze when using extra constraint columns.
pg_jobmon also does a better job at logging new partition creation and also logs a step if/when an analyze is running so you can better debug where partition maintenance may be stuck at.

Please let me know if this helps.

**Comment by keithf4** [comment]
I've released v1.8.2 that contains this new script. Thanks for the tip!

**Comment by keithf4** [comment]
Woops... previous comment was for another issue. Clicked the wrong one. Still, this issue should be fixed now as well.
