### ISSUE TITLE
Trying to insert column into incorrect partition: Fails with constraint check fail

### ISSUE THREAD

**Issue by malleblas** [keithf4/pg_partman#46]
I am using mimeo to pull in data from multiple sources in different time zones. The destination is partitioned using partman. The trigger function created by partman, does not seem to work with these disparate sources.

select to_char(timestamp with time zone '2015-02-02 00:00:00.343+11', 'IYYY"w"IW')
Return 2015w06, which is the current behaviour of the trigger function, however the constraint that has been generated does not match. It is using the postgres.conf timezone of Australia/Melbourne (+11) however the constraints are generated based on UTC.

select to_char(timestamp with time zone '2015-02-02 00:00:00.343+11' at time zone 'utc', 'IYYY"w"IW')
Returns 2015w05 which matches what the constraint is requiring.

The constraint is
CONSTRAINT data_value_p2015w06_partition_check CHECK (creation_timestamp >= '2015-02-02 11:00:00+11'::timestamp with time zone AND creation_timestamp < '2015-02-09 11:00:00+11'::timestamp with time zone)
)
and this is the table the trigger is trying to insert into.

postgres@terbium ~ $ /usr/lib64/postgresql-9.1/bin/run_refresh.py -c "host=localhost dbname=process_data user=postgres" -v
Running inserter_serial replication for table: cojafex.data_value
Traceback (most recent call last):
  File "/usr/lib64/postgresql-9.1/bin/run_refresh.py", line 102, in <module>
    single_process(result, mimeo_schema)
  File "/usr/lib64/postgresql-9.1/bin/run_refresh.py", line 60, in single_process
    cur.execute(sql, [i[0]])
psycopg2.InternalError: new row for relation "data_value_p2015w06" violates check constraint "data_value_p2015w06_partition_check"

For now, I have added to the trigger function, the "at time zone 'UTC'".

**Comment by keithf4** [comment]
Sounds like an issue someone else brought up previously when using a different timezone on the client than runs on the server. 

https://github.com/keithf4/pg_partman/issues/36

You have to make sure that the client session is using the same timezone as the server, most especially when you're using the timestamptz column. There's a reason it was left as an available session variable to be set. And honestly, you should try and have the server & database timezones set to UTC. You're making things much harder on yourself trying to run different systems in different timezones and replicate data from one to the other based on a timestamp column.

**Comment by keithf4** [comment]
Did setting the client timezone work for you? Or are you still having any issues?

**Comment by malleblas** [comment]
I changed the timezone for the server back to UTC and that works as expected.
Thinking about it more it would make sense that every client set their own timezone and set the server to UTC.

However it may also be useful for people to partition based on their local time zone. I now have data that belongs to the wrong partition based on local timezone so I have to wait an extra day (11 hours actually) before deleting the partition. Not a big deal, but something I have to think about.

**Comment by keithf4** [comment]
There's nothing wrong with partitioning based on a local timezone. I think the complication is coming in when you try and then replicate that data across to another system in a different timezone where it is partitioned as well. I'm not sure there's much I can do about handling situations like that.
