### ISSUE TITLE
custom_time_partitions cleanup

### ISSUE THREAD

**Issue by hydrogenoid** [keithf4/pg_partman#49]
custom_time_partitions should be cleaned by undo_partition_time().
Currently, if you partition a table with a custom interval and undo the partitioning, you can't partition it again until you have manually removed the entries from custom_time_partitions.

**Comment by keithf4** [comment]
Oversight on my part. Will get that fixed in next version. Thanks!

**Comment by keithf4** [comment]
Released version 1.8.3 that has this fix in it. Thanks for reporting!

**Comment by hydrogenoid** [comment]
That was pretty fast, thank you.
