### ISSUE TITLE
Question: Partition to partition fk's

### ISSUE THREAD

**Issue by hopesea** [keithf4/pg_partman#53]
Is there any support for pg_partman to create foreign keys between the partitions of two tables; ie. where the parent tables have a foreign key constraint between them, and have pg_partman establish the foreign keys between each of the corresponding partitions beneath those two tables?

The behaviour I observe is that the foreign key is established between the partition and the parent related table rather than the partition of the related table.

**Comment by keithf4** [comment]
I believe I discuss what your asking in the later part of my blog post for when I released the FK feature I do support. It's very tricky situation with the way partitioning uses table inheritance and I honestly don't have any idea how to support this in a sane manner at this point.

http://www.keithf4.com/table-partitioning-and-foreign-keys/

**Comment by keithf4** [comment]
Closing. If you have anymore questions, feel free to reopen.
