### ISSUE TITLE
Inherited Foreign Keys don't inherit the DEFERRABLE / INITIALLY DEFERRED states

### ISSUE THREAD

**Issue by davidblewett** [keithf4/pg_partman#54]
As part of #23, foreign keys are now applied to child tables. However, the `DEFFERABLE`/ `NOT DEFERRABLE` and `INITIALLY DEFERRED` / `INITIALLY IMMEDIATE` flags are not copied. I use a pattern of deleting data and using COPY in (ensuring that everything is consistent at commit time), which this change breaks. These 2 flags are available via pg_constraint ( http://www.postgresql.org/docs/current/static/catalog-pg-constraint.html ) as `condeferrable` and `condeferred`. The alternative is to use `pg_get_constraintdef` ( http://www.postgresql.org/docs/current/static/functions-info.html ) to generate the exact same definition as the existing one, and just apply it with a new name to the child table.

**Comment by keithf4** [comment]
This has been fixed in version 1.8.4. Should be able to use the python script to reapply any FKs you have in place with all the features they should have. Let me know if you have any issues.
