### ISSUE TITLE
p_control other field types

### ISSUE THREAD

**Issue by SOLDIERz** [keithf4/pg_partman#58]
I know that is probably not the right place for such an request but I don't know where to put it else. So are there plans to support other field types then date and integer? Because I want to this based on an uuid field.

**Comment by keithf4** [comment]
This is the proper place to ask :)

Partitioning schemes outside of time & id typically do not require on-going maintenance to create future partitions. And the ones that do, typically don't have any sort of easily predictable pattern for that ongoing maintenance that I could support in a generalized manner. UUID fits both of those conditions. Most UUID partition setups I've seen have a one-time setup where the block of values that each partition will cover is known ahead of time for all possible values. So you set those children up once and you're done. And even if you didn't pre-create all the child tables, how would you then determine a maintenance scheme for future partitions when the next UUID generated could literally be anywhere within the entire possible value range? Creating new partitions at the time of insertion based on the inserted value is full of race conditions with trigger-based partitioning and is why I pre-create them (http://www.fuzzy.cz/en/articles/automatic-management-of-partitions-in-postgresql/)

My goal with this extension at this time is for handling partitioning conditions that require easily predictable, on-going maintenance. If there comes a time when I think I've gotten all the features I want implemented in this extension, and partitioning still is not built in core (which would most likely handle what you're looking for), I may see about adding support for custom, one-time partition setups like UUID and alphabetical.

**Comment by SOLDIERz** [comment]
Okay cool. Thanks for the information. :-)
