### ISSUE TITLE
Allow child tables to be created in a separate schema

### ISSUE THREAD

**Issue by smith153** [keithf4/pg_partman#60]
As a wishlist item, it would be nice to be able to specify a different schema for child tables.

**Comment by keithf4** [comment]
Not sure I understand the need for this unless you're talking about something more complicated with putting child tables in a single partition set in multiple schemas. Even then I'd question the reason since that would be quite complicated to configure. The parent table is essentially an empty object so just putting it in the schema you want should be easy enough.
I'm open to use cases though in case I'm missing something.

**Comment by smith153** [comment]
Hello Keith,
Sorry for being vague. We have recently converted some of our in house databases to postgresql and are using your partition framework. It fit our needs perfectly, we just had some of the database users complain about the fact that they can see the child partition tables (there are many of them), and this clutters up table listing views in GUI tools like Dbsolo/Dbeaver, ect. I see in the source that child tables are created using the parent schema. Seemed like it would be easy enough to add a "child_schema" column to the partman config table and then all new child tables could be created under that schema. This is just a simple wishlist item, if you don't find it has any purpose, then don't worry about it :)

**Comment by keithf4** [comment]
Not likely to be adding this feature any time soon if it's just a GUI tool annoyance for the only reason. Maybe once I've gotten the other major features I have in mind done.

**Comment by walpino** [comment]
i agree with smith153

it would be nice 
otherwise with  a partition of 12 months x X ids it blows up the main schema with child partitions (tables)
and we have 5 or 6 tables which we would partitioning

but as I said it is a nice to have

**Comment by keithf4** [comment]
This still seems like mostly a presentation issue to me with no real further benefit. Version 2.0.0 has been released and can have new features developed against it. If someone does a pull request that includes a complete version patch as I've done with my other releases, as well as pgtap tests to ensure it works, I'll gladly accept the contribution. I have no plans on adding this feature myself at this time.

**Comment by julianopg** [comment]
Sorry to resurrect this post, but I need to know if is this feature available❓ 🤔
