### ISSUE TITLE
create_parent() trips upon granting permissions to PUBLIC

### ISSUE THREAD

**Issue by volter** [keithf4/pg_partman#66]
Version: 2.1.0

root@[local]:5432 [mydb] # SELECT partman.create_parent('public.mytable', 'time', 'time', 'monthly'); 
 ERROR:  role "PUBLIC" does not exist
[12:39] <volter> CONTEXT: SQL statement "GRANT DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE ON public.mytable_p2015_10 TO "PUBLIC""
PL/pgSQL function partman.create_partition_time(text,timestamp without time zone[],boolean) line 174 at EXECUTE statement
PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,boolean,text,boolean,boolean,boolean) line 272 at assignment

The keyword PUBLIC is treated as user name and quoted. This causes the statement to fail.

**Comment by keithf4** [comment]
Well that's fun. Will see what I can do.

**Comment by keithf4** [comment]
Just FYI I'm not going to be able to get this fixed for the next version. The "proper" way I want to fix this involves some bigger changes that I don't want to have mixed in with the changes I've done in 2.2.0.

**Comment by plockaby** [comment]
If it's not too pushy, this bug is significantly important to me as well.

**Comment by keithf4** [comment]
Sorry for the delay on this. I've got this handled in the next release. Consolidated a lot of the privilege management code, so can't just give a simple diff to allow you to fix the change now. Working on fixing one other bug and as soon as that's done, I'll get this fix out.

**Comment by keithf4** [comment]
Finally have 2.2.3 released which should properly handle the special PUBLIC role. If someone goes and created a real role called "PUBLIC" it won't handle that quite as gracefully, but honestly I'd rather it break for someone that does that. :)

**Comment by plockaby** [comment]
Fantastic. Thanks for the update!
