### ISSUE TITLE
Partitions based  on text column

### ISSUE THREAD

**Issue by dturon** [keithf4/pg_partman#68]
Hi,  
I have request for new feature. We have simple table:

-- table isnt real, so data is not usefull
CREATE TABLE goods(id serial primary key, category text, data int); 
-- we have table filled with some kinds of goods
INSERT INTO goods(category, data) SELECT 'cat1', a FROM generate_series(1, 100000) x(a);
INSERT INTO goods(category, data) SELECT 'cat2', a FROM generate_series(1, 10000) x(a);
INSERT INTO goods(category, data) SELECT 'cat3', a FROM generate_series(1, 10000) x(a);
INSERT INTO goods(category, data) SELECT 'cat6', a FROM generate_series(1, 100) x(a);
INSERT INTO goods(category, data) SELECT 'cat5', a FROM generate_series(1, 100) x(a);

-- partitions can be based on quantity of some kind 
SELECT most_common_vals, most_common_freqs FROM pg_stats WHERE tablename='goods' AND attname='category';
      most_common_vals      |                  most_common_freqs                  
----------------------------+-----------------------------------------------------
 {cat1,cat2,cat3,cat6,cat5} | {0.831933,0.0841,0.0824667,0.000766667,0.000733333}
(1 řádka)

SELECT n_live_tup FROM pg_stat_user_tables WHERE relname ='goods';
-[ RECORD 1 ]------
n_live_tup | 120200

In partman partition setup can be defined some treshold  (like if kind have more then 10% and table have more then 100000 rows (both values can be configured) then maintenance function make new partition - in this case create partition:

goods_cat1

For some tables can be this usefull. Thanks for look on it:) Its only my dream .... If you dont like it close issue.

**Comment by keithf4** [comment]
The intent of this extension is for partitioning schemes that require ongoing maintenance. Most text based (hashed) partitioning is a once and done setup and requires a completely different kind of (and more complex) configuration than time/serial. I've had many people request this feature, and one user is contributing some work that may lead to it. So, I do plan on trying to implement it, but it isn't a high priority for me at this time. 
Thanks for using this tool and the suggestion!

**Comment by keithf4** [comment]
That user released his project that can do range partitioning on text fields if you'd like to check it out. So I very likely won't be doing anything like this in pg_partman in the near future.

https://github.com/moat/range_partitioning
