### ISSUE TITLE
Keep track of clustered indexes when creating child tables

### ISSUE THREAD

**Issue by antibarbie** [keithf4/pg_partman#69]
Hi, I have a request for a missing feature, (and it might be easy to implement).

We use a clustered index on our table, so that pg_repack / cluster / etc.. will properly re-order the table data.

I noticed that the child tables created with pg_partman are not clustered (in my case) on their primary keys. 

I think that the *alter table cluster on* command must be explicitly run against the new tables, so the feature is probably simply missing from pg_partman.

    -- my typical example 
    CREATE TABLE dtz
    (
      cells integer NOT NULL,
      tstamp timestamp without time zone NOT NULL,
      valuez float NOT NULL,
      CONSTRAINT dtz_pkey PRIMARY KEY (cells, tstamp) 
    );
    ALTER TABLE dtz ALTER COLUMN tstamp SET STATISTICS 5000;
     -- set the cluster index for this table
    ALTER TABLE dtz CLUSTER ON dtz_pkey;
     -- create partitions
    SELECT partman.create_parent('public.dtz', 'tstamp', 'time-static', 'yearly');
    -- check clustered indexes
    select indexrelid::regclass, * from pg_index where indisclustered

ps: should I try to add such a feature, any idea where to start looking ?

**Comment by keithf4** [comment]
Seeing as clustering is a one-time operation (when the table is subsequently updated, the changes are not clustered), I'm not sure how to effectively implement this at this time. Doing the CLUSTER command at child table creation doesn't help because there is no data. And adding that operation to the maintenance schedule would be tricky because you likely wouldn't want it to do that every time maintenance ran. 
Perhaps something like I do with the additional constraints option, where the cluster is run on older tables that are no longer touched anymore. That option will be changing how it's implemented in the next release, so would wait until 2.2.0 is out before looking into it any further.

**Comment by keithf4** [comment]
Haven't looked at clustering for a while. Reading up on it more, not sure if this is something I'd want built in at this time. There's other settings that have to be taken into account as well for clustering to be effective for different use cases. You set the statistics to a different value for one example. The FILLFACTOR is also another consideration. And typically you increase `maintenance_work_mem` higher than the normal default so it runs more efficiently.
I could possibly see about inheriting the index cluster settings from the parent, but I think actually running the cluster operation may be better done outside of this extension.

**Comment by dturon** [comment]
I have already implemented on my fork:) https://github.com/dturon/pg_partman/blob/lbox-trigger-support/sql/functions/apply_cluster.sql

**Comment by keithf4** [comment]
@dturon Oh nice! If you don't mind, I may see about incorporating those changes into mine in the future :)

**Comment by dturon** [comment]
Yes i be happy:)

**Comment by antibarbie** [comment]
@dturon really nice ! I did not thought of looking at the different forks for that feature :-)

@keithf4 Doing the CLUSTER command is out of the question, and completely unnecessary since there is no data, as you said. The trick is to do the ALTER TABLE CLUSTER ON command, just to set the cluster options, it does nothing else. It just makes sure that the next maintenance will cluster the table.

**Comment by antibarbie** [comment]
@keithf4 Indeed, statistics, etc.. are not copied either. But at least for statistics, there are workarounds.

**Comment by dturon** [comment]
@keithf4 Oh, i know ALTER TABLE CLUSTER, but forgot on it:/ I will change it, alter is better... Thx

**Comment by keithf4** [comment]
I've adapted the code from @dturon's fork to a function for the upcoming version. I used some tricks I learned from someone else in the reapply_indexes.py script to better match indexes by their definitions instead of their names. Included it below if you'd like to test it out. I have it being called in the create_partition_id/time() functions whenever a new child table is made and seems to be working so far.
```
/*
* Function to apply cluster from parent to child table
* Adapted from code fork by https://github.com/dturon/pg_partman
*/
CREATE FUNCTION apply_cluster(p_parent_schema text, p_parent_tablename text, p_child_schema text, p_child_tablename text) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
AS $$
DECLARE
    v_parent_indexdef   text;
    v_row               record;
    v_sql               text;
BEGIN

    WITH parent_info AS (
        SELECT c.oid AS parent_oid 
        FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = p_parent_schema
        AND c.relname = p_parent_tablename
    )
    SELECT substring(pg_get_indexdef(i.indexrelid) from ' USING .*$') AS index_def
    INTO v_parent_indexdef
    FROM pg_catalog.pg_index i
    JOIN pg_catalog.pg_class c ON i.indexrelid = c.oid
    JOIN parent_info p ON p.parent_oid = indrelid
    WHERE i.indisclustered = true;

    -- Loop over all existing indexes in child table for find one with matching definition
    FOR v_row IN
        WITH child_info AS (
            SELECT c.oid AS child_oid 
            FROM pg_catalog.pg_class c
            JOIN pg_catalog.pg_namespace n ON c.relnamespace = n.oid
            WHERE n.nspname = p_child_schema
            AND c.relname = p_child_tablename
        )
        SELECT substring(pg_get_indexdef(i.indexrelid) from ' USING .*$') AS child_indexdef
            , c.relname AS child_indexname
        FROM pg_catalog.pg_index i
        JOIN pg_catalog.pg_class c ON i.indexrelid = c.oid
        JOIN child_info p ON p.child_oid = indrelid
    LOOP
        IF v_row.child_indexdef = v_parent_indexdef THEN
            v_sql = format('ALTER TABLE %I.%I CLUSTER ON %I', p_child_schema, p_child_tablename, v_row.child_indexname);
            RAISE DEBUG '%', v_sql;
            EXECUTE v_sql;
        END IF;
    END LOOP;
END;
$$;
```

**Comment by dturon** [comment]
Nice work ;)

**Comment by antibarbie** [comment]
Looks nice !

**Comment by keithf4** [comment]
Version 2.3.0 has been released with this feature. Inheriting FILLFACTOR was trickier than I thought it would be, but should still be possible. I delayed that for now so I could get this release out.
