### ISSUE TITLE
Partitions getting detached from parent table as separate tables

### ISSUE THREAD

**Issue by mudasirmirza** [keithf4/pg_partman#696]
Hi,

I am new to using pg_partman and facing an issue which I am unable to understand of resolve.
I am using pg_partman with pg_cron on GCP SQL PostgreSQL version 16.4.

I have configured pg_partman with below configuration

I have configured GCP SQL with proper flags
```
cloudsql.enable_pg_cron => on
cron.database_name => "my_database_name"
```

- Creating extensions in database
```
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE SCHEMA IF NOT EXISTS partman;
CREATE EXTENSION IF NOT EXISTS pg_partman WITH SCHEMA partman;
CREATE EXTENSION IF NOT EXISTS postgis;
```
- Creating pg_partman config (daily partitions with partition column to be a timestamp in milliseconds
```
SELECT partman.create_parent(
    p_parent_table => 'public.geo_location_data', 
    p_control => 'timestamp', 
    p_interval => '86400', 
    p_premake => 30, 
    p_template_table => 'public.geo_location_data_template', 
    p_epoch => 'milliseconds', 
    p_type => 'range'
);
```

- Updating retention policy for pg_partman, as I want to keep past 90 days of partitions
```
UPDATE partman.part_config
SET retention = 90,
    retention_keep_table = true,
    infinite_time_partitions = true
WHERE parent_table = 'public.geo_location_data';
```

- Once configured, I setup pg_cron to run maintenance job
```
SELECT cron.schedule(
    '@daily',
    $$
    SELECT partman.run_maintenance();
    $$
);
```

After all the configuration, I see the partitions created to next 30 days, which is consistent with premake value which I had setup.
![image](https://github.com/user-attachments/assets/f5603c48-0249-4c12-944f-46dbeded8a42)

But what is happening is that past partitions are being detached as separate tables and not being kept as partitions
![table list](https://github.com/user-attachments/assets/514bc408-61ef-4acd-9759-9d5731f36c3a)

I am not sure what is happening here but my thoughts were that these partitions will stay as partitions in the parent table so I can query the data from them.

Can someone please help me out in understanding what am I doing wrong here.

Regards,

**Comment by keithf4** [comment]
Check the docs for the `retention` column

https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#part_config
```
retention
 * Text type value that determines how old the data in a child partition can be before it is dropped.
 * Must be a value that can either be cast to the interval (for time-based partitioning) or bigint (for number partitioning) data types.
 * Leave this column NULL (the default) to always keep all child partitions. See About section for more info.
```
You set it to the simple value `90` which when cast to `interval` results in `90 seconds`
```
keith=# select '90'::interval;
 interval 
----------
 00:01:30
(1 row)
```
Therefore, retention is detaching any child table older than 90 seconds, which is nearly all of them. You have `retention_keep_table` set to `true`, so it's just detaching them.

Set the retention value to `90 days`.

**Comment by mudasirmirza** [comment]
Hi @keithf4 ,

Thanks for the info, I have made the change as will monitor it for a day or 2 to see it this happens again.
Again, really appreciate it.

Thanks.

**Comment by keithf4** [comment]
Closing this issue for now. Please feel free to reopen if it is still a problem
