### ISSUE TITLE
Question - Can the metadata table be updated after manually deleting the partitioned table

### ISSUE THREAD

**Issue by zthhhhh** [keithf4/pg_partman#697]
I noticed that after using the `create_parent` interface, if I drop the parent table, the `part_config` still retains the corresponding metadata. This prevents me from creating a new parent table with the same name and setting up partitions again. 
Is there a way to automatically update `part_config`, or should I need to create an event trigger to make additional configurations for table `part_config`?

      -- The process to reproduce this error
      create table part_test(a int primary key,b int) partition by range (a);
      select create_parent(p_parent_table=>'public.part_test',p_control=>'a',p_interval=>'10',p_premake=>10);
      drop table part_test;

      create table part_test(a int primary key,b int) partition by range (a);
      select create_parent(p_parent_table=>'public.part_test',p_control=>'a',p_interval=>'10',p_premake=>10);

**Comment by keithf4** [comment]
You can use the `undo_partition_proc()` procedure or `undo_partition()` function and it will clean up the configuration for you. Besides the `part_config` entry, there could also be template tables created as well. These functions will clean those up too.

Note this doesn't drop the parent table, it just moves all the data from the children to a target table. So either way this will be a multi-step process.

1. Drop partitioned table yourself
2. Clean up config table & template

or 

1. Run undo function
2. Drop old parent table (and target table if not needed)

You could make an event trigger if you'd like as well. But if this is just a one off or you're just testing, that seems like a bit of overkill.

**Comment by zthhhhh** [comment]
Thanks for your response.Now I understand how to do it.
