### ISSUE TITLE
Creating partitions is missing INCLUDING STATISTICS

### ISSUE THREAD

**Issue by wulczer** [keithf4/pg_partman#701]
The [SQL to create new partition tables](https://github.com/pgpartman/pg_partman/blob/83c22e36a6ec76547aa9083d8f9a61e9f70c835f/sql/functions/create_parent.sql#L614) used in `create_parent()` and `create_partition_*()` is not propagating extended statistics from the template table.

Seems that a simple fix would be to add `INCLUDING STATISTICS` to the command.

**Comment by keithf4** [comment]
Thanks for the reminder! Been trying to keep up with these but missed this one. Will try and get this into next release

**Comment by keithf4** [comment]
Will try and see if this can be done from the parent, not the template. Would prefer not to use the template table unless absolutely necessary

**Comment by keithf4** [comment]
Added this along with COMPRESSION and STORAGE as well. Current development branch has this fix if you would like to test it.

Thanks!

**Comment by wulczer** [comment]
Confirmed it works using the development branch, thank you!

**Comment by keithf4** [comment]
Version 5.2.0 has been released with this feature
