### ISSUE TITLE
partman is not creating partition

### ISSUE THREAD

**Issue by ithirisece** [keithf4/pg_partman#707]
partman is not creating partition after migrating databases from RHEL To RockyOS. 

Auto partition is enabled for the tables.

Is this the know issue? Any workaround for this issue? 

       Name        | Version |   Schema   |                        Description
--------------------+---------+------------+-----------------------------------------------------------
 pg_partman         | 4.6.2   | public     | Extension to manage partitioned tables by time or ID

**Comment by keithf4** [comment]
I'm not aware of any issues on any specific OS with pg_partman.

What version of RHEL and what version of RockyOS did you migrated between? Ex. 7 to 8?

Any errors in the postgres logs or if you manually try and run the maintenance function/procedure?

Is new data being inserted into the partition set?

**Comment by ithirisece** [comment]
we noticed this issue on few other database also. Not sure if we need to any changes in the way we create partition tables. Partman is not creating new partitions after the initial partition creation.kindly advice.

Initially we were under the impression that it could be due to OS Migration but we notice this issue on new builds also. 

Table config details

-[ RECORD 1 ]--------------+-------------------------------------
parent_table               | tablename1
control                    | create_date_time
partition_type             | native
partition_interval         | 1 mon
constraint_cols            |
premake                    | 12
optimize_trigger           | 4
optimize_constraint        | 30
epoch                      | none
inherit_fk                 | t
retention                  | 3 months
retention_schema           |
retention_keep_table       | f
retention_keep_index       | t
infinite_time_partitions   | t
datetime_string            | YYYY_MM
automatic_maintenance      | on
jobmon                     | t
sub_partition_set_full     | f
undo_in_progress           | f
trigger_exception_handling | f
upsert                     |
trigger_return_null        | t
template_table             | public.template_tablename1
publications               |
inherit_privileges         | f
constraint_valid           | t
subscription_refresh       |
drop_cascade_fk            | f

OS version:

NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"

**Comment by keithf4** [comment]
What version of pg_partman? By your configuration, I do see that you are on some version of 4.x because there's still options for triggers. Type `\dx` in psql and it will show you the version. If you are doing new deployments, I would highly recommend using the latest version of 5.x of pg_partman.

I see in the example here that you do have `infinite_time_partitions` set to true. So for this partition set, it should continue to make new partitions. Are you using the background worker to run maintenance or are you calling maintenance via some external scheduler?

I'd asked about what version of RHEL you came from due to this issue of going between 7 and 8. Hadn't seen that affect pg_partman, but wanted you to at least be aware of it.
https://wiki.postgresql.org/wiki/Locale_data_changes

**Comment by ithirisece** [comment]
Thanks for the update. we use background worker to run maintenance.

$ rpm -qa | grep pg_partman
pg_partman_14-4.6.2-1.rhel8.x86_64

        Name        | Version |   Schema   |                        Description
--------------------+---------+------------+-----------------------------------------------------------
 pg_partman         | 4.6.2   | public     | Extension to manage partitioned tables by time or ID

**Comment by ithirisece** [comment]
> I'm not aware of any issues on any specific OS with pg_partman.
> 
> What version of RHEL and what version of RockyOS did you migrated between? Ex. 7 to 8?
> 
> Any errors in the postgres logs or if you manually try and run the maintenance function/procedure?
> 
> Is new data being inserted into the partition set?


please find the errors we see in postgres logs

2024-11-22 06:37:44 EST [698365-2] ERROR:  updated partition constraint for default partition "partiton_default" would be violated by some row
        CONTEXT: SQL statement "ALTER TABLE <tablename> ATTACH PARTITION partition_p2024_11 FOR VALUES FROM ('2024-11-01 00:00:00-04') TO ('2024-12-01 00:00:00-05')"
        PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,text) line 249 at EXECUTE
        PL/pgSQL function run_maintenance(text,boolean,boolean) line 279 at assignment
        SQL statement "SELECT "public".run_maintenance(p_analyze := false, p_jobmon := false)"
        DETAIL:
        HINT:
        CONTEXT: PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,text) line 509 at RAISE
        PL/pgSQL function run_maintenance(text,boolean,boolean) line 279 at assignment
        SQL statement "SELECT "public".run_maintenance(p_analyze := false, p_jobmon := false)"
        DETAIL:
        HINT:
2024-11-22 06:37:44 EST [698365-3] CONTEXT:  PL/pgSQL function run_maintenance(text,boolean,boolean) line 408 at RAISE
        SQL statement "SELECT "public".run_maintenance(p_analyze := false, p_jobmon := false)"

**Comment by keithf4** [comment]
There's your answer. A new child table cannot be created if data that matches its boundaries already exists in the default.

You'll need to either delete that data from the default if it is invalid or use the `partition_data_proc()` procedure to move it out of the default and put it into the proper child tables. Note that that this can cause gaps in the child tables that exist. You can use the `partition_gap_fill()` function to fix that.

To keep a better eye on this in the future, you can use the `check_default()` function in your monitoring to watch for data going into the default. If it keeps happening frequently for future data, you may need to adjust your premake value to make sure you're keeping new child tables made that cover your expected data window.

**Comment by ithirisece** [comment]
since the new partition doesn't exist the records are inserted into default partition. Later when it checks and try to create the new partition it fails with this error message. The issue here is new partition is not created. we observed this issue on other database partitions also.

**Comment by keithf4** [comment]
Yes, this is how declarative partitioning works in PostgreSQL. It's not something special about pg_partman, it's a core PG feature. You cannot have two different child tables that can contain the same data. The only data that can ever exist in the default is data that cannot exist in any other child. So if you then try and add a child table later that matches data in the default, you'd be making two destination children that contain the same data. PostgreSQL does not allow this.

Before you can add the new child table, you must remove that data from the default.

**Comment by ithirisece** [comment]
I get it. it can't have the records on both default and child partition. 

It didn't create any new partition after initial partition creation. that is the issue here.

**Comment by keithf4** [comment]
For version 4.x of pg_partman, the background worker calls the `run_maintenance()` function which does all partition maintenance in a single transaction. If any error is encountered, all maintenance is rolled back, so no child tables are created.

So if you had a partition set with data in the default before another new partition set was created, the error being generated from that old partition set would cause all new maintenance to fail.

Version 5.x changes to using `run_maintenance_proc()` for the background worker, so each partition set is run in its own transaction. However, it will only have committed the partition sets that succeeded before an error is encountered.

**Comment by keithf4** [comment]
Closing this issue for now. Please feel free to re-open if you still have any questions about this issue.
