### ISSUE TITLE
Is pg_partman affected by the recent PG ABI breakage?

### ISSUE THREAD

**Issue by dtseiler** [keithf4/pg_partman#708]
Good afternoon,

We are currently on PG 15 but have pinned to an archived apt  repo version of pg_partman (4.7.5) due to not having the resources yet to perform the work needed to upgrade our many instances to pg_partman >= 5.0. I'll admit I don't fully grasp the problem with the recent minor/patch releases of PostgreSQL, but I wanted to check if there is anything that would prevent the latest PG 15 minor version from working with the archived Ubuntu/apt build of pg_partman (assuming they aren't recompiling the archived extensions). i.e. is it safe to upgrade to the latest PG with the older pg_partman or do we need to hold off until we can upgrade pg_partman?

We do appreciate the tech debt that we're in and will be planning to be able to upgrade to a current/supported version of pg_partman now that a couple of major migration projects are behind us.

**Comment by keithf4** [comment]
pg_partman was not affected by this issue. Also, a new minor release has been done that fixed the ABI breakage. 

https://www.postgresql.org/about/news/postgresql-172-166-1510-1415-1318-and-1222-released-2965/

So if you update to the absolute latest version (15.10 in your case) you should be fine for all extensions.

**Comment by dtseiler** [comment]
OK great. I wasn't sure if the new minor release still required re-compiling or not. 

Thanks for all of the information! Take care.
