### ISSUE TITLE
Cannot upgrade partman from Postgres 16.4 to Postgres 17.2

### ISSUE THREAD

**Issue by jeanloesch** [keithf4/pg_partman#711]
Good morning,

My postgres server runs under Postgres 16.4 with the extension pg_partman 5.1.0 (pg_partman_16-5.1.0-1PGDG.rhel8.x86_64).
I tried to upgrade it to Postgres 17.2 (with pg_partman 5.2.0 : pg_partman_17-5.2.0-1PGDG.rhel8.x86_64).

pg_upgrade worked fine but the upgrade of pg_partman failed.

psql -f update_extensions.sql
Vous êtes maintenant connecté à la base de données « argos_db » en tant qu'utilisateur « postgres ».
psql:update_extensions.sql:2: ERROR:  syntax error at or near "DECLARE"

It seems like the file pg_partman--5.1.0--5.2.0.sql has some bugs.

Could you please help ?

Thanks.

Best regards.

**Comment by keithf4** [comment]
Can you attach the `pg_partman--5.1.0--5.2.0.sql` file that was installed?

**Comment by jeanloesch** [comment]
Hi Keith4. Here it is.
[pg_partman--5.1.0--5.2.0.sql.txt](https://github.com/user-attachments/files/17960389/pg_partman--5.1.0--5.2.0.sql.txt)

**Comment by keithf4** [comment]
Thanks. I'm able to reproduce now. Will try and get a fix out as soon as I can

**Comment by keithf4** [comment]
Not sure if you're able to test this in a non-prod environment, but I have a fix up in the 5.2.1 branch for this

https://github.com/pgpartman/pg_partman/tree/5.2.1

Thankfully it's not an issue in 5.2.0 itself, it's just the update file. I'll try and have a new release out next week that should allow the package managers to push a new release out and overwrite this file when the package updates.

**Comment by keithf4** [comment]
Version 5.2.1 has been released and should hopefully correct this error. Please let me know

**Comment by jeanloesch** [comment]
Hi Keith4,

Thank you very much. I will try and let you know as soon as the RPM is available on download.postgresql.org.
