### ISSUE TITLE
epoch milliseconds timestamps

### ISSUE THREAD

**Issue by cristihcd** [keithf4/pg_partman#75]
Hello,

We are trying to use epoch partitioning for a time series table. The date column is represented as epoch time with milliseconds (bigint). 

For example, this query would return the date: 
```SQL
SELECT to_timestamp(1448893550206/1000)
```

Do you have a suggestion as to how we should proceed? 

Thank you.

**Comment by keithf4** [comment]
As of version 2.2.0, you can partition by epoch by setting the "p_epoch" attribute when creating the partition set. This allows you to have a integer based control column, but the partitioning will be based on whatever time interval you give it and partitions names will be time-based.

Please see the doc file for more info https://github.com/keithf4/pg_partman/blob/master/doc/pg_partman.md

**Comment by cristihcd** [comment]
Hello Keith,

Yes, p_epoch is the option we want to use. The problem is that pg_partman assumes the epoch contains seconds, not milliseconds. 

When creating the partitions, the date is wrong because of this calculation:

```SQL
SELECT to_timestamp(1448893550206);
"47883-08-11 09:36:46.000128+03"
```

instead of this calculation:

```SQL
SELECT to_timestamp(1448893550206/1000);
"2015-11-30 16:25:50+02"
```

So for this type of epoch timestamp with milliseconds, the timestamp value should be divided by 1000. 

I don't know where to modify this in the source code (safely). Maybe you could give me some pointers or another suggestion.

Thank you!

**Comment by keithf4** [comment]
Yeah, I'm not sure how I'm going to account for that. Even the to_timestamp() function assumes the value you're giving it is seconds, so that's the assumption I'm going to make to support the most common case.

To fix this, you'd have to look through the code for where I check for the value of either the p_epoch function parameter or the epoch value from the config table (usually stored as the variable v_epoch). In that condition I call the to_timestamp() function on the control column when it's true and that's where you'd have to add the division by 1000. 

Some examples would be https://github.com/keithf4/pg_partman/blob/master/sql/functions/create_partition_time.sql#L157
https://github.com/keithf4/pg_partman/blob/master/sql/functions/partition_data_time.sql#L60

You'll have to maintain a custom fork, though. At this time I can't foresee there being many major conflicts with such a fork, but I can't guarantee there won't be any.

**Comment by keithf4** [comment]
Another option would be to create an additional column that stores the value divided by 1000 and partition on that. It could be maintained via a trigger. Unfortunately I don't support trigger inheritance at this time, but that could be another customization you could do in this case. I do have plans for that at some point, but it's a major feature that I probably won't get to for a while.

**Comment by dturon** [comment]
you can make copy of to_timestamp function in partman schema that do this work and change search_path
```sql
CREATE FUNCTION partman.to_timestamp(ts bigint) RETURNS timestamptz AS $$ SELECT pg_catalog.to_timestamp(($1/1000)::float)$$ LANGUAGE SQL;
```
change search_path for role that run maintenance
```sql
SET search_path TO partman,public;
--or
ALTER ROLE partman_maintenance SET search_path TO partman,public;

SELECT to_timestamp(1448893550206);
      to_timestamp      
------------------------
 2015-11-30 15:25:50+01

```
hope helps:)

**Comment by dturon** [comment]
sorry to_timestamp function is used too in other partition types so works only if you have only all parent tables based on epoch ...

**Comment by cristihcd** [comment]
Thanks dturon, interesting idea! I will try it, we only have one table and one partitioning type.

What do you mean by 'all parent tables based on epoch'?

Also, if I alter the search path only for the partitioning role, it shouldn't affect other connections.

**Comment by dturon** [comment]
I found usage function to_timestamp in source code in other places then only managing epoch partitions, but with other argument type (text), so probably not make any problems ... and don't have side effects in partitions with timestampt based type.   

Better set search path for role that insert data into table too - maybe to_timestamp used in trigger partition function too don't know and now don't have time to check. (Need reconnect after set search_path for role)

**Comment by keithf4** [comment]
Just FYI, I'm working on adding this feature in https://github.com/keithf4/pg_partman/issues/150

Will be adjusting the epoch config column as I mentioned there to account for the extra math required.

**Comment by cristihcd** [comment]
Hello Keith,

That is indeed great news. I've been using the workaround in production
with no issues (altered search path for partman role, function to trim
milliseconds).

Will try the patch from #150 on a system.

Thank you.
