### ISSUE TITLE
undo_partition.py error if there are no child tables

### ISSUE THREAD

**Issue by martinmarques** [keithf4/pg_partman#77]
If when running undo_partition.py your parent table doesn't have any more child tables (so it's not a parent) you'll get an error like this (this is on 1.8.7, but same happens on 2.x)

postgres@lxdbpart:~$ /usr/lib/postgresql/9.3/bin/undo_partition.py --parent public.my_parent_table --droptable -b 5 --type time --connection "dbname=testing"
Attempting to turn off autovacuum for partition set...
        ... Success!
Traceback (most recent call last):
  File "/usr/lib/postgresql/9.3/bin/undo_partition.py", line 186, in <module>
    total = undo_partition_data(conn, partman_schema)
  File "/usr/lib/postgresql/9.3/bin/undo_partition.py", line 126, in undo_partition_data
    cur.execute(sql, li)
psycopg2.InternalError: Configuration for given parent table not found: public.my_parent_table

**Comment by keithf4** [comment]
Unsure what you're considering broken here. The error `Configuration for given parent table not found:...` only occurs when the configuration info for the given table does not exist in the `part_config`. The `undo_partition` functions only remove configuration info if no child tables are left for a partition set. So the only way I can see getting to the point where you got this error is if you completely unpartitioned a table and it's no longer managed by pg_partman.

**Comment by keithf4** [comment]
I've released version 2.2.3 which contains a lot of optimization in the undo partitioning code. Please let me know if this is still an issue.
