### ISSUE TITLE
function partman.check_name_length does not exist

### ISSUE THREAD

**Issue by hamann** [keithf4/pg_partman#81]
After upgrading to 9.5 I get the following error message with pg_partman 2.2.0 on inserts

```sql
ERROR:  function partman.check_name_length(unknown, unknown, text, boolean) does not exist at character 8
```

Before upgrading I created a sql dump, installed 9.5, installed pg_partman with same version as 9.4 and imported the dump. Did I miss something?

**Comment by hamann** [comment]
```sql
test=# \dx
                               List of installed extensions
    Name    | Version |   Schema   |                     Description
------------+---------+------------+------------------------------------------------------
 pg_partman | 2.2.0   | partman    | Extension to manage partitioned tables by time or ID
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

test=\dx+
                                        Objects in extension "pg_partman"
                                               Object Description
-----------------------------------------------------------------------------------------------------------------
 function partman.apply_constraints(text,text,boolean,bigint,boolean)
 function partman.apply_foreign_keys(text,text,bigint,boolean)
 function partman.check_name_length(text,text,boolean)
 function partman.check_parent()
 function partman.check_partition_type(text)
 function partman.check_subpartition_limits(text,text)
 function partman.check_subpart_sameconfig(text)
 function partman.check_version(text)
...
```

**Comment by keithf4** [comment]
Just to clarify, you're getting this error when inserting to a table managed by pg_partman?

If so, you may have a trigger left over from a previous version of pg_partman. In version 2.1.0, the check_name_length() arguments were changed. Normal maintenance of a table should have taken care of recreating the trigger function on that table.

If not, run `create_function_id('schemaname.tablename')` or `create_function_time('schemaname.tablename')` for that partition set to recreate the trigger function for it.

I'd also recommend updating to the latest version of pg_partman (2.2.2) as part of your database upgrade. There were some bug fixes there as well.

**Comment by hamann** [comment]
Just found out that we used pg_partman 2.0.0 in 9.4, not 2.2.0, so sorry for any inconvenience :/
I upgraded to 2.2.2 and everything works fine now, thanks a lot!

**Comment by keithf4** [comment]
No problem. Glad to hear things are working!
