### ISSUE TITLE
UnboundLocalError when removing Indexes from parent table

### ISSUE THREAD

**Issue by cdhouch** [keithf4/pg_partman#86]
Taken from 2.2.2 -

-bash-4.1$ reapply_indexes.py -p i2b2demodata.observation_fact -c "host=localhost dbname=I2B2test"
Traceback (most recent call last):
  File "/opt/PostgresPlus/9.5AS/bin/reapply_indexes.py", line 305, in <module>
    reindex_proc(c[0], c[1], parent_index_list, partman_schema)
  File "/opt/PostgresPlus/9.5AS/bin/reapply_indexes.py", line 268, in reindex_proc
    drop_index(conn, child_schemaname, child_tablename, child_index_list, parent_index_list)
  File "/opt/PostgresPlus/9.5AS/bin/reapply_indexes.py", line 148, in drop_index
    if not parent_found:
UnboundLocalError: local variable 'parent_found' referenced before assignment

Temporarily fixed with:
--- reapply_indexes.py	2015-11-13 17:04:47.000000000 -0600
+++ /opt/PostgresPlus/9.5AS/bin/reapply_indexes.py	2016-02-02 16:06:16.209875496 -0600
@@ -139,7 +139,8 @@
                 # if there is a parent index that matches the child index
                 # don't try to drop it - we'd just have to recreate it
                 chinddef = pat.search(d[0])
-                for p in parent_index_list:
+                parent_found = False
+		for p in parent_index_list:
                     parent_found = False
                     parinddef = pat.search(p[0])
                     if chinddef.group('index_def') == parinddef.group('index_def'):

-bash-4.1$ reapply_indexes.py -p i2b2demodata.observation_fact -c "host=localhost dbname=I2B2test"
DROP INDEX "i2b2demodata"."observation_fact_p0_concept_cd_idx"
ANALYZE "i2b2demodata"."observation_fact_p0"
DROP INDEX "i2b2demodata"."observation_fact_p100000000_concept_cd_idx"
ANALYZE "i2b2demodata"."observation_fact_p100000000"
DROP INDEX "i2b2demodata"."observation_fact_p200000000_concept_cd_idx"
ANALYZE "i2b2demodata"."observation_fact_p200000000"
DROP INDEX "i2b2demodata"."observation_fact_p300000000_concept_cd_idx"
ANALYZE "i2b2demodata"."observation_fact_p300000000"
DROP INDEX "i2b2demodata"."observation_fact_p400000000_concept_cd_idx"
ANALYZE "i2b2demodata"."observation_fact_p400000000"

**Comment by keithf4** [comment]
Thanks! Will include fix with new release I'm getting out this week.

**Comment by keithf4** [comment]
Although, the only way I can see this happening is if you had no indexes on the parent. I agree it should be handled like this to avoid a python error, but I would hope you at least have an index on the control column. Otherwise that would greatly affect the performance of partition maintenance and queries in general.

**Comment by cdhouch** [comment]
We're bulk loading data into the partitioned table using COPY (a few TB worth).  I needed a fast way to drop all the indexes before the bulk load.  We will reapply afterwards.

**Comment by keithf4** [comment]
That's understandable. Thanks again for the bug fix!

**Comment by keithf4** [comment]
Pushed out v2.2.3 that incorporates this fix.
