### ISSUE TITLE
Split schema and table name

### ISSUE THREAD

**Issue by Crack** [keithf4/pg_partman#87]
Currently I have 3700 partman-managed tables (database has 50k tables in total). partman defines partitioned table as one value, which forces it to make queries like

    -- 140 ms on my db
    SELECT schemaname, tablename
      FROM pg_catalog.pg_tables
     WHERE schemaname ||'.'||tablename = 'partman.part_config';

while an indexed select would take 1 ms or less:

    SELECT schemaname, tablename
      FROM pg_catalog.pg_tables
     WHERE schemaname = 'partman'
       AND tablename = 'part_config';

If this configuration was split into separate schema and table values, then some partman maintenance queries could be simplified and made much faster.

**Comment by keithf4** [comment]
I fixed this in version 2.2.3 in several places due to https://github.com/keithf4/pg_partman/issues/78

If you see it being done anywhere else that I missed, please let me know.

**Comment by keithf4** [comment]
Actually nevermind, yeah, I see where I'm doing that a lot more than I thought. I'll work on fixing that for next version. Thanks!

**Comment by Crack** [comment]
Yes, it helped a lot, and thanks to that I could throw away our monkey-patched code. Thanks for looking into it.

**Comment by keithf4** [comment]
Version 2.3.0 is released and contains this catalog lookup fix. Had to do it in quite a few places, so if you come across any I've missed, please let me know.
