### ISSUE TITLE
missing "or" for "CREATE REPLACE"

### ISSUE THREAD

**Issue by hvisage** [keithf4/pg_partman#94]
Line 1648 is missing the "OR", else you'll get:

postgres=# CREATE EXTENSION pg_partman SCHEMA partman;
ERROR:  syntax error at or near "REPLACE"

adding the "or":

postgres=# CREATE EXTENSION pg_partman SCHEMA partman;
CREATE EXTENSION

1645 /*
1646  * Function to turn a table into the parent of a partition set
1647  */
1648 CREATE or REPLACE FUNCTION create_parent(
1649     p_parent_table text

**Comment by keithf4** [comment]
Will get a fix out for this today. Thanks!

**Comment by keithf4** [comment]
This has been fixed in v2.3.1

**Comment by hvisage** [comment]
:)
