### ISSUE TITLE
error installing (ubuntu 14.04 postgresql 9.4)

### ISSUE THREAD

**Issue by joaoluizmf** [keithf4/pg_partman#95]
When I do a "make install" I got the following error:

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -fpic -I. -I./ -I/usr/include/postgresql/9.4/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -c -o src/pg_partman_bgw.o src/pg_partman_bgw.c
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
make: *** [src/pg_partman_bgw.o] Error 1

**Comment by keithf4** [comment]
Something seems to be wrong with your gcc installation or whatever version of gcc pg_config thinks is installed. -fstack-protector-strong was introduced into gcc in version 4.9 (https://outflux.net/blog/archives/2014/01/27/fstack-protector-strong/). 
Did pg_config get compiled with a different version of gcc than you're trying to install this extension with?
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -fpic -I. -I./ -I/opt/pgsql946/include/server -I/opt/pgsql946/include/internal -D_GNU_SOURCE   -c -o src/pg_partman_bgw.o src/pg_partman_bgw.c -MMD -MP -MF .deps/pg_partman_bgw.Po
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -fpic -L/opt/pgsql946/lib -Wl,--as-needed -Wl,-rpath,'/opt/pgsql946/lib',--enable-new-dtags  -shared -o src/pg_partman_bgw.so src/pg_partman_bgw.o
```

**Comment by joaoluizmf** [comment]
Tks!
I tried with gcc 5.30 and worked like a charm!
